'AdjustmentList'.list()
'Inventory Adjustments'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Refresh'.action({act: "refresh"})
'Download to Excel'.action({act: 'excel'})
'Adjustment'.datatype()
'adjustmentNumber'.field({key: true})
'location'.field({refersTo: 'Location', allowEmpty: false})
'date'.field({date: true})
'product'.field({refersTo: 'products', allowEmpty: false})
'quantity'.field({numeric: true})
'taxPct'.field({numeric: true, decimals: 2, caption: "Tax %"})
'lineCostIncTax'.field({numeric: true, minDecimals: 2, maxDecimals: 6, caption: "Line Total (Inc Tax)"})
'View'.action({place: 'row', act: 'edit'})
'AdjustmentMaint.js'.maintSpecname()

'AdjustmentList'.defaultSort({field: "date", descending: true})

