'ARInvoicePdf'.output({rowsPerPage: 9})
'INVOICE'.title()
'Credit'.datatype()

'Header'.section({pageHeading: true})
'creditNumber'.field({caption: "Invoice Number"})
'customerReference'.field()
"date".field()
'dueDate'.field()
'billingNameAndCompany'.field({caption: "Bill To"})
'billingAddress'.field({caption: ""})
'billingEmailAndPhone'.field({caption: ""})
'ourBusinessName'.field({caption: "From"})
'ourFromAddress'.field({caption: ""})
'ourContactDetails'.field({caption: ""})
'ourTaxId'.field({caption: "Tax ID"})
'trackingNumbers'.field({caption: 'Tracking Number'})

'Lines'.manifest()
'CreditLine'.datatype()
'productUniqueName'.field({caption: "Product", width: 82})
'productSku'.field({caption: "SKU", width: 15})
'quantity'.field({width: 18, caption: "Qty"})
'unitPriceExclTaxFX'.field({caption: "Price", width: 18})
'lineValueFX'.field({caption: "Amount", width: 20})

'Footer'.section({outputFooter: true, width: 130, rightAlign: true})
'Credit'.datatype()
'shippingExclTaxFX'.field({caption: "Shipping", width: 65})
'feesExclTaxFX'.field({caption: "Fees", width: 65})
'taxFX'.field({width: 65, caption: "Tax"})
'totalWithCurrency'.field({caption: "Invoice Total", rightAlign: true, width: 65})
'terms'.field({width: 65, rightAlign: true})
'paymentInstructions'.field({width: 65, rightAlign: true})
'paymentLink'.field({showAsLink: true, caption: '', rightAlign: true, linkText: 'Pay Now', width: 50})
