'CarrierList'.list()
'Carriers'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Carrier'.datatype()
'carrierName'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'CarrierMaint.js'.maintSpecname()
