'ConsolidationSettings'.maint({icon: 'Cog'})
'Consolidation Settings'.title()
'Back'.action({act: 'cancel'})
'OK'.action({act: 'ok'})
'Consolidation'.datatype({singleton: true, plex: true})

'Sites'.manifest()
'Add Constituent Site'.action({act: 'add'})
'Constituent'.datatype()
'siteName'.field({caption: 'Constituent Site'})
'url'.field({caption: 'URL'})
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'ConstituentMaint.js'.maintSpecname()
