'DeductionList'.list()
'Commission Deductions'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Deduction'.datatype()
'deductionNumber'.field()
'customerIds'.field({caption: 'Customers'})
'productSkus'.field({caption: 'Products'})
'productSupplierCodes'.field({caption: 'Product Suppliers'})
'agentWCUserNames'.field({caption: 'Agents'})
'type'.field()
'deductionPercent'.field({numeric: true, decimals: 2, caption: 'Deduction %'})
'deductionAmount'.field()
'active'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'DeductionMaint.js'.maintSpecname()
