'DiscountList'.list()
'Discount Rules'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Customer Groups'.action({spec: 'GroupList.js'})
'Download to Excel'.action({act: 'excel'})
'Discount'.datatype()
'description'.field({key: true})
'categories'.field({caption: 'Product Categories'})
'groups'.field({caption: 'Cust Groups'})
'discountType'.field()
'percentage'.field()
'amount'.field()
'active'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'DiscountMaint.js'.maintSpecname()

