'DriverList'.list()
'Drivers'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Driver'.datatype()
'driverName'.field()
'driverLicense'.field()
'defaultTruck'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'DriverMaint.js'.maintSpecname()
