'GenreList'.list()
'Customer Types'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Genre'.datatype()
'description'.field()
'notes'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'GenreMaint.js'.maintSpecname()
