'ImpostList'.list()
'Imposts'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Impost'.datatype()
'description'.field()
'customerMetaFieldName'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'ImpostMaint.js'.maintSpecname()
