'MagnitudeList'.list()
'Opportunity Sizes'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Magnitude'.datatype()
'description'.field()
'notes'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'MagnitudeMaint.js'.maintSpecname()
