'ProbabilityList'.list()
'Lead Probabilities'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Probability'.datatype()
'description'.field()
'notes'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'ProbabilityMaint.js'.maintSpecname()
