'Profit'.datatype({transient: true})
'product'.field({refersTo: 'products', key: true, showAsLink: true})
'salesQuantity'.field({numeric: true, showTotal: true})
'salesValue'.field({numeric: true, decimals: 2, showTotal: true})
'avgUnitPrice'.field({numeric: true, decimals: 2, caption: "Avg Unit Sale Price"})
'costOfGoodsSold'.field({numeric: true, decimals: 2, caption: "Cost of Goods Sold", showTotal: true})
'avgUnitCost'.field({numeric: true, decimals: 2})
'grossProfitValue'.field({numeric: true, decimals: 2, showTotal: true})
'grossProfitPercent'.field({numeric: true, decimals: 2, caption: "Gross Profit %", showTotal: true})
'taxValue'.field({numeric: true, decimals: 2, showTotal: true})
'sku'.field({indexed: true, hidden: true})
'finalAvgUnitCost'.field({numeric: true, decimals: 2})
