'Source'.datatype()
'description'.field({key: true})
'applicableSpecnames'.field()
'readOnly'.field({yesOrNo: true})

'Source'.data(async function() {
  let res = []

  let parmsToApplicableSpecNames = aParms => {
    let res = ''
    if ( aParms.invLev )
      res = res.appendWithSep("InventoryLevels.js", ",")
    if ( aParms.labels )
      res = res.appendWithSep("LabelsPdf.js", ",")
    return res
  }
  
  let addSource = (aParms) => {
    let applicableSpecnames = parmsToApplicableSpecNames(aParms)
    let readOnly = aParms.allowEdit ? "No" : "Yes"
    res.push({description: aParms.description, applicableSpecnames: applicableSpecnames, readOnly: readOnly})
  }

  let addPalletMultiSource = field => {
    for ( var i = 1; i <= 10; i++ ) {
      addSource({description: "Pallet." + field + global.padWithZeroes(i, 2), labels: true})
    }
  }

  let addPalletMultiSources = () => {
    addPalletMultiSource('lotNumber')
    addPalletMultiSource('lotQuantity')
    addPalletMultiSource('lotDescription')
  }

  let addNativeSources = () => {
    addSource({description: "Caption Only", labels: true})
    addSource({description: "Inventory.quantityOnHand", invLev: true})
    addSource({description: "Inventory.quantityOnPurchaseOrders", invLev: true})
    addSource({description: "Inventory.quantityBeingManufactured", invLev: true})
    addSource({description: "Inventory.quantityOnWOLines", invLev: true})
    addSource({description: "Inventory.avgUnitCost", invLev: true, allowEdit: true})
    addSource({description: "Inventory.inventoryValue", invLev: true})
    addSource({description: "Inventory.inventoryValue2", invLev: true})
    addSource({description: "Inventory.inventoryValueExclTax", invLev: true})
    addSource({description: "Inventory.inventoryValueExclConsignment", invLev: true})
    addSource({description: "Inventory.inventoryValueExclConsignmentExclTax", invLev: true})
    addSource({description: "Inventory.inventoryValueRetail", invLev: true})
    addSource({description: "Inventory.minQuantity", invLev: true, allowEdit: true})
    addSource({description: "Inventory.maxQuantity", invLev: true, allowEdit: true})
    addSource({description: "Inventory.recommendedRetailPriceIncTax", invLev: true, labels: true, allowEdit: true})
    addSource({description: "Inventory.sku", invLev: true, labels: true})
    addSource({description: "Inventory.notes", invLev: true, labels: true})
    addSource({description: "Inventory.supplierSku", invLev: true, labels: true, allowEdit: true})
    addSource({description: "Inventory.productName", invLev: true, labels: true})
    addSource({description: "Inventory.lastPurchaseUnitCostIncTax", invLev: true, labels: true, allowEdit: true})
    addSource({description: "Inventory.wooCommerceRegularPrice", invLev: true, labels: true, allowEdit: true})
    addSource({description: "Inventory.wooCommerceRegularPriceIncTax", invLev: true, labels: true})
    addSource({description: "Inventory.wooCommerceRegularPriceExclTax", invLev: true, labels: true})
    addSource({description: "Inventory.wcSalePrice", invLev: true, labels: true, allowEdit: true})
    addSource({description: "Inventory.wcSalePriceIncTax", invLev: true, labels: true})
    addSource({description: "Inventory.wcSalePriceExclTax", invLev: true, labels: true})
    addSource({description: "Inventory.barcode", invLev: true, labels: true})
    addSource({description: "Inventory.mainSupplier", invLev: true, labels: true})
    addSource({description: "Inventory.estSalesUnitsPerDay", invLev: true, allowEdit: true})
    addSource({description: "Inventory.priorWeeksSalesUnits", invLev: true})
    addSource({description: "Inventory.priorWeeksSalesValue", invLev: true})
    addSource({description: "Inventory.priorWeeksSalesValueExclTax", invLev: true})
    addSource({description: "Inventory.priorWeeksSASalesUnits", invLev: true})
    addSource({description: "Inventory.priorWeeksSASalesValue", invLev: true})
    addSource({description: "Inventory.priorWeeksSASalesValueExclTax", invLev: true})
    //addSource({description: "Inventory.priorSemiRecentWeeksSalesUnits", invLev: true})
    //addSource({description: "Inventory.priorRecentWeeksSalesUnits", invLev: true})
    addSource({description: "Inventory.totalSalesUnits", invLev: true})
    addSource({description: "Inventory.marginPct", invLev: true})
    addSource({description: "Inventory.saleMarginPct", invLev: true})
    addSource({description: "Inventory.lastSaleDate", invLev: true})
    addSource({description: "Inventory.lastPurchaseDate", invLev: true})
    addSource({description: "Inventory.lastReceivedDate", invLev: true})
    addSource({description: "Inventory.situation", invLev: true})
    addSource({description: "Inventory.avgUnitCostExclTax", invLev: true, allowEdit: true})
    addSource({description: "Inventory.quantityPackable", invLev: true})
    addSource({description: "Inventory.quantityPackable2", invLev: true})
    addSource({description: "Inventory.quantityPickable", invLev: true})
    addSource({description: "Inventory.quantityMakeable", invLev: true})
    addSource({description: "Inventory.quantityAllocatedForPicking", invLev: true})
    addSource({description: "Inventory.quantityAllocatedForMaking", invLev: true})
    addSource({description: "Inventory.quantityReservedForCustomerOrders", invLev: true})
    addSource({description: "Inventory.deepestCategoryName", invLev: true, labels: true})
    addSource({description: "Inventory.bundle", invLev: true})
    addSource({description: "Inventory.thumbnailImage", invLev: true})
    addSource({description: "Inventory.intrastatHSCode", invLev: true})
    addSource({description: "Inventory.shelf", invLev: true, labels: true})
    addSource({description: "Inventory.nextExpectedDeliveryDate", invLev: true})
    addSource({description: "Inventory.externalQuantityOnHand", invLev: true})
    addSource({description: "Inventory.externalPrice", invLev: true})
    addSource({description: "Inventory.externalPriceFX", invLev: true})
    addSource({description: "Inventory.quantityOnFirmPreorders", invLev: true})
    addSource({description: "Inventory.quantityOnForecastPreorders", invLev: true})
    addSource({description: "Inventory.defaultLocation", invLev: true})
    addSource({description: "Inventory.lastWOReceiptCostIncTax", invLev: true})
    addSource({description: "Inventory.lastWOReceiptCostExclTax", invLev: true})
    addSource({description: "Inventory.lastWOReceiptDate", invLev: true})
    addSource({description: "SOShipmentLine.shipmentNumber", labels: true})
    addSource({description: "SOShipmentLine.product", labels: true})
    addSource({description: "SOShipmentLine.quantityShipped", labels: true})
    addSource({description: "SOShipmentLine.descriptionAndSKU", labels: true})
    addSource({description: "SOShipmentLine.customerId", labels: true})
    addSource({description: "SOShipmentLine.orderId", labels: true})
    addSource({description: "SOShipmentLine.shipmentDate", labels: true})
    addSource({description: "SOShipmentLine.billingCompany", labels: true})
    addSource({description: "SOShipmentLine.sku", labels: true})
    addSource({description: "SOShipmentLine.quantityOrdered", labels: true})
    addSource({description: "SOShipmentLine.quantityRemaining", labels: true})
    addSource({description: "SOShipment.shipmentNumber", labels: true})
    addSource({description: "SOShipment.order", labels: true})
    addSource({description: "SOShipment.shipmentDate", labels: true})
    addSource({description: "SOShipment.shippingNameAndCompany", labels: true})
    addSource({description: "SOShipment.shippingAddress", labels: true})
    addSource({description: "SOShipment.billingNameAndCompany", labels: true})
    addSource({description: "SOShipment.billingEmailAndPhone", labels: true})
    addSource({description: "SOShipment.businessName", labels: true})
    addSource({description: "SOShipment.billingCompany", labels: true})
    addSource({description: "SOShipment.customerReference", labels: true})
    addSource({description: "SOShipment.billingPhone", labels: true})
    addSource({description: "SOShipment.bolSerialNumber", labels: true})
    addSource({description: "SOShipment.terms", labels: true})
    addSource({description: "SOShipment.loadedAt", labels: true})
    addSource({description: "SOShipment.loadDate", labels: true})
    addSource({description: "SOShipment.loadTime", labels: true})
    addSource({description: "SOShipment.outDate", labels: true})
    addSource({description: "SOShipment.outTime", labels: true})
    addSource({description: "SOShipment.deliverBy", labels: true})
    addSource({description: "SOShipment.carrier", labels: true})
    addSource({description: "SOShipment.driver", labels: true})
    addSource({description: "SOShipment.driverLicense", labels: true})
    addSource({description: "SOShipment.truckLicensePlate", labels: true})
    addSource({description: "SOShipment.trailerLicensePlate", labels: true})
    addSource({description: "POReceiptLine.receiptNumber", labels: true})
    addSource({description: "POReceiptLine.descriptionAndSKU", labels: true})
    addSource({description: "POReceiptLine.orderedQuantity", labels: true})
    addSource({description: "POReceiptLine.receivedQuantity", labels: true})
    addSource({description: "POReceiptLine.previouslyReceived", labels: true})
    addSource({description: "POReceiptLine.cancelledQuantity", labels: true})
    addSource({description: "POReceiptLine.outstandingQuantity", labels: true})
    addSource({description: "POReceiptLine.unitCost", labels: true})
    addSource({description: "POReceiptLine.unitCostFX", labels: true})
    addSource({description: "POReceiptLine.supplier", labels: true})
    addSource({description: "POReceiptLine.recommendedRetailPriceIncTax", labels: true})
    addSource({description: "POReceiptLine.recommendedRetailPriceExclTax", labels: true})
    addSource({description: "POReceiptLine.barcode", labels: true})
    addSource({description: "POReceiptLine.firstLotNumber", labels: true})
    addSource({description: "Allotment.lot", labels: true})
    addSource({description: "Allotment.expiryDate", labels: true})
    addSource({description: "Allotment.supplierLotNumber", labels: true})
    addSource({description: "WO.workOrderNumber", labels: true})
    addSource({description: "WO.fgQuantity", labels: true})
    addSource({description: "WO.fgLotsAndQuantities", labels: true})
    addSource({description: "WO.orderDate", labels: true})
    addSource({description: "WO.expectedCompletionDate", labels: true})
    addSource({description: "WO.expiryDate", labels: true})
    addSource({description: "WO.fgLocation", labels: true})
    addSource({description: "WO.notes", labels: true})
    addSource({description: "WO.receivedDate", labels: true})
    addSource({description: "Pallet.palletSerialNumber", labels: true})
    addSource({description: "Pallet.chep", labels: true})
    addSource({description: "Pallet.lineCount", labels: true})
    addSource({description: "Pallet.totalQuantity", labels: true})
    addSource({description: "Lot.lotNumber", labels: true})
    addSource({description: "Lot.expiryDate", labels: true})
    addSource({description: "Lot.supplierLotNumber", labels: true})
/*
    addSource({description: "Lot.createdDate", labels: true})
    addSource({description: "Lot.supplierName", labels: true})
*/
    addSource({description: "Inventory.purchasingUOM", invLev: true, labels: true})
    addSource({description: "Inventory.stockingUOM", invLev: true, labels: true})
    if ( global.incExc() )
      addSource({description: "Inventory.atsParentDescription", invLev: true, labels: true})
    addPalletMultiSources()
  }

  let addWCProductMetakeys = async () => {
    addSource({description: "WC Product.name", invLev: true, labels: true, allowEdit: false})
    let metakeys = await 'metakey'.bring()
    metakeys.forAll(metakey => {
      addSource({description: "WC Product." + metakey.name, invLev: true, labels: true, allowEdit: false})
    })
  }

  let addWCProductAttributes = async () => {
    let attributes = await 'attribute'.bring()
    attributes.forAll(attribute => {
      addSource({description: "WC Product Attribute." + attribute.name, invLev: true, labels: true, allowEdit: false})
    })
  }

  addNativeSources()
  await addWCProductMetakeys()
  await addWCProductAttributes()
  addSource({description: "WC Product.wpl_ebay_id", invLev: true, labels: true, allowEdit: false}) // has special treatment on server
  addSource({description: "WC Product.wpl_ebay_category_name", invLev: true, labels: true, allowEdit: false}) // has special treatment on server
  return res
})
