'TrailerList'.list()
'Trailers'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Trailer'.datatype()
'trailerLicensePlate'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'TrailerMaint.js'.maintSpecname()
