'Transition'.datatype({exportable: true})
'purchaseOrder'.field({refersTo: 'PO', indexed: true})
'oldStage'.field()
'newStage'.field()
'oldStatus'.field()
'newStatus'.field()
'transitionDate'.field({date: true})
'transitionTime'.field()
'user'.field({refersTo: 'users'})
