'TruckList'.list()
'Trucks'.title()
'Back'.action({act: 'cancel'})
'Add'.action({act: 'add'})
'Download to Excel'.action({act: 'excel'})
'Truck'.datatype()
'truckLicensePlate'.field()
'carrier'.field()
'Edit'.action({place: 'row', act: 'edit'})
'Trash'.action({place: 'row', act: 'trash'})
'TruckMaint.js'.maintSpecname()
