'Tasks'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Sales Agents'.click()
    'Add'.click()
      'Name'.enter('Jiminy Baseball')
      'WooCommerce Username'.enter('pleb')
      'Commission %'.enter('12.5')
      'OK'.click()
    'Back'.click()
  'Leads'.click()
    'Add'.click()
      'Add Lead'.shouldBeCurrentPage()
      'Name'.enter('Sunny Day')
      'OK'.click()
    'Back'.click()
  'Tasks'.click()
    'Tasks'.shouldBeCurrentPage()
    'Add'.click()
      'Add Task'.shouldBeCurrentPage()
      'Task Number'.shouldMatch('TA[0-9]*')
      'Task Number'.enter('TA01')
      'Description'.enter('Test Task 1')
      'Notes'.enter('Test Task 1 Notes')
      'Priority'.clickDropdown()
      'Priority'.shouldHaveOption('1')
      'Priority'.enter('2')
      'Status'.clickDropdown()
      'Status'.shouldHaveOption('New')
      'Status'.enter('In Progress')
      'Created Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
      'Created Date'.shouldBeReadOnly()
      'Start Date'.shouldEqualExpression('global.todayLocal()')
      'Start Date'.enterExpression('global.todayLocal().incDays(7)')
      'Estimated Hours'.enter('8')
      'Expected Finish Date'.shouldEqual('')
      'Expected Finish Date'.enterExpression('global.todayLocal().incDays(14)')
      'Actual Finish Date'.shouldntExist()
      'Actual Hours'.shouldntExist()
      'Lead'.clickDropdown()
      'Lead'.shouldHaveNOptions(2) // including blank
      'Lead'.enter('Sunny Day')
      'Customer'.clickDropdown()
      'Customer'.shouldHaveOption('Fester Inc (johnny.appleseed)')
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Agent'.clickDropdown()
      'Agent'.shouldHaveOption('Jiminy Baseball')
      'Agent'.enter('Jiminy Baseball')
      'OK'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable.0.Edit'.click()
      'Edit Task'.shouldBeCurrentPage()
      'Status'.enter('Completed')
      'Actual Finish Date'.shouldEqualExpression('global.todayLocal()')
      'Actual Finish Date'.enterExpression('global.todayLocal().incDays(-2)')
      'Actual Hours'.enter('9')
      'OK'.click()
    'Back'.click()
  'Leads'.click()
    'Tasks'.click()
      'mainTable'.shouldHaveCount(1)
      'Agents'.click()
        'mainTable'.shouldHaveCount(1)
        'Back'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Leads'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Customers'.shouldBeCurrentPage()
  'Customer Types'.click()
    'Customer Types'.shouldBeCurrentPage()
    'Add'.click()
      'Add Customer Type'.shouldBeCurrentPage()
      'Description'.enter('Type 1')
      'Notes'.enter('Type 1 Notes')
      'Add another'.click()
      'Description'.enter('Type 2')
      'Notes'.enter('Type 2 Notes')
      'OK'.click()
    'mainTable'.shouldHaveCount(2)
    'mainTable./Type 1/.Notes'.shouldEqual('Type 1 Notes')
    'Back'.click()
  'Leads'.click()
    'Leads'.shouldBeCurrentPage()
    'Customer Types'.click()
      'Customer Types'.shouldBeCurrentPage()
      'mainTable'.shouldHaveCount(2)
      'mainTable./Type 1/.Notes'.shouldEqual('Type 1 Notes')
      'Back'.click()
    'Statuses'.click()
      'Lead Statuses'.shouldBeCurrentPage()
      'Add'.click()
        'Add Lead Status'.shouldBeCurrentPage()
        'Description'.enter('Status 1')
        'Notes'.enter('Status 1 Notes')
        'Add another'.click()
        'Description'.enter('Status 2')
        'Notes'.enter('Status 2 Notes')
        'OK'.click()
      'mainTable'.shouldHaveCount(2)
      'mainTable./Status 1/.Notes'.shouldEqual('Status 1 Notes')
      'Back'.click()
    'Probabilities'.click()
      'Lead Probabilities'.shouldBeCurrentPage()
      'Add'.click()
        'Add Lead Probability'.shouldBeCurrentPage()
        'Description'.enter('50%')
        'Notes'.enter('50% Notes')
        'Add another'.click()
        'Description'.enter('25%')
        'Notes'.enter('25% Notes')
        'OK'.click()
      'mainTable'.shouldHaveCount(2)
      'mainTable./25%/.Notes'.shouldEqual('25% Notes')
      'Back'.click()
    'Opportunity Sizes'.click()
      'Opportunity Sizes'.shouldBeCurrentPage()
      'Add'.click()
        'Add Opportunity Size'.shouldBeCurrentPage()
        'Description'.enter('Size 1')
        'Notes'.enter('Size 1 Notes')
        'Add another'.click()
        'Description'.enter('Size 2')
        'Notes'.enter('Size 2 Notes')
        'OK'.click()
      'mainTable'.shouldHaveCount(2)
      'mainTable./Size 1/.Notes'.shouldEqual('Size 1 Notes')
      'Back'.click()
    'Add'.click()
      'Add Lead'.shouldBeCurrentPage()
      'Name'.enter('Sunny Day')
      'Phone'.enter('0456 784 531')
      'Email'.enter('admin@sunnyday.com')
      'URL'.enter('https://sunnyday.com')
      'Contact First Name'.enter('Icarus')
      'Contact Last Name'.enter('Aeschylus')
      'Company'.enter('Sunny Day Enterprises')
      'Address'.enter('34 Ray Way')
      'Address 2'.enter('Upper Side')
      'City'.enter('Melbourne')
      'State'.enter('VIC')
      'Postal Code'.enter('3000')
      'Country'.enter('Australia')
      'Customer Type'.enter('Type 1')
      'Status'.enter('Status 1')
      'Opportunity Size'.enter('Size 1')
      'Probability'.enter('50%')
      'Notes'.enter('Lead Notes')
      'Convert to Customer'.shouldntExist()
      'Save'.click()
      'Convert to Customer'.click()
        'Add Customer'.shouldBeCurrentPage()
        'Customer ID'.shouldntExist()
        'Name'.shouldEqual('Sunny Day')
        'Nice Name'.shouldEqual('Sunny Day')
        'Phone'.shouldEqual('0456 784 531')
        'Email'.shouldEqual('admin@sunnyday.com')
        'URL'.shouldEqual('https://sunnyday.com')
        'Customer Type'.shouldEqual('Type 1')
        'Notes'.shouldEqual('Lead Notes')
        'Billing'.usePanel()
          'First Name'.shouldEqual('Icarus')
          'Last Name'.shouldEqual('Aeschylus')
          'Company'.shouldEqual('Sunny Day Enterprises')
          'Address'.shouldEqual('34 Ray Way')
          'Address 2'.shouldEqual('Upper Side')
          'City'.shouldEqual('Melbourne')
          'State'.shouldEqual('VIC')
          'Postal Code'.shouldEqual('3000')
          'Country'.shouldEqual('Australia')
          'Phone'.shouldEqual('0456 784 531')
          'Email'.shouldEqual('admin@sunnyday.com')
        'Billing'.stopUsingPanel()
        'Shipping'.usePanel()
          'First Name'.shouldEqual('Icarus')
          'Last Name'.shouldEqual('Aeschylus')
          'Company'.shouldEqual('Sunny Day Enterprises')
          'Address'.shouldEqual('34 Ray Way')
          'Address 2'.shouldEqual('Upper Side')
          'City'.shouldEqual('Melbourne')
          'State'.shouldEqual('VIC')
          'Postal Code'.shouldEqual('3000')
          'Country'.shouldEqual('Australia')
        'Shipping'.stopUsingPanel()
        'Login'.enter('prfi_sunnyday')
        'Password'.enter('secret')
        'Notes'.enter('Modified lead notes')
        'OK'.click()
      'Edit Lead'.shouldBeCurrentPage()
      'Converted to Customer'.shouldEqual('Yes')
      'Convert to Customer'.shouldntExist()
      'OK'.click()
    'mainTable./Sunny Day/.Is Customer'.shouldEqual('Yes')
    'mainTable./Sunny Day/.Type'.shouldEqual('Type 1')
    'mainTable./Sunny Day/.Edit'.click()
      'Edit Customer'.shouldBeCurrentPage()
      'Name'.shouldEqual('Sunny Day')
      'Notes'.shouldEqual('Modified lead notes')
      'Customer Type'.enter('Type 2')
      'OK'.click()
    'mainTable./Sunny Day/.Type'.shouldEqual('Type 2')
    'Add'.click()
      'Name'.enter('Cloudy Day')
      'Phone'.enter('0458 784 531')
      'Email'.enter('admin@cloudyday.com')
      'URL'.enter('https://cloudyday.com')
      'Contact First Name'.enter('Simon')
      'Contact Last Name'.enter('Wilson')
      'Company'.enter('Cloudy Day Enterprises')
      'Address'.enter('34 Rain Way')
      'Address 2'.enter('Lower Side')
      'City'.enter('Sydney')
      'State'.enter('NSW')
      'Country'.enter('Australia')
      'Customer Type'.enter('Type 2')
      'Status'.enter('Status 2')
      'Opportunity Size'.enter('Size 2')
      'Probability'.enter('25%')
      'OK'.click()
    'mainTable./Sunny Day/.Phone'.shouldEqual('0456 784 531')
    'mainTable./Cloudy Day/.Type'.shouldEqual('Type 2')
    'mainTable./Cloudy Day/.Status'.shouldEqual('Status 2')
    'mainTable./Cloudy Day/.Size'.shouldEqual('Size 2')
    'mainTable./Cloudy Day/.Probability'.shouldEqual('25%')
    'mainTable./Cloudy Day/.Edit'.click()
      'Edit Lead'.shouldBeCurrentPage()
      'OK'.click()
    'mainTable./Cloudy Day/.Is Customer'.shouldEqual('No')
    'Back'.click()
  'Add'.click()
    'Login'.enter('prfi_mcg')
    'Name'.enter('Melbourne Cricket Ground')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Password'.enter('secret')
    'Add another'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'OK'.click()
  'Back'.click()
