'helper'.trashAll('Configuration')
'helper'.trashAll('CustomDashboard')
'helper'.trashAll('CustomSpec')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Keep Dashboard In Main Window'.enter('Yes')
  'OK'.click()
'stocktend_dashboard'.click()
  'Dashboard'.shouldBeCurrentPage()
  'Switch Dashboard'.click()
    'stComboboxDashboard'.shouldEqual('Main Dashboard')
    'stComboboxDashboard'.clickDropdown()
    'stComboboxDashboard'.shouldHaveNOptions(1)
    'Cancel'.click()
  'Configure'.click()
    'Dashboard Configuration'.shouldBeCurrentPage()
    'Dashboard Refresh Frequency (seconds)'.enter('999999')
    'Custom Specs'.click()
      'mainTable'.shouldHaveCount(0)
      'Add'.click()
        'Add Custom Spec'.shouldBeCurrentPage()
        'Name'.enter('ViewLowInventory')
        'Status'.shouldntExist()
        'Error Message'.shouldEqual('No javascript code has been entered')
        'Based On'.clickDropdown()
        'Based On'.shouldHaveOption('specs/CurrencyList.js')
        'Based On'.shouldntHaveOption('specs/POMaint.js')
        'Javascript Code'.shouldEqual('\n')
        'Based On'.enter('specs/OverduePOStock.js')
        'Javascript Code'.shouldContain("'purchaseOrder'.field({showAsLink: true}")
        'Based On'.enter('specs/ViewLowInventory.js')
        'Status'.shouldEqual('Valid')
        'Javascript Code'.shouldContain("'priorWeeksSales'.field({numeric: true, caption: \"Last X Weeks Sales\"}")
        'Javascript Code'.addLine("'testField'.field()")
        'Javascript Code'.addLine("'testField'.calculate(async inv => 'Test Value')")
        'Based On'.shouldBeReadOnly()
        'OK'.click()
        'stFormRejection'.shouldContain("ViewLowInventory already exists - please specify a different list name")
        'Javascript Code'.alterInputLine(0, "'View Low Inventory Custom'.list()")
        'Status'.shouldntExist()
        'Error Message'.shouldEqual('Name in code doesn\'t match - is "View Low Inventory Custom" - should be "ViewLowInventory"')
        'Name'.enter('View Low Inventory Custom')
        'Javascript Code'.replaceInInput('ViewLowInventory', 'View Low Inventory Custom')
        'Status'.shouldEqual('Valid')
        'Error Message'.shouldntExist()
        'Javascript Code'.alterInputLine(0, "'View Low Inventory Custom 2'.list()")
        'Status'.shouldntExist()
        'Error Message'.shouldEqual('Name in code doesn\'t match - is "View Low Inventory Custom 2" - should be "View Low Inventory Custom"')
        'Javascript Code'.alterInputLine(0, "'View Low Inventory Custom'.list()")
        'Status'.shouldEqual('Valid')
        'OK'.click()
      'Back'.click()
    'Custom Dashboards'.shouldHaveCount(0)
    'Add Custom Dashboard'.click()
      'Add Dashboard'.shouldBeCurrentPage()
      'Dashboard Name'.enter('View Low Inventory Custom')
      'Title'.enter('Sales Dashboard')
      'Status'.shouldEqual('Valid')
      'OK'.click()
      'stFormRejection'.shouldContain("Name 'View Low Inventory Custom' is already in use", 'doc')
      'Dashboard Name'.enter('POMaint')
      'OK'.click()
      'stFormRejection'.shouldContain("Name 'POMaint' is already in use", 'doc')
      'Dashboard Name'.enter('Sales Dashboard')
      'Error Message'.shouldntExist()
      'Javascript Code'.shouldContain("'Overdue PO Stock'.tile({spec: \"OverduePOStock.js\", widthPct: 50, heightPct: 50})")
      'Javascript Code'.removeInputLine(0)
      'Javascript Code'.removeInputLine(0)
      'Status'.shouldEqual('Valid')
      'Javascript Code'.addLine("'VLI Custom'.tile({spec: \"InvalidSpec.js\", widthPct: 100, heightPct: 50})")
      'Status'.shouldntExist()
      'Error Message'.shouldContain('InvalidSpec')
      'Javascript Code'.removeInputLine(2)
      'Status'.shouldEqual('Valid')
      'Javascript Code'.addLine("'VLI Custom'.tile({spec: \"InvalidSpec\", widthPct: 100, heightPct: 50})")
      'OK'.click()
    'Custom Specs'.click()
      'Add'.click()
        'Name'.enter('Sales Dashboard')
        'Based On'.enter('specs/ViewLowInventory.js')
        'Javascript Code'.replaceInInput('ViewLowInventory', 'Sales Dashboard')
        'OK'.click()
        'stFormRejection'.shouldContain("Name 'Sales Dashboard' is already in use", 'doc')
        'Back'.click()
        'Yes - Cancel my changes'.click('doc')
      'Back'.click()
    'Back'.click()
  'Switch Dashboard'.click()
    'stComboboxDashboard'.clickDropdown()
    'stComboboxDashboard'.shouldHaveNOptions(2)
    'stComboboxDashboard'.shouldHaveOption('Sales Dashboard')
    'stComboboxDashboard'.chooseOption('Sales Dashboard')
  'Custom Spec Error'.shouldContain('InvalidSpec is not a valid Custom Spec')
  'Configure'.click()
    'Custom Dashboards.0.Edit'.click()
      'Javascript Code'.removeInputLine(2)
      'Javascript Code'.addLine("'VLI Custom'.tile({spec: \"View Low Inventory Custom\", widthPct: 100, heightPct: 50})")
      'Javascript Code'.addLine('garbage')
      'Status'.shouldntExist()
      'Error Message'.shouldBeReadOnly()
      'Error Message'.shouldContain('garbage')
      'OK'.click()
    'Custom Dashboards./Sales Dashboard/.Status'.shouldEqual('Invalid')
    'Back'.click()
  'Sales Dashboard'.shouldBeCurrentPage()
  'Sales'.shouldntExist()
  'Error'.shouldEqual('This dashboard is invalid and cannot be viewed until it is reviewed and fixed. Javascript error: "garbage is not defined"')
  'Configure'.click()
    'Custom Dashboards./Sales Dashboard/.Edit'.click()
      'Edit Dashboard'.shouldBeCurrentPage()
      'Status'.shouldntExist()
      'Error Message'.shouldContain('garbage')
      'Javascript Code'.removeInputLine(3)
      'Status'.shouldEqual('Valid')
      'Error Message'.shouldntExist()
      'OK'.click()
    'Back'.click()
  'Sales Dashboard'.shouldBeCurrentPage()
  'Sales'.shouldExist()
  'Error'.shouldntExist()
  'Configure'.click()
    'Custom Specs'.click()
      'mainTable./View Low Inventory Custom/.Trash'.click()
      'mainTable./View Low Inventory Custom/.Really Trash?'.click()
        'messageDialogText'.shouldEqual("This Custom Spec cannot be trashed as it is used in Dashboard 'Sales Dashboard'", 'doc')
        'messageDialogOK'.click('doc')
      'Back'.click()
    'Back'.click()
  'browser'.back()
'helper'.trashAll('Inventory')
'helper'.trashAll('Transaction')
'helper'.trashAll('PO')
'helper'.trashAll('Supplier')
'helper'.simulateBrowserRefresh()
'stocktend_dashboard'.click() // Infinite scroll test
  'Short Stock.mainTable.5.Product'.shouldntEqual('')
  'Short Stock.mainTable.51.Product'.shouldEqual('')
  'Short Stock.mainTable.51'.scrollIntoView()
  'Short Stock.mainTable.51.Product'.shouldntEqual('')
  'browser'.back()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter('Castaways')
    'Save'.click()
    'Add another'.click()
    'Name'.enter('Bombast Corporation')
    'Save'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00003')
    'Supplier'.chooseOption('Bombast Corporation')
    'Expected Delivery Date'.enterExpression('global.todayLocal().incDays(-5)')
    'Add Line'.click()
      'Product'.chooseOption('Hoodie (H01)')
      'Quantity'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.flushCache()
'helper'.addWCOrder({product: 'Hoodie (H01)', quantity: 3, unitPrice: 20.00, orderDate: global.todayLocal().incDays(-3), status: 'wc-pending'})
'helper'.addWCOrder({product: 'Hoodie (H01)', quantity: 1, unitPrice: 20.00, orderDate: global.todayLocal().incDays(-18), status: 'wc-completed'})
'helper'.addWCOrder({product: 'Hoodie (H01)', quantity: 1, unitPrice: 20.00, orderDate: global.todayLocal().incDays(-400), status: 'wc-processing'})
'helper'.addWCOrder({product: 'Hoodie (H01)', quantity: 2, unitPrice: 20.00, orderDate: global.todayLocal().incDays(-19), status: 'wc-on-hold'})
'helper'.flushCache()
'Inventory'.click()
  'mainTable./Hoodie (H01)/.Adjust Qty'.click()
    'Quantity Change'.enter('5')
    'OK'.click()
  'mainTable./Hoodie (H01)/.Edit Product'.click()
    'Low Stock Threshold'.enter('13')
    'OK'.click()
  'Back'.click()
'stocktend_dashboard'.click()
  'Unfulfilled Sales Orders.mainPlot'.shouldExist()
  'stPlot'.attributeShouldContain('data-plot', '"Pending":54.55')
  'stPlot'.attributeShouldContain('data-plot', '"Processing":18.18')
  'stPlot'.attributeShouldContain('data-plot', '"On-hold":36.36')
  'Short Stock.mainTable'.shouldExist()
  'Short Stock.mainTable'.shouldExist()
  'Overdue PO Stock.mainTable'.shouldExist()
  'Sales.mainTable'.shouldExist()
  'Short Stock.mainTable.0.Product'.shouldEqual('Hoodie (H01)')
  'Short Stock.mainTable.0.Low Stock Threshold'.shouldEqual('13')
  'Short Stock.mainTable.0.On Purchase Orders'.shouldEqual('10')
  'Short Stock.mainTable.0.On Sales Orders'.shouldEqual('3')
  'Short Stock.mainTable.0.On Hand'.shouldEqual('1')
  'Short Stock.mainTable.0.Last 12 Weeks Sales'.shouldEqual('6')
  'Short Stock.mainTable.0.Surplus'.shouldEqual('-5')
  'Short Stock.mainTable.0.Surplus Weeks'.shouldEqual('-10.00')
  'Sales.mainTable'.shouldHaveCount(4)
  'Sales.mainTable.0.Quantity'.shouldEqual('3')
  'helper'.setProductSkuWithDifferentForeman('Long Sleeve Tee', 'LST3')
  'stocktend_home'.click()
'stocktend_dashboard'.click() //'stDashboardRefreshButton'.click()
  'Short Stock.veil'.click()
  'Short Stock.searcherviewLowInventory'.enter('L')
  'Short Stock.mainTable./Long Sleeve Tee (LST3)/'.shouldExist()
  'Short Stock.mainTable./Long Sleeve Tee (LST4)/'.shouldntExist()
  'helper'.setProductSkuWithDifferentForeman('Long Sleeve Tee', 'LST4')
  'helper'.trashOrderWithDifferentForeman('Hoodie (H01)')
  'stDashboardRefreshButton'.click()
  'Short Stock.mainTable./Long Sleeve Tee (LST3)/'.shouldntExist()
  'Short Stock.mainTable./Long Sleeve Tee (LST4)/'.shouldExist()
  'Sales.mainTable'.shouldHaveCount(3)
  'Overdue PO Stock.mainTable'.shouldHaveCount(2)
  'Overdue PO Stock.mainTable.1.Outstanding Quantity'.shouldEqual('10')
  'Sales.mainTable.0.View Order'.click()
    'View Sales Order'.shouldBeCurrentPage()
    'Back'.click()
  'Dashboard'.shouldBeCurrentPage()
  'Sales.mainTable'.shouldHaveCount(3)
  'Switch Dashboard'.click()
    'stComboboxDashboard'.chooseOption('Sales Dashboard')
  'Short Stock'.shouldntExist()
  'Sales.mainTable'.shouldHaveCount(3)
  'Sales.mainTable.0.Quantity'.shouldEqual('1')
  'VLI Custom.mainTable.0.Product'.shouldEqual('Hoodie (H01)')
  'Configure'.click()
    'Default Dashboard'.clickDropdown()
    'Default Dashboard'.shouldHaveOption('Main Dashboard')
    'Default Dashboard'.shouldHaveOption('Sales Dashboard')
    'Default Dashboard'.chooseOption('Sales Dashboard')
    'OK'.click()
  'Home'.click()
'stocktend_dashboard'.click()
  'Sales Dashboard'.shouldBeCurrentPage()
  'Configure'.click()
    'Custom Dashboards./Sales Dashboard/.Trash'.click()
    'Custom Dashboards./Sales Dashboard/.Really Trash?'.click()
    'Custom Dashboards./Sales Dashboard/'.shouldntExist()
    'Default Dashboard'.enter('Main Dashboard')
    'Custom Specs'.click()
      'mainTable./View Low Inventory Custom/.Trash'.click()
      'mainTable./View Low Inventory Custom/.Really Trash?'.click()
      'mainTable./View Low Inventory Custom/'.shouldntExist()
      'Back'.click()
    'Back'.click()
  'Dashboard'.shouldBeCurrentPage()
  'Home'.click()
'stocktend_reports'.click()
  'mainTable./Unfulfilled Sales Orders Chart/.Run'.click()
  'stPlot'.attributeShouldContain('data-plot', '"Processing":18.18')
  'Home'.click()
'helper'.flushCache()
'stocktend_reports'.click()
  'mainTable./Unfulfilled Sales Orders Chart/.Run'.click()
  'stPlot'.attributeShouldContain('data-plot', '"Processing":18.18')
  'Home'.click()
