'ReceiveAndPrint'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter("Castaways Inc")
    'OK'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00001')
    'Supplier'.enter('Castaways Inc')
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'OK'.click()
    'OK'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00002')
    'Supplier'.enter('Castaways Inc')
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'OK'.click()
    'OK'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00003')
    'Supplier'.enter('Castaways Inc')
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable'.shouldHaveCount(4) // including Total
  'Rcv & Prt Lbls'.click()
  'Rcv & Prt Lbls'.shouldntExist()
  'Cancel Rcv Prt'.click()
  'mainTable./PO00002/.Include In Rcv Prt'.shouldntExist()
  'Rcv & Prt Lbls'.click()
  'mainTable./PO00002/.Include In Rcv Prt'.toggleTick()
  'mainTable./PO00003/.Include In Rcv Prt'.toggleTick()
  'Confirm Rcv Prt'.click()
  'mainTable'.shouldHaveCount(2)
  'Confirm Rcv Prt'.shouldntExist()
  'Rcv & Prt Lbls'.shouldExist()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('2')
  'Back'.click()
'Main'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'Add Alternative'.click()
          'Add Component Alternative'.shouldBeCurrentPage()
          'Component'.shouldEqual('Tag (TA01)')
          'Component'.shouldBeReadOnly()
          'Quantity'.shouldntExist()
          'Alternative Product'.enter('Tag - Leather (TA02)')
          'Add another'.click()
          'Alternative Product'.enter('Tag - Deluxe (TA03)')
          'OK'.click()
        'Alternatives'.shouldHaveCount(2)
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('10')
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(2)
    'Lines./Tag (TA01)/.Edit'.click()
      'Product'.clickDropdown()
      'Product'.shouldHaveNOptions(3)
      'Product'.shouldHaveOption('Tag (TA01)')
      'Product'.shouldHaveOption('Tag - Leather (TA02)')
      'Product'.shouldHaveOption('Tag - Deluxe (TA03)')
      'Product'.enter('Tag - Leather (TA02)')
      'Quantity Required'.enter('50')
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Tag - Deluxe (TA03)')
      'Quantity Required'.enter('10')
      'Add another line'.click()
      'Product'.enter('Tag (TA01)')
      'Quantity Required'.enter('40')
      'OK'.click()
    'Lines'.shouldHaveCount(4)
    'Lines./Tag (TA01)/.Trash'.click()
    'Lines./Tag (TA01)/.Really Trash?'.click()
    'Lines'.shouldHaveCount(3)
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'Customize'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityBeingManufactured')
      'Caption'.enter('Quantity Being Manufactured')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityOnWOLines')
      'Caption'.enter('Quantity On WO Lines')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Back'.click()
  'searcher'.enter('TA')
  'mainTable./Tag (TA01)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Tag - Leather (TA02)/.Quantity On WO Lines'.shouldEqual('50')
  'mainTable./Tag - Deluxe (TA03)/.Quantity On WO Lines'.shouldEqual('10')
  'searcher'.enter('BS')
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('10')
  'Back'.click()
'stocktend_settings'.click()
  'Prompt to Produce Labels when Stock Received'.enter('Yes')
  'OK'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable.0.Enter Receipt'.click()
      'Received Quantity'.enter('5')
      'OK'.click()
      'messageDialogText'.shouldContain("Do you want to produce labels?", 'doc')
      'Yes'.click('doc')
      'Labels'.shouldBeCurrentPage()
      'Label Type'.shouldEqual('Inventory')
      'Source Type'.shouldEqual('Work Order Receipt')
      'Source Reference'.shouldContain('WO')
      'Download Labels PDF'.click()
      'Back'.click()
    'Receive Work Orders'.shouldBeCurrentPage()
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Prompt to Produce Labels when Stock Received'.enter('No')
  'OK'.click()
'stocktend_inventory'.click()
  'searcher'.enter('TA')
  'mainTable./Tag (TA01)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Tag - Leather (TA02)/.Quantity On WO Lines'.shouldEqual('25')
  'mainTable./Tag - Deluxe (TA03)/.Quantity On WO Lines'.shouldEqual('5')
  'searcher'.enter('BS')
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('5')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable.0.Enter Receipt'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'searcher'.enter('TA')
  'mainTable./Tag (TA01)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Tag - Leather (TA02)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Tag - Deluxe (TA03)/.Quantity On WO Lines'.shouldEqual('0')
  'searcher'.enter('BS')
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('0')
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('10')
  'Back'.click()
'AutoSerialsWO'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Designators'.click()
    'Add'.click()
      'Description'.enter('WF-WO')
      'Prefix'.enter('WO')
      'Suffix'.enter('WF')
      'OK'.click()
    'Back'.click()
  'OK'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Serial')
    'OK'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('9')
    'Expiry Date'.enter('31/12/2099')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(1)
      'OK'.click()
    'Lot Julian Date'.shouldntExist()
    'Designator'.clickDropdown()
    'Designator'.shouldHaveNOptions(2) // including blank
    'Designator'.enter('WF-WO')
    'Lot Julian Date'.shouldEqualExpression('global.todayJulian()')
    'Lot Julian Date'.enter('22254')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(9)
      'Lots.0.Number'.shouldEqual('WO22254WF-0001')
      'Lots.0.Quantity'.shouldEqual('1')
      'Lots.8.Number'.shouldEqual('WO22254WF-0009')
      'Lots.8.Quantity'.shouldEqual('1')
      'OK'.click()
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(3)
    'OK'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00002')
    'Product'.enter('Brag Set (BS01)')
    'Designator'.enter('WF-WO')
    'Finished Goods Quantity'.enter('2')
    'Lot Julian Date'.enter('22255')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(2)
      'Lots.0.Number'.shouldEqual('WO22255WF-0010')
      'Lots.0.Quantity'.shouldEqual('1')
      'Lots.1.Number'.shouldEqual('WO22255WF-0011')
      'Lots.1.Quantity'.shouldEqual('1')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'AutoLotsWO'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Designators'.click()
    'Add'.click()
      'Description'.enter('WP-WO')
      'Prefix'.enter('WO')
      'Suffix'.enter('WP')
      'Add another'.click()
      'Description'.enter('WF-WO')
      'Prefix'.enter('WO')
      'Suffix'.enter('WF')
      'OK'.click()
    'Back'.click()
  'OK'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Quantity Per Lot'.shouldntExist()
    'Serial/Lot Tracking'.enter('Lot')
    'Quantity Per Lot'.enter('10')
    'OK'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('90')
    'Expiry Date'.enter('31/12/2099')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(1)
      'OK'.click()
    'Lot Julian Date'.shouldntExist()
    'Designator'.clickDropdown()
    'Designator'.shouldHaveNOptions(3) // including blank
    'Designator'.enter('WF-WO')
    'Lot Julian Date'.shouldEqualExpression('global.todayJulian()')
    'Lot Julian Date'.enter('22253')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(9)
      'Lots.0.Number'.shouldEqual('WO22253WF-0001')
      'Lots.0.Expiry Date'.shouldEqual('Dec 31 2099')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.8.Number'.shouldEqual('WO22253WF-0009')
      'Lots.8.Expiry Date'.shouldEqual('Dec 31 2099')
      'Lots.8.Quantity'.shouldEqual('10')
      'OK'.click()
    'Lot Julian Date'.enter('22254')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(9)
      'Lots.0.Number'.shouldEqual('WO22254WF-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.8.Number'.shouldEqual('WO22254WF-0009')
      'Lots.8.Quantity'.shouldEqual('10')
      'OK'.click()
    'Finished Goods Quantity'.enter('75')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(8)
      'Lots.0.Number'.shouldEqual('WO22254WF-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.7.Number'.shouldEqual('WO22254WF-0008')
      'Lots.7.Quantity'.shouldEqual('5')
      'OK'.click()
    'Designator'.enter('WP-WO')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(8)
      'Lots.0.Number'.shouldEqual('WO22254WP-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.7.Number'.shouldEqual('WO22254WP-0008')
      'Lots.7.Quantity'.shouldEqual('5')
      'OK'.click()
    'Expiry Date'.enter('31/12/2088')
    'FG Lots'.click()
      'Lots.0.Expiry Date'.shouldEqual('Dec 31 2088')
      'OK'.click()
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(3)
    'OK'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00002')
    'Product'.enter('Brag Set (BS01)')
    'Designator'.enter('WP-WO')
    'Finished Goods Quantity'.enter('1')
    'Lot Julian Date'.enter('22254')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('WO22254WP-0009')
      'Lots.0.Quantity'.shouldEqual('1')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable.0.Enter Receipt'.click()
      'FG Lots'.click()
        'Lots.0.Number'.shouldContainExpression('global.todayJulian()')
        'OK'.click()
      'Completion Date'.enter('1/1/2023')
      'FG Lots'.click()
        'Lots.0.Number'.shouldContain('23001')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'NoUnspec'.chapter()
'helper'.trashAll('*')
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Designators'.click()
    'Add'.click()
      'Description'.enter('RB')
      'Suffix'.enter('RB')
      'OK'.click()
    'Add'.click()
      'Description'.enter('WO')
      'Suffix'.enter('WO')
      'OK'.click()
    'Back'.click()
  'Default WO Lot Designator'.enter('WO')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Quantity Per Lot'.enter('0')
    'Track Expiry Dates'.enter('Yes')
    'Default Expiry Days'.enter('30')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Designator'.shouldntExist()
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('50')
    'Expiry Date'.enter('1/1/2023')
    'Designator'.shouldEqual('WO')
    'Lot Julian Date'.enter('22253')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('22253WO-0001')
      'Lots.0.Quantity'.shouldEqual('50')
      'Lots.0.Edit'.click()
        'Quantity'.enter('10')
        'OK'.click()
      'Lots'.shouldHaveCount(2)
      'Lots.0.Number'.shouldEqual('22253WO-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.1.Number'.shouldEqual('22253WO-0002')
      'Lots.1.Quantity'.shouldEqual('40')
      'OK'.click()
    'Finished Goods Quantity'.enter('100')
    'FG Lots'.click()
      'Lots'.shouldHaveCount(3)
      'Lots.0.Number'.shouldEqual('22253WO-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.1.Number'.shouldEqual('22253WO-0002')
      'Lots.1.Quantity'.shouldEqual('40')
      'Lots.2.Number'.shouldEqual('22253WO-0003')
      'Lots.2.Quantity'.shouldEqual('50')
      'OK'.click()
    'Generate Lines'.click()
    'OK'.click()
  'Receive Work Orders'.click()
    'mainTable.0.Enter Receipt'.click()
      'Expiry Date'.shouldEqual('01/01/2023')
      'FG Lots'.click()
        'Lots'.shouldHaveCount(3)
        'Lots.0.Number'.shouldEqual('22253WO-0001')
        'Lots.0.Quantity'.shouldEqual('10')
        'Lots.1.Number'.shouldEqual('22253WO-0002')
        'Lots.1.Quantity'.shouldEqual('40')
        'Lots.2.Number'.shouldEqual('22253WO-0003')
        'Lots.2.Quantity'.shouldEqual('50')
        'OK'.click()
      'Received Quantity'.enter('200')
      'FG Lots'.click()
        'Lots'.shouldHaveCount(4)
        'Lots.0.Number'.shouldEqual('22253WO-0001')
        'Lots.0.Quantity'.shouldEqual('10')
        'Lots.0.Expiry Date'.shouldEqual('Jan 1 2023')
        'Lots.1.Number'.shouldEqual('22253WO-0002')
        'Lots.1.Quantity'.shouldEqual('40')
        'Lots.2.Number'.shouldEqual('22253WO-0003')
        'Lots.2.Quantity'.shouldEqual('50')
        'Lots.3.Number'.shouldEqual('22253WO-0004')
        'Lots.3.Quantity'.shouldEqual('100')
        'Lots.3.Edit'.click()
          'Quantity'.enter('35')
          'OK'.click()
        'Lots'.shouldHaveCount(5)
        'Lots.3.Number'.shouldEqual('22253WO-0004')
        'Lots.3.Quantity'.shouldEqual('35')
        'Lots.4.Number'.shouldEqual('22253WO-0005')
        'Lots.4.Quantity'.shouldEqual('65')
        'OK'.click()
      'Expiry Date'.enter('02/01/2023')
      'FG Lots'.click()
        'Lots'.shouldHaveCount(5)
        'Lots.0.Expiry Date'.shouldEqual('Jan 2 2023')
        'OK'.click()
      'Received Date'.enter('01/01/2023')
      'Expiry Date'.shouldEqual('31/01/2023')
      'FG Lots'.click()
        'Lots'.shouldHaveCount(5)
        'Lots.0.Expiry Date'.shouldEqual('Jan 31 2023')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'Quantity'.enter('50')
      'Designator'.enter('RB')
      'Lot Julian Date'.enter('22253')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('22253RB-0001')
      'Lots.0.Quantity'.shouldEqual('50')
      'Lots.0.Edit'.click()
        'Quantity'.enter('10')
        'OK'.click()
      'Lots'.shouldHaveCount(2)
      'Lots.0.Number'.shouldEqual('22253RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.1.Number'.shouldEqual('22253RB-0002')
      'Lots.1.Quantity'.shouldEqual('40')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Prompt to Produce Labels when Stock Received'.enter('Yes')
  'OK'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Received Date'.enter('1/12/2023')
    'Lines.0.Edit'.click()
      'Designator'.enter('RB')
      'Lot Julian Date'.enter('22254')
      'Received'.shouldEqual('50')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('50')
      'Lots.0.Edit'.click()
        'Expiry Date'.shouldEqual('31/12/2023')
        'Quantity'.enter('10')
        'OK'.click()
      'Lots'.shouldHaveCount(2)
      'Lots.0.Number'.shouldEqual('22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.1.Number'.shouldEqual('22254RB-0002')
      'Lots.1.Quantity'.shouldEqual('40')
      'Received'.enter('100')
      'Lots'.shouldHaveCount(3)
      'Lots.2.Number'.shouldEqual('22254RB-0003')
      'Lots.2.Quantity'.shouldEqual('50')
      'Lots.2.Edit'.click()
        'Quantity'.enter('35')
        'OK'.click()
      'Lots'.shouldHaveCount(4)
      'Lots.2.Number'.shouldEqual('22254RB-0003')
      'Lots.2.Quantity'.shouldEqual('35')
      'Lots.3.Number'.shouldEqual('22254RB-0004')
      'Lots.3.Quantity'.shouldEqual('15')
      'OK'.click()
    'OK'.click()
    'messageDialogText'.shouldContain("Do you want to produce labels?", 'doc')
    'Yes'.click('doc')
    'Labels'.shouldBeCurrentPage()
    'Label Type'.shouldEqual('Inventory')
    'Source Type'.shouldEqual('Purchase Order Receipt')
    'Source Reference'.shouldContain('PO')
    'Download Labels PDF'.click()
    'Back'.click()
  'Receive Purchases'.shouldBeCurrentPage()
  'Back'.click()
'stocktend_settings'.click()
  'Prompt to Produce Labels when Stock Received'.enter('No')
  'OK'.click()
'stocktend_receivePurchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Received'.enter('200')
        'Lots'.shouldHaveCount(5)
        'Lots.4.Quantity'.shouldEqual('100')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'AutoLotsPO'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Designators'.click()
    'Add'.click()
      'Description'.enter('RB')
      'Prefix with Supplier Code'.enter('Yes')
      'Suffix'.enter('RB')
      'Add another'.click()
      'Description'.enter('RF')
      'Prefix with Supplier Code'.enter('Yes')
      'Suffix'.enter('RF')
      'OK'.click()
    'Back'.click()
  'OK'.click()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter("Castaways Inc")
    'Supplier Code'.enter('CAST')
    'OK'.click()
    'helper'.checkNoDuplicateKeys()
  'Add'.click()
    'Name'.enter("Bombast Corporation")
    'Supplier Code'.enter('BOMB')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Quantity Per Lot'.enter('10')
    'OK'.click()
  'mainTable./Hoodie (H01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Quantity Per Lot'.enter('20')
    'OK'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00001')
    'Supplier'.enter('Castaways Inc')
    'Add Line'.click()
      'Designator'.shouldntExist()
      'Product'.enter('Brag Set (BS01)')
      'Quantity'.enter('90')
      'Lots'.shouldHaveCount(1)
      'Lot Julian Date'.shouldntExist()
      'Designator'.clickDropdown()
      'Designator'.shouldHaveNOptions(3) // including blank
      'Designator'.enter('RB')
      'Lot Julian Date'.shouldEqualExpression('global.todayJulian()')
      'Lot Julian Date'.enter('22253')
      'Lots'.shouldHaveCount(9)
      'Lots.0.Number'.shouldEqual('CAST-22253RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.8.Number'.shouldEqual('CAST-22253RB-0009')
      'Lots.8.Quantity'.shouldEqual('10')
      'Lot Julian Date'.enter('22254')
      'Lots'.shouldHaveCount(9)
      'Lots.0.Number'.shouldEqual('CAST-22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.8.Number'.shouldEqual('CAST-22254RB-0009')
      'Lots.8.Quantity'.shouldEqual('10')
      'Quantity'.enter('75')
      'Lots'.shouldHaveCount(8)
      'Lots.0.Number'.shouldEqual('CAST-22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.7.Number'.shouldEqual('CAST-22254RB-0008')
      'Lots.7.Quantity'.shouldEqual('5')
      'Designator'.enter('RF')
      'Lots'.shouldHaveCount(8)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.7.Number'.shouldEqual('CAST-22254RF-0008')
      'Lots.7.Quantity'.shouldEqual('5')
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'Designator'.enter('RF')
      'Quantity'.enter('1')
      'Lot Julian Date'.enter('22254')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0009')
      'Lots.0.Quantity'.shouldEqual('1')
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Hoodie (H01)')
      'Quantity'.enter('100')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable.0.Quantity on POs'.shouldEqual('76')
    'mainTable.0.Quantity On Hand'.shouldEqual('0')
    'mainTable./CAST-22254RF-0008/.Quantity on POs'.shouldEqual('5')
    'Back'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Lines'.shouldHaveCount(3)
    'Lines.0.Edit'.click()
      'Received'.shouldEqual('75')
      'Lots.7.Number'.shouldEqual('CAST-22254RF-0008')
      'Lots.7.Quantity'.shouldEqual('5')
      'Received'.enter('10')
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable.0.Quantity on POs'.shouldEqual('65')
    'mainTable.0.Quantity On Hand'.shouldEqual('11')
    'mainTable./CAST-22254RF-0001/.Quantity on POs'.shouldEqual('0')
    'mainTable./CAST-22254RF-0008/.Quantity on POs'.shouldEqual('5')
    'Back'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable.0.Quantity on POs'.shouldEqual('76')
    'mainTable.0.Quantity On Hand'.shouldEqual('0')
    'mainTable./CAST-22254RF-0001/.Quantity on POs'.shouldEqual('10')
    'mainTable./CAST-22254RF-0008/.Quantity on POs'.shouldEqual('5')
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Start PO Receipts As Zero'.enter('Yes')
  'OK'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Lines'.shouldHaveCount(3)
    'Lines.0.Edit'.click()
      'Received'.shouldEqual('0')
      'Received'.enter('10')
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots.1.Trash'.click()
      'Lots.1.Really Trash?'.click()
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable.0.Quantity on POs'.shouldEqual('66')
    'mainTable.0.Quantity On Hand'.shouldEqual('10')
    'mainTable./CAST-22254RF-0001/.Quantity on POs'.shouldEqual('0')
    'mainTable./CAST-22254RF-0008/.Quantity on POs'.shouldEqual('5')
    'Back'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Lines'.shouldHaveCount(3)
    'Lines.0.Edit'.click()
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0002')
      'Designator'.shouldEqual('RF')
      'Product'.shouldEqual('Brag Set (BS01)')
      'Lot Julian Date'.shouldEqual('22254')
      'Expiry Date'.shouldEqual('')
      'Expiry Date'.enter('31/12/2088')
      'Designator'.clickDropdown()
      'Designator'.shouldHaveNOptions(3) // including blank
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0002')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.0.Expiry Date'.shouldEqual('Dec 31 2088')
      'Received'.enter('65')
      'Designator'.enter('RB')
      'Lots'.shouldHaveCount(7)
      'Lots.0.Number'.shouldEqual('CAST-22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.6.Number'.shouldEqual('CAST-22254RB-0007')
      'Lots.6.Quantity'.shouldEqual('5')
      'Received'.enter('54')
      'Lots'.shouldHaveCount(6)
      'Lots.0.Number'.shouldEqual('CAST-22254RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.5.Number'.shouldEqual('CAST-22254RB-0006')
      'Lots.5.Quantity'.shouldEqual('4')
      'Lot Julian Date'.enter('22253')
      'Lots'.shouldHaveCount(6)
      'Lots.0.Number'.shouldEqual('CAST-22253RB-0001')
      'Lots.0.Quantity'.shouldEqual('10')
      'Lots.5.Number'.shouldEqual('CAST-22253RB-0006')
      'Lots.5.Quantity'.shouldEqual('4')
      'Received'.enter('65')
      'OK'.click()
    'Lines.1.Edit'.click()
      'Designator'.shouldEqual('RF')
      'Received'.enter('1')
      'Lot Julian Date'.shouldEqual('22254')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0009')
      'OK'.click()
    'Lines.2.Edit'.click()
      'Designator'.shouldEqual('')
      'Designator'.enter('RF')
      'Received'.enter('10')
      'Lot Julian Date'.enter('22254')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CAST-22254RF-0010')
      'Received'.enter('100')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable.0.Quantity on POs'.shouldEqual('0')
    'mainTable.0.Quantity On Hand'.shouldEqual('76')
    'mainTable./CAST-22254RF-0001/.Quantity on POs'.shouldEqual('0')
    'mainTable./CAST-22254RF-0001/.Quantity On Hand'.shouldEqual('10')
    'Back'.click()
  'Back'.click()
'AdjAuto'.chapter()
'helper'.trashAll('*')
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Designators'.click()
    'Add'.click()
      'Description'.enter('RB')
      'Suffix'.enter('RB')
      'OK'.click()
    'Back'.click()
  'Default Adjustment Lot Designator'.enter('RB')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Brag Set (BS01)/.Adjust Qty'.click()
    'Product'.enter('Brag Set (BS01)')
    'Quantity'.enter('50')
    'Designator'.shouldEqual('RB')
    'Lot Julian Date'.enter('22253')
    'Lots'.shouldHaveCount(1)
    'Lots.0.Number'.shouldEqual('22253RB-0001')
    'Lots.0.Quantity'.shouldEqual('50')
    'Lots.0.Edit'.click()
      'Quantity'.enter('10')
      'OK'.click()
    'Lots'.shouldHaveCount(2)
    'Lots.0.Number'.shouldEqual('22253RB-0001')
    'Lots.0.Quantity'.shouldEqual('10')
    'Lots.1.Number'.shouldEqual('22253RB-0002')
    'Lots.1.Quantity'.shouldEqual('40')
    'OK'.click()
  'Back'.click()
