'packLots'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Split WC Orders to Match Shipments'.enter('Yes')
  'Log Changes To Stock For Problem Diagnosis'.enter('Yes')
  'OK'.click()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-on-hold', company: 'Centrelink 1', customer: 'Johnny Appleseed'});
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'stocktend_inventory'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
    'mainTable./TOTAL/.Quantity on Hand'.shouldEqual('-100')
    'Back'.click()
  'mainTable./Big Bag (BB01)/.Quantity on Hand'.shouldEqual('-100')
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('250')
    'Add Lot'.click()
      'Lot Number'.enter('BBLOT-NEW')
      'Quantity'.enter('80')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(1000)')
      'Add another'.click()
      'Lot Number'.enter('BBLOT-OLD')
      'Quantity'.enter('80')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(1)')
      'Add another'.click()
      'Lot Number'.enter('BBLOT-MED')
      'Quantity'.enter('80')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(500)')
      'Add another'.click()
      'Lot Number'.enter('BBLOT-EMPTY')
      'Quantity'.enter('10')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(500)')
      'OK'.click()
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./BBLOT-NEW/.Expiry Date'.shouldntEqual('')
      'Back'.click()
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('-10')
    'Add Lot'.click()
      'Lot Number'.enter('BBLOT-EMPTY')
      'Quantity'.enter('-10')
      'OK'.click()
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Quantity on Hand'.shouldEqual('140')
  'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
    'mainTable./TOTAL/.Quantity on Hand'.shouldEqual('140')
    'mainTable./BBLOT-NEW/.Quantity on Hand'.shouldEqual('80')
    'Back'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity'.enter('90')
    'Add Lot'.click()
      'Lot Number'.enter('CLOT')
      'Quantity'.enter('90')
      'Expiry Date'.enter('1/1/2022')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Fulfillment'.click()
  'Packing Lists'.click()
  'Select All'.click()
  'Download Packing Lists PDF'.click()
  'mainTable'.shouldHaveCount(1)
  'stocktend_inventory'.click()
    'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
      'mainTable./BBLOT-OLD/.Quantity on Hand'.shouldEqual('0')
      'mainTable./BBLOT-MED/.Quantity on Hand'.shouldEqual('60')
      'mainTable./BBLOT-NEW/.Quantity on Hand'.shouldEqual('80')
      'Back'.click()
    'Back'.click()
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Quantity to Pack'.shouldEqual('100')
    'Lines./Cap (C01)/.Quantity to Pack'.shouldEqual('90')
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots'.shouldHaveCount(2)
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('80')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('20')
      'Add Lot'.click()
        'Lot Number'.clickDropdown()
        'Lot Number'.optionShouldContain(1, 'BBLOT-MED 60 ')
        'Lot Number'.optionShouldContain(2, 'BBLOT-NEW 80 ')
        'Lot Number'.optionShouldContain(3, 'BBLOT-OLD 0 ')
        'Lot Number'.chooseOption('BBLOT-NEW')
        'Lot Number'.shouldEqual('BBLOT-NEW')
        'Quantity'.enter('10')
        'OK'.click()
      'Lots.1.Edit'.click()
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Sales Order Fulfillment'.shouldBeCurrentPage()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots'.shouldHaveCount(3)
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('80')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('10')
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('10')
      'OK'.click()
    'OK'.click()
  'Unfulfilled Sales Orders'.shouldBeCurrentPage()
  'mainTable'.shouldHaveCount(1)
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots'.shouldHaveCount(3)
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('80')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('10')
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('10')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.View Serial/Lots'.click()
    'mainTable./TOTAL/.Quantity Sold but not Fulfilled'.shouldEqual('100')
    'mainTable./TOTAL/.Quantity Available to Pick'.shouldEqual('90')
    'Back'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./BBLOT-NEW/.Expiry Date'.shouldntEqual('')
      'Back'.click()
    'Back'.click()
  'mainTable./Big Bag (BB01)/.Quantity on Hand'.shouldEqual('140')
  'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
    'mainTable./TOTAL/.Quantity on Hand'.shouldEqual('140')
    'mainTable./TOTAL/.Quantity Sold but not Fulfilled'.shouldEqual('100')
    'mainTable./TOTAL/.Quantity Available to Pick'.shouldEqual('240')
    'mainTable./BBLOT-OLD/.Quantity on Hand'.shouldEqual('0')
    'mainTable./BBLOT-NEW/.Quantity on Hand'.shouldEqual('70')
    'mainTable./BBLOT-MED/.Quantity on Hand'.shouldEqual('70')
    'mainTable./BBLOT-OLD/.Quantity Sold but not Fulfilled'.shouldEqual('80')
    'mainTable./BBLOT-NEW/.Quantity Sold but not Fulfilled'.shouldEqual('10')
    'mainTable./BBLOT-MED/.Quantity Sold but not Fulfilled'.shouldEqual('10')
    'mainTable./BBLOT-OLD/.Quantity Available to Pick'.shouldEqual('80')
    'mainTable./BBLOT-NEW/.Quantity Available to Pick'.shouldEqual('80')
    'mainTable./BBLOT-MED/.Quantity Available to Pick'.shouldEqual('80')
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable'.shouldHaveCount(1)
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('10')
      'OK'.click()
    'Lines./Cap (C01)/.Quantity to Pack'.shouldEqual('90')
    'Lines./Big Bag (BB01)/.Quantity to Pack'.shouldEqual('100')
    'Lines./Big Bag (BB01)/.Quantity Shipped'.enter('50')
    'OK'.click()
    'stFormRejection'.shouldContain('Big Bag (BB01): Cannot have an Unspecified lot with a negative quantity')
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots./BBLOT-NEW/.Trash'.click()
      'Lots./BBLOT-NEW/.Really Trash?'.click()
      'Lots./BBLOT-MED/.Trash'.click()
      'Lots./BBLOT-MED/.Really Trash?'.click()
      'Lots./BBLOT-OLD/.Edit'.click()
        'Quantity'.enter('50')
        'OK'.click()
      'OK'.click()
    'Lines./Cap (C01)/.Quantity to Pack'.shouldEqual('90')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
    'mainTable./BBLOT-OLD/.Quantity on Hand'.shouldEqual('0')
    'mainTable./BBLOT-OLD/.Quantity Available to Pick'.shouldEqual('80')
    'mainTable./BBLOT-MED/.Quantity on Hand'.shouldEqual('60') // 80, less 20 that has been auto allocated to original order
    'mainTable./BBLOT-MED/.Quantity Sold but not Fulfilled'.shouldEqual('20')
    'mainTable./BBLOT-OLD/.Quantity Available to Pick'.shouldEqual('80')
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'Quantity Available to Pick'.shouldEqual('90')
    'View Lots'.click()
      'mainTable./TOTAL/.Quantity Available to Pick'.shouldEqual('90')
      'Back'.click()
    'OK'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable.0.Edit'.click()
    'Lines./Cap (C01)/.Edit'.click()
      'Lots'.shouldHaveCount(1)
      'Lots.0.Quantity'.shouldEqual('90')
      'Lots.0.Number'.shouldEqual('CLOT')
      'Quantity To Pick'.enter('50')
      'Lots'.shouldHaveCount(1)
      'Lots.0.Number'.shouldEqual('CLOT')
      'Lots.0.Quantity'.shouldEqual('50') // This one is automatically reallotted as it wasn't manually altered
      'OK'.click()
    'Lines./Cap (C01)/.Quantity Shipped'.enter('50')
    'OK'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable'.shouldHaveCount(2)
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Big Bag (BB01)/.Quantity on Hand'.shouldEqual('140')
  'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
    'mainTable./BBLOT-OLD/.Quantity on Hand'.shouldEqual('0')
    'mainTable./BBLOT-NEW/.Expiry Date'.shouldntEqual('')
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable.1.Edit'.click() // This is the shipped order - it should have the lots from the original order
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity Shipped'.shouldEqual('50')
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('50')
      'Lots'.shouldHaveCount(1)
      'OK'.click()
    'OK'.click()
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('50')
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('30')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('20')
      'OK'.click()
    'OK'.click()
  'mainTable.1.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('0')
      'OK'.click()
    'OK'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('70')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable.0.Edit'.click() // Check older order is unaffected
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('50')
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('30')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('20')
      'OK'.click()
    'OK'.click()
  'mainTable.2.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('70')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('60')
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('10')
      'OK'.click()
    'OK'.click()
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('50')
      'Lots./BBLOT-OLD/.Quantity'.shouldEqual('30')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('20')
      'OK'.click()
    'Lines.0.Quantity Shipped'.enter('50')
    'Lines.1.Quantity Shipped'.enter('50')
    'WC Order Status'.enter('Completed')
    'OK'.click() // NOTE: This has the effect of completing both orders, because this one gets added to the single shipment, which unsplits the order
  'mainTable'.shouldHaveCount(1)
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('70')
      'Lots./BBLOT-MED/.Quantity'.shouldEqual('60')
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('10')
      'OK'.click()
    'OK'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('20')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable'.shouldHaveCount(2)
  'mainTable.1.Edit'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('20')
      'Lots./BBLOT-NEW/.Quantity'.shouldEqual('20')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'0'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Status to set WC Order to when Shipment Created'.shouldntExist()
  'Auto-generate Invoice when WC Order Status Becomes'.shouldntExist()
  'Split WC Orders to Match Shipments'.enter('Yes')
  'Status to set WC Order to when Shipment Created'.enter('Processing')
  'Auto-generate Invoice when WC Order Status Becomes'.enter('Completed')
  'Enter Incremental Shipment Quantity'.enter('Yes')
  'OK'.click()
'helper'.setWCStockLevel('Big Bag (BB01)', 500)
'helper'.setWCStockLevel('Cap (C01)', 500)
'helper'.simulateBrowserRefresh()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-on-hold', company: 'Centrelink 1', customer: 'Johnny Appleseed'});
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'Sales and Invoices'.click()
  'mainTable.1.View Order'.click()
    'Total'.shouldEqual('AUD 40,000.00')
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable'.shouldHaveCount(1)
  'mainTable.0.Edit'.click()
    'Lines.0.This Shipment Qty'.enter('50')
    'Lines.1.This Shipment Qty'.enter('60')
    'OK'.click()
  'mainTable'.shouldHaveCount(2)
  'Sales and Invoices'.click()
    'mainTable.1.View Order'.click()
      'Total'.shouldEqual('AUD 22,000.22')
      'Back'.click()
    'mainTable.3.View Order'.click()
      'Total'.shouldEqual('AUD 18,000.18')
      'Back'.click()
    'mainTable.1.Product'.shouldEqual('Big Bag (BB01)');
    'mainTable.1.Amount Ex Tax'.shouldEqual('9,091.00');
    'mainTable.1.Tax'.shouldEqual('909.10');
    'mainTable.2.Quantity'.shouldEqual('40');
    'Back'.click()
  'View Shipments'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable.0.Edit'.click()
      'Labels'.click()
        'Labels'.shouldBeCurrentPage()
        'Label Type'.shouldEqual('Inventory')
        'Source Type'.shouldEqual('Shipment')
        'Purpose'.shouldEqual('Carton')
        'Download Labels PDF'.click()
        'Back'.click()
      'Invoiced'.enter('Yes')
      'OK'.click()
    'mainTable.0.Order'.click()
      'Lines./Big Bag/.Quantity'.shouldEqual('50')
      'Lines./Cap/.Quantity'.shouldEqual('60')
      'Back'.click()
    'Back'.click()
  'mainTable.1.Edit'.click()
    'Full Edit'.click()
      'Lines./Big Bag/.Tax'.shouldEqual('909.10')
      'OK'.click()
    'OK'.click()
  'mainTable.0.Fulfill Stage'.shouldEqual('Waiting')
  'mainTable.0.Edit'.click()
    'Lines./Big Bag (BB01)/.Quantity Ordered'.shouldEqual('50')
    'Lines./Cap (C01)/.Quantity Ordered'.shouldEqual('40')
    'Lines./Big Bag (BB01)/.Quantity Shipped'.shouldEqual('0')
    'Lines./Cap (C01)/.Quantity Shipped'.shouldEqual('0')
    'OK'.click()
  'mainTable.1.Fulfill Stage'.shouldEqual('Shipped')
  'mainTable.1.Edit'.click()
    'Lines./Big Bag (BB01)/.Quantity Ordered'.shouldEqual('50')
    'Lines./Cap (C01)/.Quantity Ordered'.shouldEqual('60')
    'Lines./Big Bag (BB01)/.Quantity Shipped'.shouldEqual('50')
    'Lines./Cap (C01)/.Quantity Shipped'.shouldEqual('60')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(4)
  'mainTable.1.Product'.shouldEqual('Big Bag (BB01)');
  'mainTable.1.Amount Ex Tax'.shouldEqual('9,091.00');
  'mainTable.1.Tax'.shouldEqual('909.10');
  'mainTable.1.Status'.shouldEqual('Processing');
  'mainTable.1.View Order'.click()
    'Total'.shouldEqual('AUD 22,000.22')
    'Back'.click()
  'mainTable.3.View Order'.click()
    'Total'.shouldEqual('AUD 18,000.18')
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable'.shouldHaveCount(2)
  'mainTable.0.Fulfill Stage'.shouldEqual('Waiting')
  'mainTable.0.Edit'.click()
    'Lines.0.This Shipment Qty'.enter('50')
    'Save'.click()
    'Lines.1.This Shipment Qty'.enter('40')
    'OK'.click()
  'mainTable'.shouldHaveCount(2)
  'mainTable.0.Fulfill Stage'.shouldEqual('Shipped')
  'View Shipments'.click()
    'mainTable'.shouldHaveCount(2)
    'mainTable.1.Order'.click()
      'Lines./Big Bag/.Quantity'.shouldEqual('50')
      'Lines./Cap/.Quantity'.shouldEqual('40')
      'Status'.shouldEqual('Processing')
      'Back'.click()
    'mainTable.0.Order'.click()
      'Status'.shouldEqual('Processing')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(4)
  'Back'.click()
'stocktend_customers'.click()
  'mainTable./Johnny Appleseed/.AR Balance'.shouldEqual('-22,000.22')
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable.0.Shipped Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
  'Manage Orders'.click()
    'mainTable.0.Value'.shouldEqual('22,000.22')
    'mainTable.1.Value'.shouldEqual('18,000.18')
    'Back'.click()
  'Back'.click()
'helper'.setWCOrderStatus({differentForeman: true, customer: 'Johnny Appleseed', status: 'Completed'})
'stocktend_customers'.click()
  'mainTable./Johnny Appleseed/.AR Balance'.shouldEqual('-40,000.40')
  'Back'.click()
'Commission'.chapter()
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('Yes')
  'OK'.click()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter("Castaways Inc")
    'Supplier Code'.enter('CA')
    'OK'.click()
  'Add'.click()
    'Name'.enter("Bombast Corporation")
    'Supplier Code'.enter('BO')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
  'Add Supplier'.click()
    'Supplier'.enter('Bombast Corporation')
    'OK'.click()
  'OK'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
  'Add Supplier'.click()
    'Supplier'.enter('Castaways Inc')
    'OK'.click()
  'OK'.click()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-processing', company: 'Ajax', customer: 'Johnny Appleseed', shippingIncTax: 20.00, excludeDefaultCountry: true})
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'Inventory'.click()
  'Refresh'.click()
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('-100')
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('-100')
  'Back'.click()
'Fulfillment'.click()
  'mainTable.0.Edit'.click()
    'Drop Ship'.click()
      'Add Purchase Order'.shouldBeCurrentPage()
      'Lines'.shouldHaveCount(0)
      'Add Sales Order Lines'.click()
        'messageDialogText'.shouldEqual('Please select a Supplier before adding Sales Order lines', 'doc')
        'messageDialogOK'.click('doc')
      'Supplier'.enter('Castaways Inc')
      'Add Sales Order Lines'.click()
      'Lines./Big Bag (BB01)/.Quantity'.shouldEqual('100')
      'Lines./Cap (C01)/.Quantity'.shouldEqual('100')
      'Sales Order'.shouldntEqual('')
      'Sales Order'.shouldBeReadOnly()
      'Deliver To'.shouldEqual('Warehouse of Ajax, 26 Sherwood Rd, Mt Waverley, VIC 3149 AU')
      'Our Contact Details'.shouldEqual('i.am.paul.andrews+3@gmail.com')
      'OK'.click()
    'WC Order Status'.shouldEqual('Completed')
    'Fulfill Stage'.shouldEqual('Shipped')
    'Shipment Method'.shouldEqual('Drop Shipment')
    'OK'.click()
  'Back'.click()
'Inventory'.click()
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'helper'.clearWCOrders()
'Sales and Invoices'.click()
  'Sales Agents'.click()
    'Commission Deductions'.click()
      'Add'.click()
        'Add Deduction'.shouldBeCurrentPage()
        'Customer IDs (comma-separated)'.enter('8,9,999')
        'Product SKUs (comma-separated)'.enter('C01,BB01,XXXXX')
        'Product Supplier Codes (comma-separated)'.enter('CA,BO,YYYYY')
        'OK'.click()
        'stFormRejection'.shouldContain('Invalid Customer: 999')
        'Customer IDs (comma-separated)'.enter('8,9')
        'OK'.click()
        'stFormRejection'.shouldContain('Invalid Product SKU: XXXXX')
        'Product SKUs (comma-separated)'.enter('C01,BB01')
        'OK'.click()
        'stFormRejection'.shouldContain('Invalid Supplier: YYYYY')
        'Product Supplier Codes (comma-separated)'.enter('CA,BO')
        'OK'.click()
        'stFormRejection'.shouldContain('Please enter a valid Deduction %')
        'Deduction %'.enter('1.2')
        'OK'.click()
      'mainTable'.shouldHaveCount(1)
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.clearWCStockLevels()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'Sales Agents'.click()
    'Sales Agents'.shouldBeCurrentPage()
    'Add'.click()
      'Add Sales Agent'.shouldBeCurrentPage()
      'Name'.enter('Jiminy Baseball')
      'WooCommerce Username'.enter('pleb')
      'Commission %'.enter('12.5')
      'Add another'.click()
      'Name'.enter('Peter Saucepan')
      'WooCommerce Username'.enter('pleb2')
      'Commission %'.enter('20')
      'OK'.click()
    'mainTable'.shouldHaveCount(2)
    'Commission Deductions'.click()
      'mainTable.0.Edit'.click()
        'Agent WC Usernames (comma-separated)'.enter('pleb,pleb2,elvis')
        'OK'.click()
        'stFormRejection'.shouldContain('Invalid Agent: elvis')
        'Agent WC Usernames (comma-separated)'.enter('pleb,pleb2')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_customers'.click()
  'Sales Agents'.click()
    'mainTable'.shouldHaveCount(2)
    'Back'.click()
  'mainTable./Johnny Appleseed/.Edit'.click()
    'Agents'.shouldHaveCount(0)
    'Add Agent'.click()
      'Add Agent for Customer Johnny Appleseed'.shouldBeCurrentPage()
      'Agent'.clickDropdown()
      'Agent'.shouldHaveOption('Jiminy Baseball')
      'Agent'.chooseOption('Peter Saucepan')
      'OK'.click()
    'Agents'.shouldHaveCount(1)
    'Agents.0.Agent'.shouldEqual('Peter Saucepan')
    'Agents.0.Trash'.click()
    'Agents.0.Really Trash?'.click()
    'Add Agent'.click()
      'Agent'.chooseOption('Peter Saucepan')
      'OK'.click()
    'Back'.click()
  'mainTable./Kevin Costly/.Edit'.click()
    'Agents'.shouldHaveCount(0)
    'Add Agent'.click()
      'Agent'.enter('Jiminy Baseball')
      'Add another'.click()
      'Agent'.enter('Peter Saucepan')
      'OK'.click()
    'Agents'.shouldHaveCount(2)
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO-GEN-01')
    'Expected Delivery Date'.enter('3/10/2021')
    'Add Line'.click()
      'Product'.enter('Big Bag (BB01)')
      'Quantity'.enter('40')
    'Add another line'.click()
      'Product'.enter('Cap (C01)')
      'Quantity'.enter('40')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable./PO-GEN-01/.Enter Receipt'.click()
    'Lines./Big Bag (BB01)/.Received'.enter('30')
    'Lines./Cap (C01)/.Received'.enter('30')
    'OK'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-processing', company: 'Ajax', customer: 'Johnny Appleseed', shippingIncTax: 20.00})
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(2)
  'mainTable.0.View Order'.click()
    'Commission'.click()
      'Pieces'.shouldHaveCount(1)
      'Add Agent'.click()
        'Agent'.enter('Jiminy Baseball')
        'OK'.click()
      'Pieces'.shouldHaveCount(2)
      'Pieces./Jiminy Baseball/.Trash'.click()
      'Pieces./Jiminy Baseball/.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-processing', company: 'Boral', customer: 'Kevin Costly', shippingIncTax: 20.00})
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(4)
  'mainTable./Boral/.View Order'.click()
    'Commission'.click()
      'Pieces'.shouldHaveCount(2)
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Big Bag (BB01)', quantity: 100, unitPrice: 200, orderDate: global.todayLocal(), status: 'wc-processing', company: 'Centrelink', shippingIncTax: 20.00})
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100, unitPrice: 200})
'stocktend_fulfillment'.click()
  'mainTable'.shouldHaveCount(3)
  'Allocate'.click()
    'Allocate Inventory to Sales Orders'.shouldBeCurrentPage()
    'mainTable'.shouldHaveCount(2)
    'mainTable./Big Bag (BB01)/.Quantity Pickable'.shouldEqual('30')
    'mainTable./Big Bag (BB01)/.Quantity Incoming'.shouldEqual('10')
    'mainTable./Big Bag (BB01)/.Incoming ETA'.shouldEqual('Oct 3 2021')
    'mainTable./Big Bag (BB01)/.On Sales Orders'.shouldEqual('300')
    'mainTable./Big Bag (BB01)/.Allocated %'.shouldEqual('0.00')
    'mainTable./Cap (C01)/.Quantity Pickable'.shouldEqual('30')
    'mainTable./Cap (C01)/.Quantity Incoming'.shouldEqual('10')
    'mainTable./Cap (C01)/.Incoming ETA'.shouldEqual('Oct 3 2021')
    'mainTable./Cap (C01)/.On Sales Orders'.shouldEqual('300')
    'mainTable./Cap (C01)/.Allocated %'.shouldEqual('0.00')
    'mainTable./Big Bag (BB01)/.Allocate'.click()
      'Edit Allocation'.shouldBeCurrentPage()
      'Product'.shouldEqual('Big Bag (BB01)')
      'Lines'.shouldHaveCount(4) // Including total
      'Lines./Warehouse of Ajax/.Order Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
      'Lines./Warehouse of Ajax/.Sales Order Price'.shouldEqual('200.00')
      'Lines./Warehouse of Ajax/.Remaining to Ship'.shouldEqual('100')
      'Lines./Warehouse of Ajax/.Allocate %'.shouldEqual('0.00')
      'Lines./Warehouse of Boral/.Order Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
      'Lines./Warehouse of Boral/.Sales Order Price'.shouldEqual('200.00')
      'Lines./Warehouse of Boral/.Remaining to Ship'.shouldEqual('100')
      'Lines./Warehouse of Boral/.Allocate %'.shouldEqual('0.00')
      'Lines./Warehouse of Centrelink/.Order Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
      'Lines./Warehouse of Centrelink/.Sales Order Price'.shouldEqual('200.00')
      'Lines./Warehouse of Centrelink/.Remaining to Ship'.shouldEqual('100')
      'Lines./Warehouse of Centrelink/.Allocate %'.shouldEqual('0.00')
      'Lines./Warehouse of Ajax/.Allocate %'.enter('60')
      'Lines./Warehouse of Boral/.Allocate %'.enter('40')
      'OK'.click()
    'mainTable./Big Bag (BB01)/.Allocated %'.shouldEqual('100.00')
    'mainTable./Cap (C01)/.Allocate'.click()
      'Lines./Warehouse of Ajax/.Allocate %'.enter('50')
      'Lines./Warehouse of Boral/.Allocate %'.enter('30')
      'OK'.click()
    'mainTable./Cap (C01)/.Allocated %'.shouldEqual('80.00')
    'mainTable./Cap (C01)/.Allocate'.click()
      'Lines./Warehouse of Centrelink/.Allocate %'.enter('20')
      'OK'.click()
    'mainTable./Cap (C01)/.Allocated %'.shouldEqual('100.00')
    'Back'.click()
  'mainTable'.shouldHaveCount(3)
  'mainTable./Warehouse of Ajax/.Packable'.shouldEqual('Partially')
  'mainTable./Warehouse of Boral/.Packable'.shouldEqual('Partially')
  'mainTable./Warehouse of Centrelink/.Packable'.shouldEqual('Partially')
  'mainTable./Warehouse of Ajax/.Edit'.click()
    'Lines./Big Bag (BB01)/.Packable'.shouldEqual('Partially')
    'Lines./Big Bag (BB01)/.Quantity To Pack'.shouldEqual('18')
    'Lines./Big Bag (BB01)/.Quantity Shipped'.enter('18')
    'Lines./Cap (C01)/.Packable'.shouldEqual('Partially')
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('15')
    'Lines./Cap (C01)/.Quantity Shipped'.enter('15')
    'OK'.click()
  'mainTable./Warehouse of Boral/.Edit'.click()
    'Lines./Big Bag (BB01)/.Packable'.shouldEqual('Partially')
    'Lines./Big Bag (BB01)/.Quantity To Pack'.shouldEqual('12')
    'Lines./Big Bag (BB01)/.Quantity Shipped'.enter('12')
    'Lines./Cap (C01)/.Packable'.shouldEqual('Partially')
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('9')
    'Lines./Cap (C01)/.Quantity Shipped'.enter('9')
    'OK'.click()
  'mainTable./Warehouse of Centrelink/.Edit'.click()
    'Lines./Big Bag (BB01)/.Packable'.shouldEqual('No')
    'Lines./Big Bag (BB01)/.Quantity To Pack'.shouldEqual('0')
    'Lines./Cap (C01)/.Packable'.shouldEqual('Partially')
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('6')
    'Lines./Cap (C01)/.Quantity Shipped'.enter('5')
    'OK'.click()
  'Allocate'.click()
    'mainTable'.shouldHaveCount(2)
    'mainTable./Cap (C01)/.Allocate'.click()
      'Product'.shouldEqual('Cap (C01)')
      'Lines'.shouldHaveCount(4) // Including total
      'Lines./Warehouse of Boral/.Allocate %'.enter(0)
      'Lines./Warehouse of Ajax/.Allocate %'.enter(0)
      'Lines./Warehouse of Centrelink/.Allocate %'.enter(100)
      'OK'.click()
    'Back'.click()
  'mainTable./Warehouse of Centrelink/.Edit'.click()
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('1')
    'Lines./Cap (C01)/.Quantity Shipped'.enter('6')
    'OK'.click()
  'Allocate'.click()
    'mainTable'.shouldHaveCount(2)
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Calculate Commission From'.enter('Shipments')
  'OK'.click()
'Sales and Invoices'.click()
  'Sales Agents'.click()
    'Commission Deductions'.click()
      'mainTable.0.Edit'.click()
        'Active'.enter('No')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Commission Report'.click()
    'Commission Based on Shipments'.shouldBeCurrentPage()
    'Agent'.enter('Jiminy Baseball')
    'Go'.click()
    'mainTable./Cap (C01)/.Sold Price'.shouldEqual('181.82')
    'mainTable./Cap (C01)/.Commission'.shouldEqual('204.55')
    'Back'.click()
  'Sales Agents'.click()
    'Commission Deductions'.click()
      'mainTable.0.Edit'.click()
        'Active'.enter('Yes')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Commission Report'.click()
    'Agent'.enter('Jiminy Baseball')
    'Go'.click()
    'mainTable./Cap (C01)/.Sold Price'.shouldEqual('179.64')
    'mainTable./Cap (C01)/.Commission'.shouldEqual('202.09')
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Calculate Commission From'.shouldEqual('Shipments')
  'Calculate Commission From'.enter('Orders')
  'OK'.click()
'Sales and Invoices'.click()
  'searcher'.enter('cap')
  'mainTable.0.Edit'.click()
    'Lines./Big Bag/.Quantity'.enter('0')
    'Lines./Cap/.Quantity'.enter('6')
    'Status'.enter('Completed')
    'OK'.click()
  'mainTable.1.Edit'.click()
    'Lines./Big Bag/.Quantity'.enter('12')
    'Lines./Cap/.Quantity'.enter('9')
    'Status'.enter('Completed')
    'OK'.click()
  'mainTable.2.Edit'.click()
    'Lines./Big Bag/.Quantity'.enter('18')
    'Lines./Cap/.Quantity'.enter('15')
    'Status'.enter('Completed')
    'OK'.click()
  'Commission Report'.click()
    'Commission Based on Orders'.shouldBeCurrentPage()
    'Agent'.enter('Jiminy Baseball')
    'Go'.click()
    'mainTable./Cap (C01)/.Sold Price'.shouldEqual('179.64')
    'mainTable./Cap (C01)/.Commission'.shouldEqual('202.09')
    'Back'.click()
  'Back'.click()
'1'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('Yes')
  'OK'.click()
'stocktend_fulfillment'.click()
  'View Shipments'.click()
    'Transport Settings'.click()
      'Carriers'.click()
        'Carriers'.shouldBeCurrentPage()
        'Add'.click()
          'Add Carrier'.shouldBeCurrentPage()
          'Carrier Name'.enter('Acme')
          'Add another'.click()
          'Carrier Name'.enter('ABC Trucking')
          'OK'.click()
        'Back'.click()
      'Trailers'.click()
        'Trailers'.shouldBeCurrentPage()
        'Add'.click()
          'Add Trailer'.shouldBeCurrentPage()
          'Trailer License Plate'.enter('TDOUGIE')
          'Add another'.click()
          'Trailer License Plate'.enter('TBOBBIE')
          'OK'.click()
        'Back'.click()
      'Trucks'.click()
        'Trucks'.shouldBeCurrentPage()
        'Add'.click()
          'Add Truck'.shouldBeCurrentPage()
          'Truck License Plate'.enter('DOUGIE')
          'Default Trailer License Plate'.enter('TDOUGIE')
          'Carrier'.enter('Acme')
          'Add another'.click()
          'Truck License Plate'.enter('BOBBIE')
          'Default Trailer License Plate'.enter('TBOBBIE')
          'Carrier'.enter('ABC Trucking')
          'OK'.click()
        'Back'.click()
      'Drivers'.click()
        'Drivers'.shouldBeCurrentPage()
        'Add'.click()
          'Add Driver'.shouldBeCurrentPage()
          'Driver Name'.enter('Bob Grenshen')
          'Driver License'.enter('897-985-715')
          'Default Truck'.enter('BOBBIE')
          'Add another'.click()
          'Driver Name'.enter('Doug Underwood')
          'Driver License'.enter('7876-908-90')
          'Default Truck'.enter('DOUGIE')
          'OK'.click()
        'Back'.click()
      'Company Name'.enter('Candelabra Orchards, Inc.')
      'Address 1'.enter('9680 State Route 999 N.')
      'Address 2'.enter('PO Box 999')
      'City/Suburb/Town'.enter('Alto Pas')
      'State/Province'.enter('IL')
      'Postal/Zip Code'.enter('62905')
      'Phone'.enter('618-999-9876')
      'Fax'.enter('618-999-9877')
      'Default Loaded At'.enter('Alto Pas, IL.')
      'Contact Name'.enter('Wayne Reynolds')
      'Contact Email'.enter('wayne@candelabraorchards.com')
      'Web Site'.enter('www.candelabraorchards.com')
      'Bill of Lading Message'.enter('We appreciate your business.  Thank you for supporting family farming! Wayne Reynolds 987-123-1987')
      'Pallet Charge Message'.enter('$6.00 Pallet Charge If No Exchange.')
      'Default Deliver By'.enter('Truck')
      'Default Driver'.clickDropdown()
      'Default Driver'.shouldHaveNOptions(3) // including blank
      'Default Driver'.enter('Bob Grenshen')
      'Default Truck License Plate'.shouldEqual('BOBBIE')
      'Default Carrier'.shouldEqual('ABC Trucking')
      'Default Carrier'.clickDropdown()
      'Default Carrier'.shouldHaveNOptions(3) // including blank
      'Default Carrier'.enter('Acme')
      'Default Driver License'.shouldEqual('897-985-715')
      'Default Driver'.enter('Bob Grenshen II')
      'Default Terms'.enter('FOB')
      'Default Truck License Plate'.enter('BGH198')
      'Default Trailer License Plate'.enter('TRU965')
      'BOL PDF Logo URL'.enter('http://localhost/wp-content/uploads/Picture1.jpg')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_locations'.click()
  'Add'.click()
    'Name'.enter('Sydney')
    'OK'.click()
  'Add'.click()
    'Name'.enter('Melbourne')
    'OK'.click()
'stocktend_inventory'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Adjust Qty'.click()
    'lots'.shouldntExist()
    'Back'.click()
  'mainTable./Corn Flakes (CF01)/.Adjust Qty'.click()
    'lots'.shouldntExist()
    'Back'.click()
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'Serial/Lot Tracking'.shouldEqual('None')
    'Track Expiry Dates'.shouldntExist()
    'Serial/Lot Tracking'.clickDropdown()
    'Serial/Lot Tracking'.shouldHaveOption('Serial')
    'Serial/Lot Tracking'.shouldHaveOption('Lot')
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.shouldEqual('No')
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Serial')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Lemon (LE01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('18')
    'lots./Unspecified/.Quantity'.shouldEqual('18')
    'Add Serial Number'.shouldntExist()
    'Add Lot'.click()
      'Lot Number'.enter('LE01-MEL-01')
      'Quantity'.enter('17')
      'Expiry Date'.shouldntExist()
      'OK'.click()
    'lots./LE01-MEL-01/.Quantity'.shouldEqual('17')
    'lots./Unspecified/.Quantity'.shouldEqual('1')
    'OK'.click()
  'mainTable./Lemon (LE01)/.Quantity On Hand'.shouldEqual('18')
  'searcher'.enter('')
  'mainTable./Cap (C01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Hoodie (H01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('None')
    'OK'.click()
    'stFormRejection'.shouldContain('This product has lot/serial numbers - cannot turn off lot tracking')
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Lemon (LE01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('12')
    'lots./Unspecified/.Quantity'.shouldEqual('12')
    'Add Serial Number'.shouldntExist()
    'Add Lot'.click()
      'Lot Number'.enter('LE01-MEL-02')
      'Quantity'.enter('12')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
      'OK'.click()
    'lots./LE01-MEL-02/.Quantity'.shouldEqual('12')
    'lots./LE01-MEL-02/.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(365).toLocalMMMDY()')
    'lots./LE01-MEL-02/.Edit'.click()
      'Expiry Date'.enterExpression('global.todayLocal().incDays(188)')
      'OK'.click()
    'lots./LE01-MEL-02/.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(188).toLocalMMMDY()')
    'OK'.click()
  'mainTable./Lemon (LE01)/.Quantity On Hand'.shouldEqual('30')
  'mainTable./Corn Flakes (CF01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('4')
    'lots./Unspecified/.Quantity'.shouldEqual('4')
    'Add Lot'.shouldntExist()
    'Add Serial Number'.click()
      'Serial Number'.enter('CF01-MEL-01')
      'Quantity'.shouldntExist()
      'Expiry Date'.enterExpression('global.todayLocal().incDays(183)')
      'Add another'.click()
      'Serial Number'.enter('CF01-MEL-01')
      'Expiry Date'.enterExpression('global.todayLocal().incDays(183)')
      'OK'.click()
      'stFormRejection'.shouldContain('You cannot specify the same serial number twice on the same adjustment')
      'Serial Number'.enter('CF01-MEL-02')
      'OK'.click()
    'lots./CF01-MEL-01/.Quantity'.shouldEqual('1')
    'lots./CF01-MEL-02/.Quantity'.shouldEqual('1')
    'lots./Unspecified/.Quantity'.shouldEqual('2')
    'OK'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Quantity On Hand'.shouldEqual('30')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./LE01-MEL-01/.Quantity On Hand'.shouldEqual('17')
      'mainTable./LE01-MEL-01/.Location'.shouldEqual('Melbourne')
      'mainTable./LE01-MEL-02/.Quantity On Hand'.shouldEqual('12')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('1')
      'mainTable./LE01-MEL-02/.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(188).toLocalMMMDY()')
      'Back'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'mainTable./CF01-MEL-01/.Quantity On Hand'.shouldEqual('1')
      'mainTable./CF01-MEL-02/.Quantity On Hand'.shouldEqual('1')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('2')
      'Back'.click()
    'OK'.click()
  'helper'.addWCOrder({differentForeman: true, company: 'Ajax', customer: 'Johnny Appleseed', product: 'Lemon (LE01)', quantity: 3, orderDate: global.todayLocal(), status: 'wc-processing', shippingIncTax: 20.00})
  'helper'.addWCOrder({differentForeman: true, company: 'Centrelink', customer: 'Kevin Costly', product: 'Corn Flakes (CF01)', quantity: 3, orderDate: global.todayLocal(), status: 'wc-processing', shippingIncTax: 20.00})
  'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 100})
  'helper'.addWCOrderItem({product: 'Hoodie (H01)', quantity: 100})
  'helper'.addWCOrderItem({product: 'Little Bag (LB01)', quantity: 100})
  'Refresh'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Quantity On Hand'.shouldEqual('27')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'searcher'.enter('General')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('-3')
      'Back'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'searcher'.enter('General')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('-3')
      'Back'.click()
    'OK'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'mainTable.0.Edit'.click()
    'Ship From Location'.enter('Melbourne')
    'lines.0.Product'.shouldEqual('Lemon (LE01)')
    'lines.0.Quantity To Pack'.shouldEqual('3')
    'lines.0.Edit'.click()
      'Sales Order'.shouldntEqual('')
      'Quantity to Pick'.shouldEqual('3')
      'Quantity Shipped'.shouldEqual('0')
      'Quantity to Pick'.enter('2')
      'lots'.shouldHaveCount(1)
      'Quantity Shipped'.enter('2')
      'lots'.shouldHaveCount(1)
      'lots.0.Number'.shouldEqual('LE01-MEL-01')
      'lots.0.Edit'.click()
        'Quantity'.enter('1')
        'OK'.click()
      'lots'.shouldHaveCount(2)
      'lots.1.Number'.shouldEqual('Unspecified')
      'Add Lot'.click()
        'Lot Number'.enter('LE01-MEL-02')
        'Quantity'.enter('1')
        'OK'.click()
      'lots'.shouldHaveCount(2)
      'OK'.click()
    'WC Order Status'.enter('Completed')
    'OK'.click()
    'stFormRejection'.shouldContain('Quantity Shipped must equal Quantity Ordered before you can set the order to Completed')
    'lines.0.Edit'.click()
      'Quantity to Pick'.enter('3')
      'Quantity Shipped'.enter('3')
      'OK'.click()
    'OK'.click()
  'stFormRejection'.shouldntExist()
  'mainTable.0.Edit'.click() // above one is now gone as it was set to completed
    'Ship From Location'.enter('Melbourne')
    'lines./Corn Flakes (CF01)/.Quantity To Pack'.shouldEqual('3')
    'lines./Corn Flakes (CF01)/.Edit'.click()
      'Quantity to Pick'.shouldEqual('3')
      'Quantity Shipped'.shouldEqual('0')
      'Quantity to Pick'.enter('2')
      'lots'.shouldHaveCount(2)
      'Quantity Shipped'.enter('2')
      'lots'.shouldHaveCount(2)
      'lots.0.Number'.shouldEqual('CF01-MEL-02')
      'lots.1.Number'.shouldEqual('CF01-MEL-01')
      'lots'.shouldHaveCount(2)
      'Quantity to Pick'.enter('3')
      'Quantity Shipped'.enter('3')
      'OK'.click()
    'lines./Cap (C01)/.Quantity Shipped'.enter('50')
    'lines./Cap (C01)/.Edit'.click()
      'Add Lot'.click()
        'Lot Number'.enter('LOT-CAP-01')
        'Quantity'.enter('10')
        'Add another'.click()
        'Lot Number'.enter('LOT-CAP-02')
        'Quantity'.enter('10')
        'Add another'.click()
        'Lot Number'.enter('LOT-CAP-03')
        'Quantity'.enter('30')
        'OK'.click()
      'OK'.click()
    'lines./Hoodie (H01)/.Quantity Shipped'.enter('50')
    'lines./Little Bag (LB01)/.Quantity Shipped'.enter('50')
    'lines./Hoodie (H01)/.Edit'.click()
      'Add Lot'.click()
        'Lot Number'.enter('LOT-HOODIE-01')
        'Quantity'.enter('10')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-02')
        'Quantity'.enter('1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-03')
        'Quantity'.enter('30')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-04')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-05')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-06')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-07')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-08')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-09')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-0.10')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-11')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-12')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-21')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-22')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-22')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-23')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-24')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-25')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-26')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-27')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-28')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-29')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-30')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-31')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-32')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-32')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-33')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-34')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-35')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-36')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-37')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-38')
        'Quantity'.enter('0.1')
        'Add another'.click()
        'Lot Number'.enter('LOT-HOODIE-39')
        'Quantity'.enter('0.1')
        'OK'.click()
      'OK'.click()
    'Transport'.click()
      'Shipment Number'.shouldExist()
      'Add Pallet'.click()
        'Add Pallet'.shouldBeCurrentPage()
        'Shipment Number'.shouldExist()
        'OK'.click()
        'stFormRejection'.shouldContain('Pallet Serial Number is required')
        'Pallet Serial Number'.enter('PALLET-01')
        'CHEP?'.enter('Yes')
        'Add Lines'.click()
          'Add Products to Shipment Pallet'.shouldBeCurrentPage()
          'mainTable'.shouldHaveCount(39)
          'mainTable./LOT-CAP-01/.Quantity'.shouldEqual('10')
          'mainTable./LOT-HOODIE-03/.Quantity'.shouldEqual('30')
          'mainTable./Little Bag (LB01)/.Quantity'.shouldEqual('50')
          'mainTable./Little Bag (LB01)/.Serial/Lot'.shouldEqual('')
          'mainTable./LOT-CAP-01/.Include'.toggleTick()
          'mainTable./LOT-HOODIE-03/.Include'.toggleTick()
          'mainTable./Little Bag (LB01)/.Include'.toggleTick()
          'OK'.click()
        'Lines'.shouldHaveCount(3)
        'Lines./LOT-CAP-01/.Quantity'.shouldEqual('10')
        'Lines./LOT-HOODIE-03/.Quantity'.shouldEqual('30')
        'Lines./Little Bag (LB01)/.Quantity'.shouldEqual('50')
        'Lines./LOT-HOODIE-03/.Trash'.click()
        'Lines./LOT-HOODIE-03/.Really Trash?'.click()
        'Lines'.shouldHaveCount(2)
        'Add Lines'.click()
          'mainTable'.shouldHaveCount(37)
          'mainTable./LOT-HOODIE-03/.Include'.toggleTick()
          'OK'.click()
        'Lines'.shouldHaveCount(3)
        'OK'.click()
      'Add Pallet'.click()
        'Pallet Serial Number'.enter('PALLET-02')
        'Add Lines'.click()
          'mainTable'.shouldHaveCount(36)
          'mainTable./LOT-CAP-02/.Include'.toggleTick()
          'OK'.click()
        'OK'.click()
      'Pallets'.shouldHaveCount(2)
      'Pallet Count'.shouldEqual('1')
      'CHEP Pallet Count'.shouldEqual('1')
      'Back'.click()
    'OK'.click()
  'stFormRejection'.shouldntExist()
  'View Shipments'.click()
    'mainTable.1.Edit'.click()
      'Transport'.click()
        'Shipment Number'.shouldExist()
        'Pallets'.shouldHaveCount(2)
        'Pallets./PALLET-01/.Line Count'.shouldEqual('3')
        'Pallets./PALLET-01/.Total Quantity'.shouldEqual('90')
        'Pallets./PALLET-01/.Edit'.click()
          'Lines'.shouldHaveCount(3)
          'Add Lines'.click()
            'mainTable'.shouldHaveCount(35)
            'mainTable./LOT-HOODIE-02/.Include'.toggleTick()
            'OK'.click()
          'Lines'.shouldHaveCount(4)
          'OK'.click()
        'Pallets./PALLET-01/.Line Count'.shouldEqual('4')
        'Pallets./PALLET-01/.Edit'.click()
          'Add Lines'.click()
            'mainTable'.shouldHaveCount(34)
            'mainTable.0.Include'.toggleTick()
            'mainTable.1.Include'.toggleTick()
            'mainTable.2.Include'.toggleTick()
            'mainTable.3.Include'.toggleTick()
            'mainTable.5.Include'.toggleTick()
            'mainTable.6.Include'.toggleTick()
            'mainTable.7.Include'.toggleTick()
            'mainTable.8.Include'.toggleTick()
            'mainTable.9.Include'.toggleTick()
            'mainTable.10.Include'.toggleTick()
            'mainTable.11.Include'.toggleTick()
            'mainTable.12.Include'.toggleTick()
            'mainTable.13.Include'.toggleTick()
            'mainTable.14.Include'.toggleTick()
            'mainTable.15.Include'.toggleTick()
            'mainTable.16.Include'.toggleTick()
            'mainTable.17.Include'.toggleTick()
            'mainTable.18.Include'.toggleTick()
            'mainTable.19.Include'.toggleTick()
            'mainTable.20.Include'.toggleTick()
            'mainTable.21.Include'.toggleTick()
            'mainTable.22.Include'.toggleTick()
            'mainTable.23.Include'.toggleTick()
            'mainTable.24.Include'.toggleTick()
            'mainTable.25.Include'.toggleTick()
            'mainTable.26.Include'.toggleTick()
            'mainTable.27.Include'.toggleTick()
            'mainTable.28.Include'.toggleTick()
            'mainTable.29.Include'.toggleTick()
            'mainTable.30.Include'.toggleTick()
            'mainTable.31.Include'.toggleTick()
            'mainTable.32.Include'.toggleTick()
            'mainTable.33.Include'.toggleTick()
            'OK'.click()
          'Labels'.click()
            'Label Type'.shouldEqual('Pallet')
            'Source Type'.shouldEqual('Pallet')
            'Source Reference'.shouldEqual('PALLET-01')
            'Layout'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('Pallet.palletSerialNumber')
                'Caption'.enter('Pallet Number')
                'Distance from Left of Label (mm)'.enter('20')
                'Distance from Top of Label (mm)'.enter('1')
                'OK'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('Pallet.lotNumber08')
                'Caption'.enter('Lot Test 08')
                'Distance from Left of Label (mm)'.enter('0')
                'Distance from Top of Label (mm)'.enter('23')
                'Maximum Width (mm)'.enter('20')
                'Font Size'.enter('8')
                'OK'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('SOShipment.shipmentNumber')
                'Caption'.enter('Lot Test 08')
                'Distance from Left of Label (mm)'.enter('30')
                'Distance from Top of Label (mm)'.enter('0')
                'Maximum Width (mm)'.enter('20')
                'Font Size'.enter('8')
                'OK'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('Pallet.lotQuantity08')
                'Caption'.enter('Lot Qty 08')
                'Distance from Left of Label (mm)'.enter('20')
                'Distance from Top of Label (mm)'.enter('23')
                'Maximum Width (mm)'.enter('20')
                'Font Size'.enter('8')
                'OK'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('Pallet.lotDescription08')
                'Caption'.enter('Lot Qty 08')
                'Distance from Left of Label (mm)'.enter('40')
                'Distance from Top of Label (mm)'.enter('23')
                'Maximum Width (mm)'.enter('20')
                'Font Size'.enter('8')
                'OK'.click()
              'Add Field'.click()
                'Get Value From'.chooseOption('SOShipment.bolSerialNumber')
                'Caption'.enter('BOL serial number')
                'Distance from Left of Label (mm)'.enter('20')
                'Distance from Top of Label (mm)'.enter('17')
                'Maximum Width (mm)'.enter('20')
                'Font Size'.enter('8')
                'OK'.click()
              'Back'.click()
            'Download Labels PDF'.click()
            'Back'.click()
          'OK'.click()
        'Loaded At'.shouldEqual('Alto Pas, IL.')
        'Loaded At'.enter('Cumberland, IL.')
        'Deliver By'.shouldEqual('Truck')
        'Truck License Plate'.shouldEqual('BGH198')
        'Trailer License Plate'.shouldEqual('TRU965')
        'Driver'.shouldEqual('Bob Grenshen II')
        'Driver'.clickDropdown()
        'Driver'.shouldHaveNOptions(3) // including blank
        'Driver License'.shouldEqual('897-985-715')
        'Driver'.enter('Doug Underwood')
        'Carrier'.shouldEqual('Acme')
        'Carrier'.clickDropdown()
        'Carrier'.shouldHaveNOptions(3) // including blank
        'Carrier'.enter('ABC Trucking')
        'Driver License'.shouldEqual('7876-908-90')
        'Truck License Plate'.shouldEqual('DOUGIE')
        'Trailer License Plate'.shouldEqual('TDOUGIE')
        'Driver'.enter('Doug Underwood II')
        'Terms'.shouldEqual('FOB')
        'Load Date'.enter('21/1/2023')
        'Load Time'.enter('11:56')
        'Out Date'.enter('22/1/2023')
        'Out Time'.enter('14:45')
        'BOL Serial Number'.enter('023149-17516Y00143')
        'Bill of Lading PDF'.click()
        'Back'.click()
      'Create Invoice'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'mainTable.0.Edit'.click()
    'lines./Cap (C01)/.Quantity Shipped'.enter('100')
    'lines./Cap (C01)/.Edit'.click()
      'Add Lot'.click()
        'Lot Number'.enter('LOT-CAP-04')
        'Quantity'.enter('50')
        'OK'.click()
      'OK'.click()
    'lines./Hoodie (H01)/.Quantity Shipped'.enter('100')
    'lines./Little Bag (LB01)/.Quantity Shipped'.enter('100')
    'lines./Hoodie (H01)/.Edit'.click()
      'Add Lot'.click()
        'Lot Number'.enter('LOT-HOODIE-44')
        'Quantity'.enter('50')
        'OK'.click()
      'OK'.click()
    'WC Order Status'.enter('Completed')
    'OK'.click()
  'View Shipments'.click()
    'mainTable.2.Edit'.click()
      'Transport'.click()
        'Pallets'.shouldHaveCount(0)
        'Add Pallet'.click()
          'Pallet Serial Number'.enter('PALLET-03')
          'Add Lines'.click()
            'mainTable'.shouldHaveCount(3)
            'mainTable.0.Include'.toggleTick()
            'mainTable.1.Include'.toggleTick()
            'mainTable.2.Include'.toggleTick()
            'OK'.click()
          'OK'.click()
        'Bill of Lading PDF'.click()
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Quantity On Hand'.shouldEqual('27')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./LE01-MEL-01/.Quantity On Hand'.shouldEqual('16')
      'mainTable./LE01-MEL-02/.Quantity On Hand'.shouldEqual('11')
      'Back'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'mainTable./CF01-MEL-01/.Quantity On Hand'.shouldEqual('0')
      'mainTable./CF01-MEL-02/.Quantity On Hand'.shouldEqual('0')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('1')
      'Back'.click()
    'OK'.click()
  'mainTable./Lemon (LE01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('3')
    'Add Lot'.click()
      'Lot Number'.enter('LE01-MEL-01')
      'Quantity'.enter('1')
      'Add another'.click()
      'Lot Number'.enter('LE02-MEL-01')
      'Quantity'.enter('1')
      'OK'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('3')
    'Add Serial Number'.click()
      'Serial Number'.enter('CF01-MEL-01')
      'Add another'.click()
      'Serial Number'.enter('CF02-MEL-01')
      'OK'.click()
    'OK'.click()
  'mainTable./Hoodie with Logo (HL01)/.Transfer Between Locations'.click()
    'Add Lot'.shouldntExist()
    'Add Serial Number'.shouldntExist()
    'Back'.click()
  'mainTable./Lemon (LE01)/.Transfer Between Locations'.click()
    'From Location'.enter('Melbourne')
    'To Location'.enter('Sydney')
    'Quantity'.enter('30')
    'Add Lot'.click()
      'Lot Number'.enter('LE01-MEL-01')
      'Quantity'.enter('17')
      'Add another'.click()
      'Lot Number'.enter('LE01-MEL-02')
      'Quantity'.enter('12')
      'OK'.click()
    'OK'.click()
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./TOTAL/.Quantity On Hand'.shouldEqual('30')
      'searcher'.enter('Sydney')
      'mainTable./LE01-MEL-01/.Quantity On Hand'.shouldEqual('17')
      'mainTable./LE01-MEL-02/.Quantity On Hand'.shouldEqual('12')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('1')
      'Back'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Transfer Between Locations'.click()
    'From Location'.enter('Melbourne')
    'To Location'.enter('Sydney')
    'Quantity'.enter('4')
    'Add Serial Number'.click()
      'Serial Number'.enter('CF01-MEL-01')
      'Add another'.click()
      'Serial Number'.enter('CF01-MEL-02')
      'OK'.click()
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'mainTable./TOTAL/.Quantity On Hand'.shouldEqual('4')
      'searcher'.enter('Sydney')
      'mainTable./CF01-MEL-01/.Quantity On Hand'.shouldEqual('1')
      'mainTable./CF01-MEL-02/.Quantity On Hand'.shouldEqual('1')
      'mainTable./Unspecified/.Quantity On Hand'.shouldEqual('2')
      'Back'.click()
    'OK'.click()
  'mainTable./Lemon (LE01)/.Adjust Qty'.click()
    'Location'.enter('Sydney')
    'Quantity'.enter('-30')
    'lots./Unspecified/.Quantity'.shouldEqual('-30')
    'Add Lot'.click()
      'Lot Number'.enter('LE01-MEL-01')
      'Quantity'.enter('-17')
      'Add another'.click()
      'Lot Number'.enter('LE01-MEL-02')
      'Quantity'.enter('-12')
      'OK'.click()
    'OK'.click()
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'View Product Lots'.shouldBeCurrentPage()
      'searcher'.enter('Sydney')
      'mainTable./LE01-MEL-01/'.shouldntExist()
      'mainTable./LE01-MEL-02/'.shouldntExist()
      'Back'.click()
    'Back'.click()
  'mainTable./Corn Flakes (CF01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('-4')
    'lots./Unspecified/.Quantity'.shouldEqual('-4')
    'Add Lot'.shouldntExist()
    'Add Serial Number'.click()
      'Serial Number'.enter('CF01-MEL-01')
      'Quantity'.shouldntExist()
      'Add another'.click()
      'Serial Number'.enter('CF01-MEL-02')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO-GEN-01')
    'Location'.enter('Sydney')
    'Add Line'.click()
      'Add Serial'.shouldntExist()
      'Product'.enter('Corn Flakes (CF01)')
      'Quantity'.enter('3')
      'lots'.shouldHaveCount(1)
      'lots.0.Number'.shouldEqual('Unspecified')
      'lots.0.Quantity'.shouldEqual('3')
      'Add Serial Number'.click()
        'Add Serial Number'.shouldBeCurrentPage()
        'Product'.shouldEqual('Corn Flakes (CF01)')
        'Product'.shouldBeReadOnly()
        'Serial Number'.shouldEqual('Unspecified')
        'Serial Number'.enter('CFS01')
        'Quantity'.shouldntExist()
        'OK'.click()
      'lots'.shouldHaveCount(2)
      'lots./CFS01/.Quantity'.shouldEqual('1')
      'lots./Unspecified/.Quantity'.shouldEqual('2')
      'Add Serial Number'.click()
        'Serial Number'.enter('CFS01')
        'OK'.click()
        'stFormRejection'.shouldContain('This serial number is already on order')
        'Serial Number'.enter('CFS02')
        'OK'.click()
      'lots'.shouldHaveCount(3)
      'lots./CFS01/.Quantity'.shouldEqual('1')
      'lots./CFS02/.Quantity'.shouldEqual('1')
      'lots./Unspecified/.Quantity'.shouldEqual('1')
      'Add Serial Number'.click()
        'Serial Number'.enter('CFS03')
        'OK'.click()
      'lots'.shouldHaveCount(3)
      'lots./CFS01/.Quantity'.shouldEqual('1')
      'lots./CFS02/.Quantity'.shouldEqual('1')
      'lots./CFS03/.Quantity'.shouldEqual('1')
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Hoodie with Logo (HL01)')
      'Quantity'.enter('10')
      'Add Lot'.shouldntExist()
      'Add Serial'.shouldntExist()
      'Product'.enter('Lemon (LE01)')
      'lots'.shouldHaveCount(1)
      'Add Lot'.click()
        'Product'.shouldEqual('Lemon (LE01)')
        'Product'.shouldBeReadOnly()
        'Lot Number'.shouldEqual('Unspecified')
        'Lot Number'.enter('LEL01')
        'Quantity'.shouldEqual('10')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
        'OK'.click()
      'lots'.shouldHaveCount(1)
      'lots.0.Number'.shouldEqual('LEL01')
      'lots.0.Quantity'.shouldEqual('10')
      'lots.0.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(365).toLocalMMMDY()')
      'lots.0.Edit'.click()
        'Expiry Date'.enterExpression('global.todayLocal().incDays(188)')
        'OK'.click()
      'lots.0.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(188).toLocalMMMDY()')
      'lots.0.Number'.click()
        'Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(188)')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(90)')
        'OK'.click()
      'lots.0.Expiry Date'.shouldEqualExpression('global.todayLocal().incDays(90).toLocalMMMDY()')
      'Quantity'.enter('5')
      'lots'.shouldHaveCount(2)
      'lots.0.Quantity'.shouldEqual('10')
      'lots./Unspecified/.Quantity'.shouldEqual('-5')
      'lots.0.Edit'.click()
        'Edit Lot Quantity'.shouldBeCurrentPage()
        'Product'.shouldEqual('Lemon (LE01)')
        'Lot Number'.shouldEqual('LEL01')
        'Quantity'.enter('5')
        'OK'.click()
      'lots'.shouldHaveCount(1)
      'lots.0.Trash'.click()
      'lots.0.Really Trash?'.click()
      'Add Lot'.click()
        'Lot Number'.clickDropdown()
        'Lot Number'.enter('LEL01-01')
        'Quantity'.enter('3')
        'OK'.click()
      'lots'.shouldHaveCount(2)
      'lots./Unspecified/.Quantity'.shouldEqual('2')
      'Add Lot'.click()
        'Add Lot Quantity'.shouldBeCurrentPage()
        'Lot Number'.shouldEqual('Unspecified')
        'Quantity'.shouldEqual('2')
        'Lot Number'.enter('LEL02')
        'OK'.click()
      'lots'.shouldHaveCount(2)
      'lots./Unspecified/.Quantity'.shouldntExist()
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'mainTable./CFS01/.Quantity on POs'.shouldEqual('1')
      'mainTable./CFS02/.Quantity on POs'.shouldEqual('1')
      'mainTable./CFS03/.Quantity on POs'.shouldEqual('1')
      'Back'.click()
    'Back'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'View Product Lots'.shouldBeCurrentPage()
      'mainTable./TOTAL/.Quantity on POs'.shouldEqual('5')
      'mainTable./TOTAL/.Quantity On Hand'.shouldEqual('0')
      'mainTable./LEL02/.Quantity on POs'.shouldEqual('2')
      'mainTable./LEL01-01/.Quantity on POs'.shouldEqual('3')
      'mainTable./LEL01-01/.Location'.shouldEqual('Sydney')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Receipt Number'.shouldEqual('PO-GEN-01-01')
    'Lines./Lemon (LE01)/.Edit'.click()
      'lots'.shouldHaveCount(2)
      'lots./LEL01-01/.Quantity'.shouldEqual('3')
      'lots./LEL01-01/.Edit'.click()
        'Quantity'.enter('4')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
        'OK'.click()
      'OK'.click()
      'stFormRejection'.shouldContain('Cannot have an Unspecified lot with a negative quantity')
'helper'.simulateBrowserRefresh()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Lines./Lemon (LE01)/.Edit'.click()
      'lots./LEL01-01/.Quantity'.shouldEqual('3')
      'lots./LEL02/.Quantity'.shouldEqual('2')
      'Received'.enter('4')
      'OK'.click()
      'stFormRejection'.shouldContain('Cannot have an Unspecified lot with a negative quantity')
      'Add Lot'.shouldExist()
      'lots./LEL02/.Edit'.click()
        'Product'.shouldEqual('Lemon (LE01)')
        'Quantity'.enter('1')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
        'OK'.click()
      'OK'.click()
    'Lines./Corn Flakes (CF01)/.Edit'.click()
      'lots'.shouldHaveCount(3)
      'Add Serial Number'.shouldExist()
      'lots./CFS03/.Trash'.click()
      'lots./CFS03/.Really Trash?'.click()
      'Received'.enter('2')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'View Product Serial Numbers'.shouldBeCurrentPage()
      'mainTable./CFS01/.Quantity on POs'.shouldEqual('0')
      'mainTable./CFS01/.Quantity on Hand'.shouldEqual('1')
      'mainTable./CFS02/.Quantity on POs'.shouldEqual('0')
      'mainTable./CFS02/.Quantity on Hand'.shouldEqual('1')
      'mainTable./CFS03/.Quantity on POs'.shouldEqual('1')
      'Back'.click()
    'Back'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./TOTAL/.Quantity on POs'.shouldEqual('1')
      'mainTable./TOTAL/.Quantity On Hand'.shouldEqual('4')
      'mainTable./LEL01-01/.Quantity on POs'.shouldEqual('0')
      'mainTable./LEL01-01/.Quantity on Hand'.shouldEqual('3')
      'mainTable./LEL02/.Quantity on POs'.shouldEqual('1')
      'mainTable./LEL02/.Quantity on Hand'.shouldEqual('1')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'stocktend_inventory'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./LEL02/.Quantity on POs'.shouldEqual('1')
      'mainTable./LEL02/.Quantity on Hand'.shouldEqual('1')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Receipt Number'.shouldEqual('PO-GEN-01-02')
    'Lines./Corn Flakes (CF01)/.Edit'.click()
      'lots'.shouldHaveCount(1)
      'lots./CFS03/.Edit'.click()
        'Edit Serial Number'.shouldBeCurrentPage()
        'Serial Number'.enter('CFS01')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
        'OK'.click()
      'OK'.click()
      'stFormRejection'.shouldContain('Serial Number CFS01 is already in stock')
      'lots./CFS01/.Edit'.click()
        'Serial Number'.enter('CFS04')
        'Expiry Date'.enterExpression('global.todayLocal().incDays(365)')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'searcher'.enter('l')
  'mainTable./Lemon (LE01)/.Edit Product'.click()
    'View Lots'.click()
      'mainTable./LEL02/.Quantity on POs'.shouldEqual('0')
      'mainTable./LEL02/.Quantity on Hand'.shouldEqual('2')
      'Back'.click()
    'Back'.click()
  'searcher'.enter('')
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'View Serial Numbers'.click()
      'mainTable./CFS03/'.shouldntExist()
      'mainTable./CFS04/.Quantity on Hand'.shouldEqual('1')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'View Shipments'.click()
    'mainTable.1.Edit'.click()
      'Transport'.click()
        'Bill of Lading PDF'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'2'.chapter()
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('Yes')
  'Show WO and Bundle Costs Including Tax'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'Customize'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityPickable')
      'Caption'.enter('Quantity Pickable')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityAllocatedForPicking')
      'Caption'.enter('Quantity Allocated for Picking')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityMakeable')
      'Caption'.enter('Quantity Makeable')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityAllocatedForMaking')
      'Caption'.enter('Quantity Allocated for Making')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'OK'.click()
  'mainTable./Brag Set (BS01)/.Adjust Qty'.click()
    'Quantity'.enter('1')
    'Unit Price (Inc Tax)'.enter('200.00')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('10')
    'Unit Price (Inc Tax)'.enter('50.00')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity'.enter('9')
    'Unit Price (Inc Tax)'.enter('30.00')
    'OK'.click()
  'searcher'.enter('tag')
  'mainTable./Tag (TA01)/.Adjust Qty'.click()
    'Quantity'.enter('1000')
    'Unit Price (Inc Tax)'.enter('0.20')
    'OK'.click()
  'searcher'.enter('')
  'Bundles'.click()
    'Bundles'.shouldBeCurrentPage()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Overhead Cost'.enter('10.00')
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.shouldEqual('1')
        'Quantity On Hand'.shouldEqual('10')
        'Avg Unit Cost'.shouldEqual('50.00')
        'Total Cost'.shouldEqual('50.00')
        'OK'.click()
      'components'.shouldHaveCount(1)
      'components.0.Product'.shouldEqual('Big Bag (BB01)')
      'components.0.Quantity'.shouldEqual('1')
      'components.0.Quantity Pickable'.shouldEqual('10')
      'components.0.Total Cost'.shouldEqual('50.00')
      'Total Bundle Cost'.shouldEqual('60.00')
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'Quantity On Hand'.shouldEqual('9')
        'Avg Unit Cost'.shouldEqual('30.00')
        'Total Cost'.shouldEqual('90.00')
        'OK'.click()
      'Total Bundle Cost'.shouldEqual('150.00')
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'Quantity On Hand'.shouldEqual('1000')
        'Avg Unit Cost'.shouldEqual('0.20')
        'Total Cost'.shouldEqual('2.00')
        'OK'.click()
      'Total Bundle Cost'.shouldEqual('152.00')
      'OK'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable.0.Product'.shouldEqual('Brag Set (BS01)')
    'mainTable.0.Sellable Quantity'.shouldEqual('4')
    'Add'.click()
      'Bundle Product'.enter('Tag (TA01)')
      'Overhead Cost'.enter('1.00')
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Brag Set (BS01)')
        'OK'.click()
        'stFormRejection'.shouldContain('Cannot add this product, as it is already a parent bundle to this component')
        'Component Product'.enter('Tag Outer (TO01)')
        'OK'.click()
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Tag Label (TL01)')
        'Quantity'.enter(2)
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Bundle Product'.enter('Tag (TA01)')
      'OK'.click()
      'stFormRejection'.shouldContain('This product is already a bundle product')
      'Back'.click()
      'Yes - Cancel my changes'.click('doc')
    'Back'.click()
  'searcher'.enter('tag')
  'mainTable./Tag (TA01)/.Adjust Qty'.click()
    'Quantity'.enter('-1000')
    'OK'.click()
  'Bundles'.click()
    'mainTable./Tag (TA01)/.Sellable Quantity'.shouldEqual('0')
    'mainTable./Brag Set (BS01)/.Sellable Quantity'.shouldEqual('1')
    'Back'.click()
  'mainTable./Tag Outer (TO01)/.Adjust Qty'.click()
    'Quantity'.enter('10')
    'Unit Price (Inc Tax)'.enter('0.05')
    'OK'.click()
  'mainTable./Tag Label (TL01)/.Adjust Qty'.click()
    'Quantity'.enter('10')
    'Unit Price (Inc Tax)'.enter('0.02')
    'OK'.click()
  'Bundles'.click()
    'mainTable./Tag (TA01)/.Sellable Quantity'.shouldEqual('5')
    'mainTable./Brag Set (BS01)/.Sellable Quantity'.shouldEqual('1')
    'Back'.click()
  'mainTable./Tag Label (TL01)/.Adjust Qty'.click()
    'Quantity'.enter('10') // balance 20
    'OK'.click()
  'Bundles'.click()
    'mainTable./Tag (TA01)/.Sellable Quantity'.shouldEqual('10')
    'mainTable./Brag Set (BS01)/.Sellable Quantity'.shouldEqual('2')
    'Back'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'stocktend_inventory'.click()
    'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
    'mainTable./Brag Set (BS01)/.Avg Unit Cost'.shouldEqual('200.00')
    'searcher'.enter('Tag')
    'mainTable./Tag Label (TL01)/.Quantity On Hand'.shouldEqual('20')
    'mainTable./Tag (TA01)/.Quantity On Hand'.shouldEqual('0')
    'searcher'.enter('')
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Log Changes To Stock For Problem Diagnosis'.enter('Yes')
  'OK'.click()
'helper'.addWCOrder({differentForeman: true, product: 'Brag Set (BS01)', quantity: 2, orderDate: global.todayLocal(), status: 'wc-processing', shippingIncTax: 20.00})
'stocktend_fulfillment'.click()
  'stocktend_inventory'.click()
    'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('0')
    'mainTable./Brag Set (BS01)/.Avg Unit Cost'.shouldEqual('180.45')
    'searcher'.enter('Tag')
    'mainTable./Tag (TA01)/.Quantity On Hand'.shouldEqual('0')
    'mainTable./Tag (TA01)/.Avg Unit Cost'.shouldEqual('1.09')
    'mainTable./Tag Label (TL01)/.Quantity On Hand'.shouldEqual('0')
    'mainTable./Tag Label (TL01)/.View History'.click()
      'mainTable.0.Quantity'.shouldEqual('-20')
      'Back'.click()
    'mainTable./Tag Label (TL01)/.Quantity Pickable'.shouldEqual('20')
    'mainTable./Tag (TA01)/.Quantity Pickable'.shouldEqual('0')
    'mainTable./Tag (TA01)/.Quantity Makeable'.shouldEqual('10')
    'mainTable./Tag Outer (TO01)/.Quantity On Hand'.shouldEqual('0')
    'mainTable./Tag Outer (TO01)/.Quantity Pickable'.shouldEqual('10')
    'mainTable./Tag Outer (TO01)/.Inventory by Location'.click()
      'mainTable./General/.Pickable'.shouldEqual('10')
      'Back'.click()
    'searcher'.enter('')
    'Back'.click()
  'Refresh'.click()
  'mainTable'.shouldHaveCount(1)
  'stocktend_locations'.click()
    'Add'.click()
      'Location Name'.enter('Perth')
      'OK'.click()
    'Back'.click()
  'mainTable.0.Edit'.click()
    'Lines.0.Edit'.click()
      'Quantity Makeable'.shouldEqual('1')
      'OK'.click()
    'Save'.click()
    'stocktend_inventory'.click()
      'searcher'.enter('tag')
      'mainTable./Tag (TA01)/.Edit Product'.click()
        'Inventory by Location'.click()
          'mainTable./General/.Pickable'.shouldEqual('0')
          'mainTable./General/.Reserved for Customer Orders'.shouldEqual('0')
          'mainTable./General/.On Hand'.shouldEqual('0')
          'mainTable./General/.Makeable'.shouldEqual('10')
          'Back'.click()
        'Back'.click()
      'searcher'.enter('')
      'mainTable./Brag Set (BS01)/.Edit Product'.click()
        'Inventory by Location'.click()
          'mainTable./General/.Pickable'.shouldEqual('1')
          'mainTable./General/.Makeable'.shouldEqual('1')
          'mainTable./General/.Reserved for Customer Orders'.shouldEqual('2')
          'Back'.click()
        'Back'.click()
      'searcher'.enter('TO01')
      'mainTable./Tag Outer (TO01)/.Quantity Pickable'.shouldEqual('10')
      'mainTable./Tag Outer (TO01)/.Inventory by Location'.click()
        'mainTable./General/.Pickable'.shouldEqual('10')
        'Back'.click()
      'Back'.click()
    'Lines'.shouldHaveCount(6)
    'Ship From Location'.enter('Perth')
    'Lines.0.Ship From Location'.shouldEqual('Perth')
    'Ship From Location'.enter('General')
    'Lines.0.Edit'.click()
      'Quantity Makeable'.shouldEqual('1')
      'OK'.click()
    'Lines.0.Ship From Location'.shouldEqual('General')
    'Lines.3.Ship From Location'.shouldEqual('General')
    'Lines.5.Ship From Location'.shouldEqual('General')
    'stocktend_inventory'.click()
      'searcher'.enter('tag')
      'mainTable./Tag (TA01)/.Edit Product'.click()
        'Inventory by Location'.click()
          'mainTable./General/.Pickable'.shouldEqual('0')
          'mainTable./General/.Reserved for Customer Orders'.shouldEqual('0')
          'mainTable./General/.On Hand'.shouldEqual('0')
          'mainTable./General/.Makeable'.shouldEqual('10')
          'Back'.click()
        'Back'.click()
      'searcher'.enter('')
      'mainTable./Brag Set (BS01)/.Edit Product'.click()
        'Inventory by Location'.click()
          'mainTable./General/.Pickable'.shouldEqual('1')
          'mainTable./General/.Makeable'.shouldEqual('1')
          'mainTable./General/.Reserved for Customer Orders'.shouldEqual('2')
          'Back'.click()
        'Back'.click()
      'Back'.click()
    'Lines.0.Edit'.click()
      'Quantity Makeable'.shouldEqual('1') // ***
      'OK'.click()
    'Fulfill Stage'.enter('Picking')
    'Lines.0.Fulfill Stage'.shouldEqual('Picking')
    'Lines.3.Fulfill Stage'.shouldEqual('Picking')
    'Lines.5.Fulfill Stage'.shouldEqual('Picking')
    'Priority'.enter('3')
    'Lines.0.Priority'.shouldEqual('3')
    'Lines.3.Priority'.shouldEqual('3')
    'Lines.5.Priority'.shouldEqual('3')
    'Lines.0.Edit'.click()
      'Quantity Makeable'.shouldEqual('1')
      'OK'.click()
    'OK'.click()
  'Packing Lists'.click()
  'Select All'.click()
  'Download Packing Lists PDF'.click()
  'Back'.click()
  'mainTable.0.Edit'.click()
    'Packable From This Location'.shouldEqual('Yes')
    'Lines.0.Line No'.shouldEqual('001')
    'Lines.0.Product'.shouldEqual('Brag Set (BS01)')
    'Lines.0.Packable'.shouldEqual('Yes')
    'Lines.0.Quantity to Pack'.shouldEqual('2')
    'Lines.0.Edit'.click()
      'Quantity Pickable'.shouldEqual('1')
      'Quantity to Pick'.shouldEqual('1')
      'Quantity Makeable'.shouldEqual('1')
      'Quantity to Make'.shouldEqual('1')
      'Quantity Packable'.shouldEqual('2')
      'Quantity to Pack'.shouldEqual('2')
      'Quantity to Pack'.shouldBeReadOnly()
      'OK'.click()
    'Lines.1.Line No'.shouldEqual('001.001')
    'Lines.1.Product'.shouldEqual('Big Bag (BB01)')
    'Lines.1.Packable'.shouldEqual('Yes')
    'Lines.2.Line No'.shouldEqual('001.002')
    'Lines.2.Product'.shouldEqual('Little Bag (LB01)')
    'Lines.2.Packable'.shouldEqual('Yes')
    'Lines.2.Quantity to Pack'.shouldEqual('3')
    'Lines.3.Line No'.shouldEqual('001.003')
    'Lines.3.Product'.shouldEqual('Tag (TA01)')
    'Lines.3.Packable'.shouldEqual('Yes')
    'Lines.3.Quantity to Pack'.shouldEqual('10')
    'Lines.4.Line No'.shouldEqual('001.003.001')
    'Lines.4.Product'.shouldEqual('Tag Outer (TO01)')
    'Lines.4.Packable'.shouldEqual('Yes')
    'Lines.4.Quantity to Pack'.shouldEqual('10')
    'Lines.5.Line No'.shouldEqual('001.003.002')
    'Lines.5.Product'.shouldEqual('Tag Label (TL01)')
    'Lines.5.Packable'.shouldEqual('Yes')
    'Lines.5.Quantity to Pack'.shouldEqual('20')
    'Lines.1.Edit'.click()
      'Quantity to Pick'.shouldBeReadOnly()
      'OK'.click()
    'Lines.0.Edit'.click()
      'Quantity to Pick'.enter('0')
      'Quantity to Make'.enter('0')
      'OK'.click()
    'Lines'.shouldHaveCount(1)
    'Lines.0.Edit'.click()
      'Quantity to Pick'.enter('1')
      'OK'.click()
    'Lines'.shouldHaveCount(1)
    'Lines.0.Edit'.click()
      'Quantity to Make'.enter('1')
      'OK'.click()
    'Lines.2.Quantity to Pack'.shouldEqual('3')
    'Lines.3.Quantity to Pack'.shouldEqual('10')
    'Lines.4.Quantity to Pack'.shouldEqual('10')
    'Lines.5.Quantity to Pack'.shouldEqual('20')
    'Lines.0.Edit'.click()
      'Quantity to Pick'.enter('2')
      'Quantity to Make'.enter('0')
      'Quantity Shipped'.enter('2')
      'OK'.click()
    'Transport'.click()
      'Pallets'.shouldBeEmpty()
      'Add Pallet'.click()
        'Pallet Serial Number'.enter('PALLET-03')
        'Add Lines'.click()
          'mainTable'.shouldHaveCount(1)
          'OK'.click()
        'OK'.click()
      'Back'.click()
    'WC Order Status'.enter('Completed')
    'OK'.click()
  'stocktend_inventory'.click()
    'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('-1')
    'searcher'.enter('Tag')
    'mainTable./Tag (TA01)/.Quantity Makeable'.shouldEqual('10')
    'mainTable./Tag Label (TL01)/.Quantity On Hand'.shouldEqual('20')
    'mainTable./Tag Label (TL01)/.Quantity Pickable'.shouldEqual('20')
    'searcher'.enter('')
    'Back'.click()
'3'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('Yes')
  'OK'.click()
'stocktend_locations'.click()
  'Add'.click()
    'Name'.enter('Sydney')
    'OK'.click()
  'Add'.click()
    'Name'.enter('Melbourne')
    'OK'.click()
  'Add'.click()
    'Name'.enter('Perth')
    'OK'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Cap (C01)', quantity: 1, orderDate: global.todayLocal().incDays(-10), status: 'wc-processing', shippingIncTax: 20.00})
'stocktend_inventory'.click()
  'Customize'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityPackable')
      'Caption'.enter('Qty Packable')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityReservedForCustomerOrders')
      'Caption'.enter('Qty Reserved')
      'Minimum Decimals'.enter(0)
      'Maximum Decimals'.enter(0)
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('-1')
  'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('1')
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'On Hand'.shouldEqual('-1')
    'Back'.click()
  'stocktend_fulfillment'.click()
    'mainTable.0.Edit'.click()
      'Ship From Location'.shouldEqual('General')
      'Ship From Location'.enter('Melbourne')
      'OK'.click()
    'Back'.click()
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'On Hand'.shouldEqual('0')
    'Location'.enter('Melbourne')
    'mainTable'.shouldHaveCount(2) // including total
    'On Hand'.shouldEqual('-1')
    'Back'.click()
  'Back'.click()
  'stocktend_fulfillment'.click()
    'mainTable.0.Edit'.click()
      'Ship From Location'.enter('General')
      'OK'.click()
    'Back'.click()
'helper'.simulateBrowserRefresh()
'stocktend_fulfillment'.click()
  'mainTable.0.WC Status'.shouldEqual('Processing')
  'mainTable.0.Packable'.shouldEqual('No')
  'helper'.setWCStockLevel('Cap (C01)', 0, {differentForeman: true})
  'Refresh'.click()
  'mainTable.0.Packable'.shouldEqual('Yes')
  'mainTable.0.WC Status'.shouldEqual('Processing')
  'mainTable.0.Edit'.click()
    'Lines.0.Edit'.click()
      'Back'.click()
    'Back'.click()
  'mainTable.0.WC Status'.shouldEqual('Processing')
  'helper'.setWCStockLevel('Cap (C01)', -1, {differentForeman: true})
  'Refresh'.click()
  'mainTable.0.Packable'.shouldEqual('No')
  'Back'.click()
'helper'.setWCStockLevel('Cap (C01)', 0, {differentForeman: true})
'helper'.simulateBrowserRefresh()
'stocktend_fulfillment'.click()
  'mainTable.0.Packable'.shouldEqual('Yes')
  'Back'.click()
'helper'.setWCStockLevel('Cap (C01)', -1)
'stocktend_fulfillment'.click()
  'mainTable'.shouldHaveCount(1)
  'stocktend_inventory'.click()
    'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('1')
    'Back'.click()
  'mainTable.0.Edit'.click()
    'WC Order Status'.shouldEqual('Processing')
    'WC Order Status'.clickDropdown()
    'WC Order Status'.shouldHaveOption('Pending')
    'WC Order Status'.shouldHaveOption('On-hold')
    'WC Order Status'.shouldHaveOption('Processing')
    'WC Order Status'.shouldHaveOption('Completed')
    'WC Order Status'.enter('Pending')
    'OK'.click()
  'mainTable.0.WC Status'.shouldEqual('Pending')
  'stocktend_inventory'.click()
    'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('0')
    'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('0')
    'Back'.click()
  'mainTable.0.Edit'.click()
    'WC Order Status'.enter('On-hold')
    'OK'.click()
  'mainTable.0.WC Status'.shouldEqual('On-hold')
  'stocktend_inventory'.click()
    'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('-1')
    'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('1')
    'Back'.click()
  'mainTable.0.Edit'.click()
    'lines.0.Edit'.click()
      'Quantity To Pick'.enter('1')
      'Quantity Shipped'.enter('1')
      'OK'.click()
    'WC Order Status'.enter('Completed')
    'OK'.click()
  'stocktend_inventory'.click()
    'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('-1')
    'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('0')
    'Back'.click()
  'mainTable'.shouldHaveCount(0)
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity'.enter('1')
    'OK'.click()
  'mainTable./Hoodie (H01)/.Adjust Qty'.click()
    'Quantity'.enter('26')
    'OK'.click()
  'helper'.checkNoNegativeIds()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Location'.enter('Sydney')
    'Quantity'.enter('9')
    'OK'.click()
  'helper'.checkNoNegativeIds()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Location'.enter('Melbourne')
    'Quantity'.enter('9')
    'OK'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity'.enter('11')
    'OK'.click()
  'searcher'.enter('polo')
  'mainTable./Polo (P01)/.Adjust Qty'.click()
    'Location'.enter('Sydney')
    'Quantity'.enter('5')
    'OK'.click()
  'mainTable./Polo (P01)/.Adjust Qty'.click()
    'Quantity'.enter('5')
    'OK'.click()
  'searcher'.enter('vnec')
  'mainTable./Vneck Tshirt (V01)/.Adjust Qty'.click()
    'Location'.enter('Sydney')
    'Quantity'.enter('7')
    'OK'.click()
  'searcher'.enter('')
  'Back'.click()
'helper'.checkNoNegativeIds()
'stocktend_inventory'.click()
  'searcher'.enter('vnec')
  'mainTable./Vneck Tshirt (V01)/.Quantity On Hand'.shouldEqual('7')
  'mainTable./Vneck Tshirt (V01)/.Qty Packable'.shouldEqual('7') //****
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'mainTable./Vneck Tshirt (V01)/'.shouldntExist()
    'Location'.enter('Sydney')
    'mainTable./Vneck Tshirt (V01)/.On Hand'.shouldEqual('7')
    'mainTable./Vneck Tshirt (V01)/.Packable'.shouldEqual('7')
    'Back'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Vneck Tshirt (V01)', quantity: 7, orderDate: global.todayLocal().incDays(-3), status: 'wc-on-hold', shippingIncTax: 20.00})
'helper'.addWCOrderItem({product: 'Cap (C01)', quantity: 8})
'stocktend_inventory'.click()
  'searcher'.enter('vnec')
  'mainTable./Vneck Tshirt (V01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'stocktend_inventory'.click()
  'Location Inventory'.click()
    'mainTable./Cap (C01)/.View History'.click()
      'mainTable./Sale/.Quantity'.shouldEqual('-8')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'helper'.trashAll('Configuration')
'helper'.trashAll('Morsel')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'searcher'.enter('vnec')
  'mainTable./Vneck Tshirt (V01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Vneck Tshirt (V01)/.Qty Packable'.shouldEqual('7')
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'mainTable./Vneck Tshirt (V01)/.On Hand'.shouldEqual('-7')
    'mainTable./Vneck Tshirt (V01)/.Packable'.shouldEqual('0')
    'Location'.enter('Sydney')
    'mainTable./Vneck Tshirt (V01)/.On Hand'.shouldEqual('7')
    'mainTable./Vneck Tshirt (V01)/.Packable'.shouldEqual('7')
    'Back'.click()
  'searcher'.enter('cap')
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('21') 
  'mainTable./Cap (C01)/.Qty Reserved'.shouldEqual('8')
  'mainTable./Cap (C01)/.Qty Packable'.shouldEqual('29') // ***
  'Back'.click()
'stocktend_fulfillment'.click()
  'mainTable'.shouldHaveCount(1)
  'mainTable.0.Edit'.click()
    'Fulfill Stage'.shouldEqual('Waiting')
    'Lines.0.Fulfill Stage'.shouldEqual('Waiting')
    'Lines.1.Fulfill Stage'.shouldEqual('Waiting')
    'Fulfill Stage'.enter('Packing')
    'Lines.0.Fulfill Stage'.shouldEqual('Packing')
    'Lines.1.Fulfill Stage'.shouldEqual('Packing')
    'Priority'.enter('1')
    'Lines.0.Priority'.shouldEqual('1')
    'Lines.1.Priority'.shouldEqual('1')
    'Priority'.enter('2')
    'Lines.0.Priority'.shouldEqual('2')
    'Lines.1.Priority'.shouldEqual('2')
    'OK'.click()
  'mainTable.0.Fulfill Stage'.shouldEqual('Packing')
  'mainTable.0.Priority'.shouldEqual('2')
  'Back'.click()
'helper'.addWCOrder({differentForeman: true, product: 'Polo (P01)', quantity: 5, orderDate: global.todayLocal().incDays(-2), status: 'wc-processing', shippingIncTax: 20.00})
'helper'.addWCOrderItem({differentForeman: true, product: 'Cap (C01)', quantity: 6})
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('15') 
  'mainTable./Cap (C01)/.Qty Packable'.shouldEqual('29')
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable./Cap (C01)/.Quantity'.shouldEqual('6')
  'mainTable./Cap (C01)/.Status'.shouldEqual('Processing')
  'Back'.click()
'stocktend_inventory'.click()
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'mainTable./Cap (C01)/.Packable'.shouldEqual('11')
    'Back'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'mainTable'.shouldHaveCount(2)
  'Back'.click()
'helper'.addWCOrder({differentForeman: true, product: 'Hoodie (H01)', quantity: 3, orderDate: global.todayLocal().incDays(-1), status: 'wc-pending', shippingIncTax: 20.00})
'helper'.addWCOrderItem({differentForeman: true, product: 'Cap (C01)', quantity: 4})
'stocktend_fulfillment'.click()
  'mainTable'.shouldHaveCount(3)
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('15') 
  'mainTable./Cap (C01)/.Qty Packable'.shouldEqual('29')
  'Back'.click()
'helper'.addWCOrder({differentForeman: true, product: 'Hoodie (H01)', quantity: 3, orderDate: global.todayLocal(), status: 'wc-pending', shippingIncTax: 20.00})
'stocktend_inventory'.click()
  'searcher'.enter('vnec')
  'mainTable./Vneck Tshirt (V01)/.Qty Packable'.shouldEqual('7')
  'searcher'.enter('') 
  'mainTable./Cap (C01)/.Qty Packable'.shouldEqual('29')
  'mainTable./Hoodie (H01)/.Qty Packable'.shouldEqual('26')
  'searcher'.enter('polo')
  'mainTable./Polo (P01)/.Qty Packable'.shouldEqual('10')
  'Location Inventory'.click()
    'Location'.shouldEqual('General')
    'mainTable./Vneck Tshirt (V01)/.Packable'.shouldEqual('0')
    'mainTable./Cap (C01)/.On Hand'.shouldEqual('-3')
    'mainTable./Cap (C01)/.Packable'.shouldEqual('11') // --
    'mainTable./Hoodie (H01)/.Packable'.shouldEqual('26')
    'mainTable./Polo (P01)/.Packable'.shouldEqual('5')
    'Location'.enter('Sydney')
    'mainTable./Vneck Tshirt (V01)/.Packable'.shouldEqual('7')
    'mainTable./Cap (C01)/.Packable'.shouldEqual('9')
    'mainTable./Polo (P01)/.Packable'.shouldEqual('5')
    'Location'.enter('Melbourne')
    'mainTable./Cap (C01)/.Packable'.shouldEqual('9')
    'Back'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'Unfulfilled Sales Orders'.shouldBeCurrentPage()
  'mainTable.0.Order Date'.shouldEqualExpression('global.todayLocal().incDays(-3).toLocalMMMDY()')
  'mainTable.0.WC Status'.shouldEqual('On-hold')
  'mainTable.0.Ship From Location'.shouldEqual('General')
  'mainTable.0.Packable'.shouldEqual('Partially')
  'mainTable.0.Fulfill Stage'.shouldEqual('Packing')
  'mainTable.1.Order Date'.shouldEqualExpression('global.todayLocal().incDays(-2).toLocalMMMDY()')
  'mainTable.1.WC Status'.shouldEqual('Processing')
  'mainTable.1.Ship From Location'.shouldEqual('General')
  'mainTable.1.Packable'.shouldEqual('Partially')
  'mainTable.2.Order Date'.shouldEqualExpression('global.todayLocal().incDays(-1).toLocalMMMDY()')
  'mainTable.2.WC Status'.shouldEqual('Pending')
  'mainTable.2.Ship From Location'.shouldEqual('General')
  'mainTable.2.Packable'.shouldEqual('Partially')
  'mainTable.3.Order Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
  'mainTable.3.WC Status'.shouldEqual('Pending')
  'mainTable.3.Ship From Location'.shouldEqual('General')
  'mainTable.3.Packable'.shouldEqual('Yes')
  'mainTable.0.Edit'.click() // Packable Quantities:       GEN: P01: 5, C01: 11, H01 26, V01: 0;     SYD: V01: 7, P01: 5, C01: 9;     MEL: C01: 9
    'Sales Order Fulfillment'.shouldBeCurrentPage() // V01 x 7, C01 x 8, qoh not yet reduced
    'Ship From Location'.shouldEqual('General')
    'Packable From This Location'.shouldEqual('Partially')
    'Ship From Location'.enter('Melbourne')
    'Lines'.shouldHaveCount(2)
    'Lines.0.Product'.shouldEqual('Vneck Tshirt (V01)')
    'Lines.0.Quantity Ordered'.shouldEqual('7')
    'Lines.0.Packable'.shouldEqual('No')
    'Lines.0.Quantity to Pack'.shouldEqual('0')
    'Lines.1.Product'.shouldEqual('Cap (C01)')
    'Lines.1.Quantity Ordered'.shouldEqual('8')
    'Lines.1.Packable'.shouldEqual('Yes')
    'Lines.1.Quantity to Pack'.shouldEqual('8')
    'Packable'.shouldEqual('Partially')
    'Ship From Location'.enter('Perth')
    'Packable'.shouldEqual('No')
    'Ship From Location'.enter('Sydney')
    'Packable'.shouldEqual('Yes')
    'Priority'.shouldEqual('2')
    'Priority'.enter('1')
    'Fulfill Stage'.shouldEqual('Packing')
    'WC Order Status'.shouldEqual('On-hold')
    'Our Notes'.enter('Send on Wednesday')
    'Lines'.shouldHaveCount(2)
    'Lines.0.Product'.shouldEqual('Vneck Tshirt (V01)')
    'Lines.0.Quantity Ordered'.shouldEqual('7')
    'Lines.0.Packable'.shouldEqual('Yes')
    'Lines.0.Quantity to Pack'.shouldEqual('7')
    'Lines.1.Product'.shouldEqual('Cap (C01)')
    'Lines.1.Quantity Ordered'.shouldEqual('8')
    'Lines.1.Packable'.shouldEqual('Yes')
    'Lines.1.Quantity to Pack'.shouldEqual('8')
    'Lines.0.Edit'.click()
      'Sales Order Line Fulfillment'.shouldBeCurrentPage()
      'Product'.shouldEqual('Vneck Tshirt (V01)')
      'Quantity Ordered'.shouldEqual('7')
      'Quantity Ordered'.shouldBeReadOnly()
      'Quantity Pickable'.shouldEqual('7')
      'Quantity Pickable'.shouldBeReadOnly()
      'Quantity Makeable'.shouldntExist()
      'Quantity to Make'.shouldntExist()
      'Quantity Packable'.shouldntExist()
      'Quantity to Pack'.shouldntExist()
      'Quantity to Pick'.shouldEqual('7')
      'Quantity Shipped'.shouldEqual('0')
      'Quantity Remaining To Ship'.shouldEqual('7')
      'Quantity Remaining To Ship'.shouldBeReadOnly()
      'Fulfill Stage'.shouldEqual('Packing')
      'Quantity to Pick'.enter('6')
      'OK'.click()
    'Lines.0.Quantity to Pack'.shouldEqual('6')
    'Lines.1.Edit'.click()
      'Product'.shouldEqual('Cap (C01)')
      'Quantity Ordered'.shouldEqual('8')
      'Quantity Pickable'.shouldEqual('9')
      'Quantity to Pick'.shouldEqual('8')
      'Quantity Shipped'.shouldEqual('0')
      'Quantity Remaining To Ship'.shouldEqual('8')
      'Fulfill Stage'.shouldEqual('Packing')
      'OK'.click()
    'OK'.click()
  'Unfulfilled Sales Orders'.shouldBeCurrentPage()
  'mainTable.0.Include'.shouldntExist()
  'Packing Lists'.click()
    'Select All'.click()
    'mainTable.0.Include'.shouldBeTicked()
    'Select All'.shouldntExist()
    'Select None'.click()
    'Select None'.shouldntExist()
    'Select All'.click()
    'Select All'.shouldntExist()
    'Select None'.shouldExist()
    'mainTable.0.Include'.shouldBeTicked()
    'mainTable.1.Include'.shouldBeTicked()
    'mainTable.0.Include'.toggleTick()
    'mainTable.1.Include'.toggleTick()
    'mainTable.0.Include'.shouldBeUnticked()
    'mainTable.1.Include'.shouldBeUnticked()
    'Select None'.click()
    'Select All'.click()
    'mainTable.1.Fulfill Stage'.shouldEqual('Waiting')
    'Download Packing Lists PDF'.click()
    'mainTable.1.Fulfill Stage'.shouldEqual('Packing')
    'Back'.click()
  'Download Packing Lists PDF'.shouldntExist()
  'mainTable.0.Edit'.click()
    'Fulfill Stage'.shouldEqual('Packing')
    'Lines./Cap (C01)/.Quantity Shipped'.shouldEqual('0')
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('8')
    'Fulfill Stage'.enter('Shipped')
    'Lines./Cap (C01)/.Quantity Shipped'.shouldEqual('8')
    'Lines./Cap (C01)/.Quantity To Pack'.shouldEqual('0')
    'OK'.click()
  'mainTable.1.Edit'.click()
    'Lines.0.Edit'.click()
      'Quantity to Pick'.enter('0')
      'OK'.click() // was generating error re saving with temporary id
    'OK'.click()
  'Back'.click()
