'PO'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter('Acme')
    'GL AP Account (leave empty for default)'.shouldntExist()
    'GL Purchase Expense Account (leave empty for default)'.shouldntExist()
    'OK'.click()
  'Back'.click()
'Inventory'.click()
  'searcher'.enter('Hoodie')
  'mainTable./Hoodie (H01)/.Edit Product'.click()
  'Treat as Expense in GL'.shouldntExist()
  'Back'.click()
'General Ledger'.click()
  'Enable General Ledger'.click()
    'Enable General Ledger'.enter('Yes')
    'OK'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('POTEST')
    'Add Line'.click()
      'Product'.enter('Hoodie (H01)')
      'Unit Price (Inc Tax)'.enter('22.00')
      'Tax %'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable./POTEST/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('22.00')
  'mainTable./Trade Payables/.Balance'.shouldEqual('22.00')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payment Status'.enter('Paid')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('22.00')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'mainTable./Bank/.Balance'.shouldEqual('-22.00')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payment Status'.enter('Unpaid')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Trade Payables/.Balance'.shouldEqual('22.00')
  'mainTable./Bank/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_settings'.click()
  'Supplier Payment Handling'.enter('Multiple Payments Per PO')
  'OK'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payments'.click()
      'Add'.click()
        'Status'.enter('Unpaid')
        'Amount'.enter('10.00')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Trade Payables/.Balance'.shouldEqual('22.00')
  'mainTable./Bank/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payments'.click()
      'mainTable.1.Edit'.click()
        'Status'.enter('Paid')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Trade Payables/.Balance'.shouldEqual('12.00')
  'mainTable./Bank/.Balance'.shouldEqual('-10.00')
  'Back'.click()
'stocktend_receivePurchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Trash'.click()
  'mainTable.0.Really Trash?'.click()
    'messageDialogText'.shouldContain("Cannot trash this purchase order as there is a payment for it", 'doc')
    'OK'.click('doc')
  'mainTable.0.Edit'.click()
    'Payments'.click()
      'mainTable.1.Trash'.click()
      'mainTable.1.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'mainTable.0.Trash'.click()
  'mainTable.0.Really Trash?'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'Back'.click()
'Inventory'.click()
  'searcher'.enter('Hoodie')
  'mainTable./Hoodie (H01)/.Edit Product'.click()
  'Treat as Expense in GL'.enter('Yes')
  'Stock On Hand Account'.shouldntExist()
  'OK'.click()
'stocktend_suppliers'.click()
  'mainTable./Acme/.Edit'.click()
    'GL AP Account (leave empty for default)'.shouldEqual('')
    'GL Purchase Expense Account (leave empty for default)'.shouldEqual('')
    'OK'.click()
  'mainTable./Acme/.Edit'.click()
    'GL AP Account (leave empty for default)'.enter('Other Payables (020104)')
    'GL Purchase Expense Account (leave empty for default)'.enter('Raw Material, Parts And Supplies (010302)')
    'OK'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('POTEST')
    'Supplier'.enter('Acme')
    'Add Line'.click()
      'Product'.enter('Hoodie (H01)')
      'Unit Price (Inc Tax)'.enter('22.00')
      'Tax %'.enter('10')
      'OK'.click()
    'Add Line'.click()
      'Line Type'.enter('Shipping')
      'Unit Price (Inc Tax)'.enter('2.00')
      'Tax %'.enter('10')
      'OK'.click()
    'Add Line'.click()
      'Line Type'.enter('Fee')
      'Unit Price (Inc Tax)'.enter('3.00')
      'Tax %'.enter('10')
      'OK'.click()
    'Add Line'.click()
      'Line Type'.enter('Other')
      'Unit Price (Inc Tax)'.enter('0.50')
      'Tax %'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'mainTable./Other Payables/.Balance'.shouldEqual('')
  'searcher'.enter('raw')
  'mainTable./Raw Material, Parts And Supplies/.Balance'.shouldEqual('')
  'searcher'.enter('ser')
  'mainTable./Services Expense/.YTD Balance'.shouldEqual('')
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable./POTEST/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'mainTable./Other Payables/.Balance'.shouldEqual('27.50')
  'searcher'.enter('raw')
  'mainTable./Raw Material, Parts And Supplies/.Balance'.shouldEqual('22.00')
  'searcher'.enter('ser')
  'mainTable./Services Expense/.YTD Balance'.shouldEqual('5.50')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payments'.click()
      'Add'.click()
        'Amount'.enter('10.00')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Other Payables/.Balance'.shouldEqual('17.50')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payments'.click()
      'mainTable.1.Trash'.click()
      'mainTable.1.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Other Payables/.Balance'.shouldEqual('')
  'searcher'.enter('raw')
  'mainTable./Raw Material, Parts And Supplies/.Balance'.shouldEqual('')
  'searcher'.enter('ser')
  'mainTable./Services Expense/.YTD Balance'.shouldEqual('')
  'Back'.click()
'Inventory'.click()
  'searcher'.enter('Hoodie')
  'mainTable./Hoodie (H01)/.Edit Product'.click()
  'Treat as Expense in GL'.enter('No')
  'Stock On Hand Account'.enter('Other Inventory (010305)')
  'OK'.click()
'stocktend_receivePurchases'.click()
  'mainTable./POTEST/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'searcher'.enter('other')
  'mainTable./Other Inventory/.Balance'.shouldEqual('22.00')
  'Back'.click()
'1'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'General Ledger'.click()
  'mainTable'.shouldHaveCount(0)
  'GL Settings'.shouldntExist()
  'Add Account'.shouldntExist()
  'Journal Entries'.shouldntExist()
  'Profit and Loss'.shouldntExist()
  'Balance Sheet'.shouldntExist()
  'Enable General Ledger'.click()
    'General Ledger Settings'.shouldBeCurrentPage()
    'Enable General Ledger'.shouldEqual('No')
    'Enable General Ledger'.enter('Yes')
    'Calendar Starting Month'.shouldEqual('July')
    'Calendar Starting Month'.enter('August')
    'OK'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'Enable General Ledger'.shouldntExist()
  'GL Settings'.click()
    'Calendar Starting Month'.shouldEqual('August')
    'Calendar Starting Month'.enter('July')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'Profit and Loss'.click()
    'Modify'.click()
      'Modify Statement'.shouldBeCurrentPage()
      'Name'.shouldEqual('Profit and Loss')
      'Lines.0.Sequence'.shouldEqual('100')
      'Lines.0.Caption'.shouldEqual('Income')
      'Add Line'.click()
        'Add Statement Line'.shouldBeCurrentPage()
        'Sequence'.enter('50')
        'Caption'.enter('Test')
        'Ranges'.enter('999-999')
        'DR/CR'.enter('DR')
        'OK'.click()
      'Lines.0.Caption'.shouldEqual('Test')
      'Lines.0.Edit'.click()
        'Edit Statement Line'.shouldBeCurrentPage()
        'Sequence'.enter('101')
        'OK'.click()
      'Lines.1.Caption'.shouldEqual('Test')
      'Lines.1.Trash'.click()
      'Lines.1.Really Trash?'.click()
      'OK'.click()
    'Back'.click()
  'Add Account'.click()
    'Add Account'.shouldBeCurrentPage()
    'Account Code'.enter('01010199')
    'Name'.enter('Bank2')
    'Type'.shouldEqual('Expenditure')
    'Type'.enter('Asset')
    'OK'.click()
  'Journal Entries'.click()
    'Add'.click()
      'Add Line'.click()
        'Account'.enter('Sales - Goods (040101)')
        'Amount'.enter('1000.00')
        'OK'.click()
      'Add Line'.click()
        'Account'.enter('Work In Process (010303)')
        'Amount'.shouldEqual('1000.00')
        'OK'.click()
      'Posted'.shouldEqual('Yes')
      'OK'.click()
    'Back'.click()
  'searcher'.enter('sales')
  'mainTable./Sales - Goods/.YTD Balance'.shouldEqual('1,000.00')
  'searcher'.enter('work')
  'mainTable./Work In Process/.Balance'.shouldEqual('1,000.00')
  'searcher'.enter('sales')
  'Journal Entries'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click() // Note: removing one entry line should set the entry to unposted and therefore reverse effects of both lines
    'Back'.click()
  'searcher'.enter('sales')
  'mainTable./Sales - Goods/.YTD Balance'.shouldEqual('')
  'searcher'.enter('work')
  'mainTable./Work In Process/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('POTEST')
    'Add Line'.click()
      'Product'.enter('Hoodie (H01)')
      'Unit Price (Inc Tax)'.enter('22.00')
      'Tax %'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable./POTEST/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('22.00')
  'Back'.click()
'General Ledger'.click()
  'GL Settings'.click()
    'Calendar Starting Month'.enter('August')
    'OK'.click()
    'stFormRejection'.shouldContain("The starting month cannot be changed as there have been journal entries made")
    'Calendar Starting Month'.enter('July')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Overhead Cost'.enter('2.00')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('2')
    'Unit Price (Inc Tax)'.enter('10.00')
    'Tax %'.enter('10.00')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity'.enter('6')
    'Unit Price (Inc Tax)'.enter('5.00')
    'OK'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('60.00')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('72.00')
  'Back'.click()
'helper'.addWCOrder({product: 'Brag Set (BS01)', quantity: 1, unitPrice: 60, shippingIncTax: 12.50, feesIncTax: 10.00, orderDate: global.todayLocal(), status: 'wc-processing', differentForeman: true})
'General Ledger'.click()
  'searcher'.enter('inv')
  'mainTable./Inventory/.Balance'.shouldEqual('47.00')
  'searcher'.enter('sales')
  'mainTable./Cost Of Sales/.YTD Balance'.shouldEqual('27.00')
  'searcher'.enter('overhead')
  'mainTable./Accrued Overhead/.Balance'.shouldEqual('2.00')
  'searcher'.enter('shipping')
  'mainTable./Shipping Clearing/.Balance'.shouldEqual('12.50')
  'searcher'.enter('fees')
  'mainTable./Fees Clearing/.Balance'.shouldEqual('10.00')
  'searcher'.enter('tax')
  'mainTable./Accrued Taxes (Other Than Payroll)/.Balance'.shouldEqual('3.69') // 5.45 + 1.14 shipping + 0.91 fees - 1.82 adjustment - 2.00 PO Receipt
  'searcher'.enter('sales')
  'mainTable./Sales - Goods/.Account Code'.shouldEqual('040101')
  'mainTable./Sales - Goods/.Type'.shouldEqual('Income')
  'mainTable./Sales - Goods/.Edit'.click()
    'Tax Treatment'.shouldEqual('Taxed')
    'OK'.click()
  'mainTable./Sales - Goods/.YTD Balance'.shouldEqual('82.51')
  'mainTable./Sales - Goods/.Balance'.shouldEqual('')
  'mainTable./Sales - Services/.Account Code'.shouldEqual('040102')
  'searcher'.enter('')
  'mainTable./Cash And Cash Equivalents/.Account Code'.shouldEqual('010101')
  'mainTable./Cash And Cash Equivalents/.Type'.shouldEqual('Asset')
  'mainTable./Bank/.Balance'.shouldEqual('105.01')
  'mainTable./Cash And Cash Equivalents/.Balance'.shouldEqual('')
  'searcher'.enter('sales')
  'mainTable./Sales - Goods/.Edit'.click()
    'Edit Account'.shouldBeCurrentPage()
    'Account Code'.shouldEqual('040101')
    'Name'.shouldEqual('Sales - Goods')
    'Name'.enter('Sales - Products')
    'Type'.shouldEqual('Income')
    'Tax Treatment'.enter('Tax Free')
    'Tax Treatment'.enter('Taxed')
    'YTD Balance'.shouldBeReadOnly()
    'Balance'.shouldntExist()
    'OK'.click()
  'mainTable./Sales - Products/.Account Code'.shouldEqual('040101')
  'searcher'.enter('cash')
  'mainTable./Cash And Cash Equivalents/.Edit'.click()
    'Balance'.shouldBeReadOnly()
    'YTD Balance'.shouldntExist()
    'OK'.click()
  'Journal Entries'.click()
    'Journal Entries'.shouldBeCurrentPage()
    'Add'.click()
      'Add Journal Entry'.shouldBeCurrentPage()
      'Effective Date'.shouldEqualExpression('global.todayLocal()')
      'Effective Date'.enterExpression('global.todayLocal().incDays(-366)')
      'Notes'.enter('Refund')
      'Entry Balance'.shouldEqual('0.00')
      'Entry Balance'.shouldBeReadOnly()
      'Posted'.shouldEqual('No')
      'Posted'.shouldBeReadOnly()
      'Add Line'.click()
        'Add Journal Entry Line'.shouldBeCurrentPage()
        'Account'.enter('Sales - Products (040101)')
        'Account Type'.shouldEqual('Income')
        'Account Type'.shouldBeReadOnly()
        'Amount'.enter('-1000.00')
        'Effect on Ledger'.shouldBeReadOnly()
        'Effect on Ledger'.shouldEqual('1000.00 DR')
        'OK'.click()
      'Entry Balance'.shouldEqual('1,000.00')
      'Add Line'.click()
        'Account'.enter('Bank2 (01010199)')
        'Account Type'.shouldEqual('Asset')
        'Amount'.shouldEqual('-1000.00')
        'Effect on Ledger'.shouldEqual('1000.00 CR')
        'Amount'.enter('124.45')
        'Effect on Ledger'.shouldEqual('124.45 DR')
        'OK'.click()
      'Entry Balance'.shouldEqual('1,124.45')
      'Posted'.shouldEqual('No')
      'OK'.click()
        'messageDialogText'.shouldEqual("WARNING: Journal Entry is out of balance and has not been posted", 'doc')
      'OK'.click()
    'Back'.click()
  'searcher'.enter('Bank2')
  'mainTable./Bank2/.Balance'.shouldEqual('')
  'Journal Entries'.click()
    'mainTable./Bank2 (01010199)/.Edit'.click()
      'Lines./Bank2 (01010199)/.Edit'.click()
        'Edit Journal Entry Line'.shouldBeCurrentPage()
        'Account'.shouldEqual('Bank2 (01010199)')
        'Amount'.enter('-1000.00')
        'Effect on Ledger'.shouldEqual('1000.00 CR')
        'OK'.click()
      'Entry Balance'.shouldEqual('0.00')
      'Posted'.shouldEqual('Yes')
      'Lines'.shouldHaveCount(3) // including total
      'Lines./Sales - Products (040101)/.CR Amount'.shouldEqual('')
      'Lines./Sales - Products (040101)/.DR Amount'.shouldEqual('1,000.00')
      'Lines./Bank2 (01010199)/.CR Amount'.shouldEqual('1,000.00')
      'Lines./Bank2 (01010199)/.DR Amount'.shouldEqual('')
      'OK'.click()
    'Back'.click()
  'searcher'.enter('Bank2')
  'mainTable./Bank2/.Balance'.shouldEqual('-1,000.00')
  'mainTable./Bank2/.YTD Balance'.shouldEqual('')
  'searcher'.enter('sales')
  'mainTable./Sales - Products/.Balance'.shouldEqual('')
  'Back'.click()
'General Ledger'.click()
  'Journal Entries'.click()
    'Add'.click()
      'Effective Date'.enterExpression('global.todayLocal()')
      'Add Line'.click()
        'Account'.enter('Sales - Services (040102)')
        'Amount'.enter('20000')
        'Add another line'.click()
        'Account'.enter('Accounts, Notes And Loans Receivable (010201)')
        'Amount'.enter('20000')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'searcher'.enter('sales')
  'mainTable./Sales - Services/.PTD Balance'.shouldEqual('20,000.00')
  'searcher'.enter('accounts')
  'mainTable./Accounts, Notes And Loans Receivable/.Balance'.shouldEqual('20,000.00')
  'Profit and Loss'.click()
    'Go'.click()
    'mainTable./Income/.PTD'.shouldEqual('20,082.51')
    'mainTable./Income/.YTD'.shouldEqual('20,082.51')
    'mainTable./Cost Of Goods Sold/.YTD'.shouldEqual('27.00')
    'mainTable./GROSS PROFIT/.YTD'.shouldEqual('20,055.51')
    'Back'.click()
  'Balance Sheet'.click()
    'mainTable'.shouldBeEmpty()
    'Go'.click()
    'mainTable./ASSETS/.Balance'.shouldEqual('19,152.01')
    'mainTable./LIABILITIES AND EQUITY/.Balance'.shouldEqual('19,152.01')
    'Statement'.enter('Profit and Loss')
    'mainTable'.shouldBeEmpty()
    'Go'.click()
    'mainTable./GROSS PROFIT/.YTD'.shouldEqual('20,055.51')
  'Back'.click()
'General Ledger'.click()
  'GL Settings'.click()
    'Reset General Ledger'.click()
      'messageDialogText'.shouldEqual("WARNING: This will delete all GL accounts and journals and reset settings to default. Please do a backup before proceeding. Are you sure?", 'doc')
      'Yes'.click('doc')
    'Enable General Ledger'.shouldEqual('No')
    'OK'.click()
  'mainTable'.shouldHaveCount(0)
  'Enable General Ledger'.click()
    'Enable General Ledger'.enter('Yes')
    'Calendar Starting Month'.shouldEqual('July')
    'OK'.click()
  'Balance Sheet'.click()
    'mainTable'.shouldBeEmpty()
    'Go'.click()
    'mainTable./ASSETS/.Balance'.shouldEqual('0.00')
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('POTEST2')
    'Add Line'.click()
      'Product'.enter('Hoodie (H01)')
      'Unit Price (Inc Tax)'.enter('22.00')
      'Tax %'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable./POTEST2/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('22.00')
  'mainTable./Trade Payables/.Balance'.shouldEqual('22.00')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'mainTable.0.Edit'.click()
    'Payment Status'.enter('Paid')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Inventory/.Balance'.shouldEqual('22.00')
  'mainTable./Trade Payables/.Balance'.shouldEqual('')
  'mainTable./Bank/.Balance'.shouldEqual('-22.00')
  'Back'.click()
'AR'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'General Ledger'.click()
  'Enable General Ledger'.click()
    'Enable General Ledger'.enter('Yes')
    'OK'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Bank/.Balance'.shouldEqual('')
  'mainTable./Accounts, Notes And Loans Receivable/.Balance'.shouldEqual('')
  'Back'.click()
'stocktend_customers'.click()
  'Add'.click()
    'Name'.enter('Fred Smith')
    'Password'.enter('secret')
    'Login'.enter('prfi_fred')
    'OK'.click()
  'mainTable./Fred Smith/.Account'.click()
    'Add Entry'.click()
      'AR Entry Number'.enter('INV01')
      'Entry Type'.enter('Invoice')
      'Amount'.enter('100.00')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Bank/.Balance'.shouldEqual('-100.00')
  'mainTable./Accounts, Notes And Loans Receivable/.Balance'.shouldEqual('100.00')
  'Back'.click()
'stocktend_customers'.click()
  'mainTable./Fred Smith/.Account'.click()
    'mainTable./INV01/.Edit'.click()
      'Enter Payment'.click()
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'General Ledger'.click()
  'mainTable./Bank/.Balance'.shouldEqual('')
  'mainTable./Accounts, Notes And Loans Receivable/.Balance'.shouldEqual('')
  'Back'.click()
