'1'.chapter()
'helper'.clearWCStockLevels()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Weeks of Prior Sales to use for Sales Analysis'.enter('1000')
  'Date To Use For Profit Reporting'.enter('Order Date')
  'Consolidation'.click()
    'Consolidation Settings'.shouldBeCurrentPage()
    'Add Constituent Site'.click()
      'Add Constituent Site'.shouldBeCurrentPage()
      'OK'.click()
      'stFormRejection'.shouldContain('URL is required')
      'URL'.enter('http://c1.tocsv.com')
      'OK'.click()
      'stFormRejection'.shouldContain('Consumer Key is required')
      'Consumer Key'.enter('ck_579b5b2f9c9c3c276fadf6e98e3d361dbc23fdfc')
      'OK'.click()
      'stFormRejection'.shouldContain('Consumer Secret is required')
      'Consumer Secret'.enter('cs_17db8d5bd05192f4fd28862d84559d61c20b7440')
      'OK'.click()
      'stFormRejection'.shouldContain('You must enter a Site Name')
      'Site Name'.enter('Constituent C1')
      'OK'.click()
      'stFormRejection'.shouldContain('Url must start with https://')
      'URL'.enter('https://c1.tocsv.com')
      'OK'.click()
    'Sites'.shouldHaveCount(1)
    'Add Constituent Site'.click()
      'Site Name'.enter('Constituent C2')
      'URL'.enter('https://c2.tocsv.com')
      'Consumer Key'.enter('ck_bfa73dc4dbc49020481f4764ae0b2529ae930443')
      'Consumer Secret'.enter('cs_be542ab1ed7608143e70d255b0a968c8f033b68f')
      'OK'.click()
    'Back'.click()
  'OK'.click()
'stocktend_settings'.click()
  'Short Date Format'.enter('dd/mm/yyyy')
  'OK'.click()
'stocktend_purchaseOrders'.click()
  'helper'.trashAll('Transaction')
  'Add'.click()
    'Purchase Order Number'.enter('PO00001')
    'Order Date'.enter('28/4/2019')
    'Add Line'.click()
      'Product'.chooseOption('Shórts - Blue (SB01)')
      'Unit Price (Inc Tax)'.enter('5.00')
      'Quantity'.enter('4')
      'OK'.click()
    'OK'.click()
  'Add'.click()
  'Purchase Order Number'.enter('PO00002')
  'Order Date'.enter('28/5/2019')
  'Add Line'.click()
    'Product'.chooseOption('Shórts - Blue (SB01)')
    'Unit Price (Inc Tax)'.enter('4.78')
    'Quantity'.enter('8')
    'OK'.click()
  'OK'.click()
'Receive Purchases'.click()
  'mainTable./PO00001/.Enter Receipt'.click()
    'Received Date'.enter('28/4/2019')
    'OK'.click()
  'mainTable./PO00002/.Enter Receipt'.click()
    'Received Date'.enter('28/5/2019')
    'OK'.click()
  'Back'.click()
'helper'.clearWCOrders()
'View Profits'.click()
  'mainTable'.shouldBeEmpty()
  'From Date'.enter('1/7/2019')
  'To Date'.enter('30/6/2099')
  'Go'.click()
  'searcher'.enter('s')
  'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('0.00')
  'Back'.click()
'helper'.addWCOrder({product: 'Shórts - Blue (SB01)', quantity: 1, unitPrice: 10.00, orderDate: '28/6/2019'})
'helper'.flushCache()
'Sales and Invoices'.click()
  'mainTable.0.Product'.shouldEqual('Shórts - Blue (SB01)')
  'mainTable.0.Amount Ex Tax'.shouldEqual('9.09')
  'mainTable.0.Quantity'.shouldEqual('1')
  'mainTable.0.View Order'.click()
    'View Sales Order'.shouldBeCurrentPage()
    'Order Number'.shouldntEqual('')
    'Order Date'.shouldEqual('Jun 28 2019')
    'productsTotalExTax'.shouldEqual('9.09')
    'Tax'.shouldEqual('0.91')
    'Shipping'.shouldEqual('0.00')
    'Total'.shouldContain('10.00')
    'Lines'.shouldHaveCount(1)
    'Lines.0.Description'.shouldEqual('Shórts - Blue')
    'Lines.0.Unit Price'.shouldEqual('9.09')
    'Lines.0.Quantity'.shouldEqual('1')
    'Lines.0.Amount'.shouldEqual('9.09')
    'Lines.0.Tax'.shouldEqual('0.91')
    'Lines.0.Amount Inc Tax'.shouldEqual('10.00')
    'Download Invoice PDF'.click()
    'browser'.back()
'helper'.clearWCOrders()
'helper'.flushCache()
'View Profits'.click()
  'From Date'.enter('1/7/2019')
  'To Date'.enter('30/6/2020')
  'Go'.click()
  'searcher'.enter('s')
  'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('0.00')
  'browser'.back()
'helper'.addWCOrder({product: 'Shórts - Blue (SB01)', quantity: 2, unitPrice: 9.50, orderDate: '1/7/2019'})
'View Profits'.click()
  'From Date'.shouldEqual('01/07/2019')
  'To Date'.shouldEqual('30/06/2020')
  'searcher'.enter('Blue')
  'Go'.click()
  'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('19.00')
  'mainTable./Shórts - Blue (SB01)/.Cost of Goods Sold'.shouldEqual('9.71')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit Value'.shouldEqual('9.29')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit %'.shouldEqual('48.91')
  'helper'.addWCOrder({product: 'Shórts - Blue (SB01)', quantity: 3, unitPrice: 9.25, orderDate: '1/8/2019'})
  'Go'.click()
  'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('46.75')
  'mainTable./Shórts - Blue (SB01)/.Cost of Goods Sold'.shouldEqual('24.27')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit Value'.shouldEqual('22.48')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit %'.shouldEqual('48.09')
  'helper'.addWCOrder({product: 'Shórts - Blue (SB01)', quantity: 1, unitPrice: 9.00, orderDate: '1/7/2020'}) // NOTE: not in the selected date range
  'Go'.click()
  'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('46.75')
  'mainTable./Shórts - Blue (SB01)/.Cost of Goods Sold'.shouldEqual('24.27')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit Value'.shouldEqual('22.48')
  'mainTable./Shórts - Blue (SB01)/.Gross Profit %'.shouldEqual('48.09')
  'helper'.addWCOrder({product: 'Polo (P01)', quantity: 1, unitPrice: 20.00, orderDate: '1/7/2019'})
  'Go'.click()
  'searcher'.enter('')
  'mainTable./Polo (P01)/.Sales Value'.shouldEqual('20.00')
  'mainTable./Polo (P01)/.Cost of Goods Sold'.shouldEqual('Unknown')
  'mainTable./Polo (P01)/.Gross Profit Value'.shouldEqual('Unknown')
  'mainTable./Polo (P01)/.Gross Profit %'.shouldEqual('Unknown')
  'Consolidated Profits'.click()
    'Consolidation Settings'.click()
      'Sites'.shouldHaveCount(2)
      'Back'.click()
    'From Date'.shouldEqual('01/07/2019')
    'To Date'.shouldEqual('30/06/2020')
    'Sites'.shouldEqual('This site + Constituent C1 + Constituent C2')
    'Sites'.shouldBeReadOnly()
    'Go'.click()
    'searcher'.enter('Blue')
    'mainTable./Shórts - Blue (SB01)/.Sales Quantity'.shouldEqual('7')
    'mainTable./Shórts - Blue (SB01)/.Sales Value'.shouldEqual('67.50')
    'mainTable./Shórts - Blue (SB01)/.Cost of Goods Sold'.shouldEqual('34.27')
    'mainTable./Shórts - Blue (SB01)/.Gross Profit Value'.shouldEqual('33.23')
    'mainTable./Shórts - Blue (SB01)/.Gross Profit %'.shouldEqual('49.23')
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00003')
    'Order Date'.enter('2/7/2019')
    'Add Line'.click()
      'Product'.chooseOption('Polo (P01)')
      'Unit Price (Inc Tax)'.enter('23.00')
      'Quantity'.enter('1')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable./PO00003/.Enter Receipt'.click()
    'Received Date'.enter('2/7/2019')
    'OK'.click()
  'Back'.click()
'View Profits'.click()
  'Go'.click()
  'mainTable./Polo (P01)/.Sales Value'.shouldEqual('20.00')
  'mainTable./Polo (P01)/.Cost of Goods Sold'.shouldEqual('23.00')
  'mainTable./Polo (P01)/.Gross Profit Value'.shouldEqual('-3.00')
  'mainTable./Polo (P01)/.Gross Profit %'.shouldEqual('-15.00')
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO00004')
    'Order Date'.enter('20/8/2019')
    'Add Line'.click()
      'Product'.chooseOption('Polo (P01)')
      'Unit Price (Inc Tax)'.enter('11.00')
      'Quantity'.enter('6')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable./PO00004/.Enter Receipt'.click()
    'Received Date'.enter('20/8/2019')
    'OK'.click()
  'Back'.click()
'helper'.addWCOrder({product: 'Polo (P01)', quantity: 2, unitPrice: 17.65, orderDate: '20/9/2019'})
'View Profits'.click()
  'Go'.click()
  'mainTable./Polo (P01)/.Sales Value'.shouldEqual('55.30')
  'mainTable./Polo (P01)/.Cost of Goods Sold'.shouldEqual('45.00')
  'mainTable./Polo (P01)/.Gross Profit Value'.shouldEqual('10.30')
  'mainTable./Polo (P01)/.Gross Profit %'.shouldEqual('18.63')
  'Back'.click()
'helper'.addWCOrder({product: 'Polo (P01)', quantity: 3, unitPrice: 19.23, orderDate: '2/3/2020'})
'View Profits'.click()
  'Go'.click()
  'mainTable./Polo (P01)/.Sales Value'.shouldEqual('113.00')
  'mainTable./Polo (P01)/.Cost of Goods Sold'.shouldEqual('78.00')
  'mainTable./Polo (P01)/.Gross Profit Value'.shouldEqual('35.00')
  'mainTable./Polo (P01)/.Gross Profit %'.shouldEqual('30.97')
  'helper'.addWCOrder({product: 'Polo (P01)', quantity: 1, unitPrice: 9.00, orderDate: '1/7/2020'})
  'Back'.click()
'View Profits'.click()
  'Go'.click()
  'mainTable./Polo (P01)/.Sales Value'.shouldEqual('113.00')
  'mainTable./Polo (P01)/.Cost of Goods Sold'.shouldEqual('78.00')
  'mainTable./Polo (P01)/.Gross Profit Value'.shouldEqual('35.00')
  'mainTable./Polo (P01)/.Gross Profit %'.shouldEqual('30.97')
  'Back'.click()
'helper'.setWCStockLevel('Hoodie with Pocket (HP01)', 10)
'helper'.flushCache()
'Inventory'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Quantity On Hand'.shouldEqual('10')
  'mainTable./Hoodie with Pocket (HP01)/.Product'.click()
    'Adjust Value'.click()
      'Avg Unit Cost'.enter('33.00')
      'OK'.click()
    'OK'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Avg Unit Cost'.shouldEqual('33.00')
  'mainTable./Hoodie with Pocket (HP01)/.Inventory Value'.shouldEqual('330.00')
  'Back'.click()
'helper'.addWCOrder({product: 'Hoodie with Pocket (HP01)', quantity: 1, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-pending"})
'View Profits'.click()
  'From Date'.enter('1/7/2019')
  'To Date'.enter('30/6/2020')
  'Go'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Sales Value'.shouldEqual('50.00')
  'mainTable./Hoodie with Pocket (HP01)/.Cost of Goods Sold'.shouldEqual('33.00')
  'mainTable./Hoodie with Pocket (HP01)/.Gross Profit Value'.shouldEqual('17.00')
  'Back'.click()
'Inventory'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Quantity On Hand'.shouldEqual('10')
  'mainTable./Hoodie with Pocket (HP01)/.Inventory Value'.shouldEqual('330.00')
  'browser'.back()
'helper'.flushCache()
'Inventory'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Inventory Value'.shouldEqual('330.00')
  'Back'.click()
'Receive Purchases'.click()
  'mainTable'.shouldBeEmpty()
  'View All Receipts'.click()
    'mainTable./PO00004-01/.Trash'.click()
    'mainTable./PO00004-01/.Really Trash?'.click()
    'Back'.click()
  'Receive Purchases'.shouldBeCurrentPage()
  'mainTable'.shouldHaveCount(2) // Including total
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable.<columnHeadings>.Order Number'.click()
  'mainTable.0.Product'.shouldEqual('Shórts - Blue (SB01)')
  'mainTable.<columnHeadings>.Order Number'.click()
  'mainTable.0.Product'.shouldEqual('Hoodie with Pocket (HP01)')
  'Back'.click()
'PackagingReport'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'helper'.addWCOrder({product: 'Brag Set (BS01)', quantity: 20, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-pending"})
'helper'.addWCOrder({product: 'Brag Set (BS01)', quantity: 20, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-processing"})
'helper'.addWCOrder({product: 'Brag Set (BS01)', quantity: 20, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-complete"})
'helper'.addWCOrder({product: 'Tag (TA01)', quantity: 20, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-processing"})
'helper'.addWCOrder({product: 'Tag Outer (TO01)', quantity: 20, unitPrice: 50.00, orderDate: '28/6/2020', status: "wc-processing"})
'helper'.addWCOrder({product: 'Cap (C01)', quantity: 20, unitPrice: 50.00, orderDate: '28/5/2020', status: "wc-processing"})
'stocktend_fulfillment'.click()
  'mainTable.5.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'mainTable.4.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'mainTable.3.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'mainTable.2.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'mainTable.1.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'mainTable.0.Edit'.click()
    'Lines.0.Quantity Shipped'.enter('20')
    'OK'.click()
  'Back'.click()
'stocktend_fulfillment'.click()
  'View Shipments'.click()
    'mainTable.0.Edit'.click()
      'Shipment Date'.enter('28/6/2020')
      'OK'.click()
    'mainTable.1.Edit'.click()
      'Shipment Date'.enter('28/6/2020')
      'OK'.click()
    'mainTable.2.Edit'.click()
      'Shipment Date'.enter('28/6/2020')
      'OK'.click()
    'mainTable.3.Edit'.click()
      'Shipment Date'.enter('28/6/2020')
      'OK'.click()
    'mainTable.4.Edit'.click()
      'Shipment Date'.enter('28/6/2020')
      'OK'.click()
    'mainTable.5.Edit'.click()
      'Shipment Date'.enter('28/5/2020')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('3')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Bundle Product'.enter('Tag (TA01)')
      'Add Component'.click()
        'Component Product'.enter('Tag Outer (TO01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag Label (TL01)')
        'Quantity'.enter('2')
        'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_reports'.click()
  'mainTable./Packaging Used In Shipped Goods Report/.Run'.click()
    'Packaging Used In Shipped Goods Report'.shouldBeCurrentPage()
    'From Date'.enter('01/06/2020')
    'To Date'.enter('01/07/2020')
    'Go'.click()
    'mainTable'.shouldHaveCount(9)
    'Include Categories (comma-separated, or blank for all)'.enter('Paper,Plastic')
    'Go'.click()
    'mainTable'.shouldHaveCount(4)
    'Include Categories (comma-separated, or blank for all)'.enter('')
    'From Date'.enter('01/05/2020')
    'Go'.click()
    'mainTable'.shouldHaveCount(10)
    'Back'.click()
  'Back'.click()
