'Scheduling'.chapter()
'helper'.trashAll('*')
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Units of Measure'.click()
    'Add'.click()
      'Unit of Measure Name'.enter('Cut')
      'OK'.click()
    'Add'.click()
      'Unit of Measure Name'.enter('Each')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Stocking and Sales UOM'.enter('Each')
    'OK'.click()
  'Back'.click()
'Work Orders'.click()
  'Processes'.click()
    'Add'.click()
      'Add Process'.shouldBeCurrentPage()
      'Process Name'.enter('Wash')
      'Add another'.click()
      'Process Name'.enter('Slice')
      'Add another'.click()
      'Process Name'.enter('Pack')
      'Add another'.click()
      'Process Name'.enter('Sanitize')
      'Add another'.click()
      'Process Name'.enter('Dice')
      'Add another'.click()
      'Process Name'.enter('Repack')
      'OK'.click()
    'mainTable'.shouldHaveCount(6)
    'Back'.click()
  'Work Stations'.click()
    'Groups'.click()
      'Work Station Groups'.shouldBeCurrentPage()
      'Add'.click()
        'Add Work Station Group'.shouldBeCurrentPage()
        'Group Name'.enter('Processing Room')
        'Add another'.click()
        'Group Name'.enter('Warehouse')
        'OK'.click()
      'mainTable'.shouldHaveCount(2)
      'Back'.click()
    'Add'.click()
      'Add Work Station'.shouldBeCurrentPage()
      'Work Station Code'.enter('E0001')
      'Work Station Name'.enter('Wash Room 1')
      'Group'.clickDropdown()
      'Group'.shouldHaveNOptions(3)
      'Group'.enter('Processing Room')
      'Add Process'.click()
        'Add Supported Process'.shouldBeCurrentPage()
        'Process'.clickDropdown()
        'Process'.shouldHaveNOptions(7)
        'Process'.enter('Wash')
        'Hourly Output'.enter('10')
        'Unit of Measure'.enter('Cut')
        'Add another'.click()
        'Process'.enter('Sanitize')
        'Hourly Output'.enter('5')
        'Unit of Measure'.enter('Cut')
        'OK'.click()
      'Supported Processes'.shouldHaveCount(2)
      'Supported Processes./Wash/.Process'.shouldEqual('Wash')
      'Operating Hours'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(1)')
          'OK'.click()
          'stFormRejection'.shouldContain("Start Time is required")
          'Finish Time'.enter('09:00')
          'Start Time'.enter('xx')
          'OK'.click()
          'stFormRejection'.shouldContain("Invalid Start Time")
          'Start Time'.enter('06:00')
          'Finish Time'.enter('')
          'OK'.click()
          'stFormRejection'.shouldContain("Finish Time is required")
          'Finish Time'.enter('09:00')
          'OK'.click()
        'Operating Hours.0.Start Time'.shouldEqual('06:00')
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(2)')
          'Finish Time'.enter('10:30')
          'Start Time'.enter('25:00')
          'OK'.click()
          'stFormRejection'.shouldContain("Invalid Start Time")
          'Start Time'.enter('xx:00')
          'OK'.click()
          'stFormRejection'.shouldContain("Invalid Start Time")
          'Start Time'.enter('06:30')
          'Finish Time'.enter('xx:00')
          'OK'.click()
          'stFormRejection'.shouldContain("Invalid Finish Time")
          'Finish Time'.enter('10:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(3)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(4)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(5)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Add Work Station'.shouldBeCurrentPage()
      'Work Station Code'.enter('E0002')
      'Work Station Name'.enter('Wash Room 2')
      'Group'.enter('Processing Room')
      'Add Process'.click()
        'Process'.enter('Wash')
        'Hourly Output'.enter('10')
        'Unit of Measure'.enter('Cut')
        'Add another'.click()
        'Process'.enter('Sanitize')
        'Hourly Output'.enter('5')
        'Unit of Measure'.enter('Cut')
        'OK'.click()
      'Operating Hours'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal()')
          'OK'.click()
          'stFormRejection'.shouldContain("Start Time is required")
          'Start Time'.enter('06:00')
          'OK'.click()
          'stFormRejection'.shouldContain("Finish Time is required")
          'Finish Time'.enter('09:00')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(2)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('10:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(3)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(4)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(5)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Add Work Station'.shouldBeCurrentPage()
      'Work Station Code'.enter('E0003')
      'Work Station Name'.enter('Food Dicer 1')
      'Group'.enter('Processing Room')
      'Add Process'.click()
        'Process'.enter('Dice')
        'Hourly Output'.enter('8')
        'Unit of Measure'.enter('Cut')
        'OK'.click()
      'Operating Hours'.click()
        'Work Station Operating Hours'.shouldBeCurrentPage()
        'Work Station Name'.shouldEqual('Food Dicer 1')
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(1)')
          'OK'.click()
          'stFormRejection'.shouldContain("Start Time is required")
          'Start Time'.enter('06:00')
          'OK'.click()
          'stFormRejection'.shouldContain("Finish Time is required")
          'Finish Time'.enter('09:00')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(2)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('10:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(7)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(14)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(15)')
          'Start Time'.enter('06:30')
          'Finish Time'.enter('14:30')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Add Work Station'.shouldBeCurrentPage()
      'Work Station Code'.enter('E0004')
      'Work Station Name'.enter('Food Slicer')
      'Group'.enter('Processing Room')
      'Add Process'.click()
        'Process'.enter('Slice')
        'OK'.click()
      'Operating Hours'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(1)')
          'Start Time'.enter('07:00')
          'Finish Time'.enter('10:00')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(2)')
          'Start Time'.enter('07:30')
          'Finish Time'.enter('11:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(7)')
          'Start Time'.enter('07:30')
          'Finish Time'.enter('15:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(14)')
          'Start Time'.enter('07:30')
          'Finish Time'.enter('15:30')
          'OK'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(15)')
          'Start Time'.enter('07:30')
          'Finish Time'.enter('15:30')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Add Work Station'.shouldBeCurrentPage()
      'Work Station Code'.enter('E0005')
      'Work Station Name'.enter('Packing 2')
      'Group'.enter('Warehouse')
      'OK'.click()
    'Back'.click()
  'Assemblies'.click()
    'Add'.click()
      'Assembly Product'.enter('Brag Set (BS01)')
      'Finished Goods Quantity'.enter('100')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Finished Goods Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Finished Goods Quantity'.enter('3')
        'OK'.click()
      'Processes'.click()
        'Assembly Processes'.shouldBeCurrentPage()
        'Add Process'.click()
          'Sequence'.shouldEqual('10')
          'Process'.enter('Wash')
          'Process Quantity'.enter('500')
          'Unit of Measure'.shouldEqual('Each')
          'Unit of Measure'.shouldBeReadOnly()
          'Process Notes'.enter('Wash raw products for 12 minutes then sanitize')
          'Add another'.click()
          'Sequence'.shouldEqual('20')
          'Process'.enter('Dice')
          'Process Quantity'.enter('240')
          'Unit of Measure'.shouldEqual('Each')
          'Add another'.click()
          'Process'.enter('Pack')
          'Sequence'.shouldEqual('30')
          'Process Quantity'.enter('50')
          'Unit of Measure'.shouldEqual('Each')
          'OK'.click()
        'Processes.1.Sequence'.shouldEqual('20')
        'Processes.1.Edit'.click()
          'Sequence'.enter('5')
          'OK'.click()
        'Processes.0.Sequence'.shouldEqual('5')
        'Processes.1.Sequence'.shouldEqual('10')
        'Processes.0.Edit'.click()
          'Sequence'.enter('20')
          'OK'.click()
        'Processes.1.Sequence'.shouldEqual('20')
        'Back'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('15')
    'Schedule'.shouldntExist()
    'Generate Lines'.click()
    'Schedule'.click()
      'Work Order Schedule'.shouldBeCurrentPage()
      'Work Order Number'.shouldEqual('WO00001')
      'Processes'.shouldHaveCount(3)
      'Processes./Wash/.Process Quantity'.shouldEqual('500')
      'Processes./Wash/.Unit of Measure'.shouldEqual('Each')
      'Back'.click()
    'OK'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00002')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('10')
    'Generate Lines'.click()
    'OK'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00003')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('10')
    'Generate Lines'.click()
    'OK'.click()
  'Back'.click()
'Plan and Schedule'.click()
  'Blocks'.click()
    'Add'.click()
      'Station'.enter('E0001')
      'Date'.enterExpression('global.todayLocal().incDays(1)')
      'Reason'.enter('Cleaning')
      'Start Time'.enter('07:00')
      'Finish Time'.enter('08:00')
      'OK'.click()
    'Add'.click()
      'Station'.enter('E0001')
      'Date'.enterExpression('global.todayLocal().incDays(1)')
      'Reason'.enter('Cleaning')
      'Start Time'.enter('15:00')
      'Finish Time'.enter('17:00')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Work Stations'.click()
    'mainTable./E0001/.Edit'.click()
      'Operating Hours'.click()
        'Add'.click()
          'Date'.enterExpression('global.todayLocal().incDays(1)')
          'Start Time'.enter('13:00')
          'Finish Time'.enter('20:00')
          'OK'.click()
        'Back'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'CopyDay'.chapter()
'Plan and Schedule'.click()
  'Copy Day'.click()
    'Copy From Date'.shouldEqualExpression('global.todayLocal()')
    'Copy To Date'.shouldEqual('')
    'Copy Now'.click()
      'messageDialogText'.shouldContain("Please enter a Copy To Date", 'doc')
      'OK'.click('doc')
    'Copy From Date'.enterExpression('global.todayLocal().incDays(1)')
    'Copy To Date'.enterExpression('global.todayLocal().incDays(3)')
    'Copy Now'.click()
    'messageDialogText'.shouldContain("Copy completed successfully", 'doc')
    'OK'.click('doc')
  'Schedule Master'.shouldBeCurrentPage()
  'Daily Worksheet'.click()
    'Worksheet Date'.enterExpression('global.todayLocal().incDays(1)')
    'Go'.click()
    'mainTable'.shouldHaveCount(4)
    'mainTable./WO00003/.SKU'.shouldEqual('BS01')
    'Worksheet Date'.enterExpression('global.todayLocal().incDays(3)')
    'Go'.click()
    'mainTable'.shouldHaveCount(4)
    'mainTable./WO00006/.SKU'.shouldEqual('BS01')
    'Back'.click()
  'Back'.click()
'DailyWorksheet'.chapter()
'Plan and Schedule'.click()
  'Daily Worksheet'.click()
    'Worksheet Date'.shouldEqualExpression('global.todayLocal()')
    'Download PDF'.click()
    'Back'.click()
  'Back'.click()
'MFG1'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.simulateBrowserRefresh()
'stocktend_inventory'.click()
  'Customize'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityBeingManufactured')
      'Caption'.enter('Quantity Being Manufactured')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityOnWOLines')
      'Caption'.enter('Quantity On WO Lines')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.lastWOReceiptCostExclTax')
      'Caption'.enter('Last Cost')
      'OK'.click()
    'Back'.click()
  'mainTable./Little Bag (LB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Brag Set (BS01)/.Adjust Qty'.click()
    'Quantity'.enter('1')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('10')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity'.enter('30')
    'Add Lot'.click()
      'Lot Number'.enter('CLOT01')
      'Quantity'.enter('10')
      'Expiry Date'.enter('1/1/2020')
      'OK'.click()
    'Add Lot'.click()
      'Lot Number'.enter('CLOT01')
      'Quantity'.enter('20')
      'Expiry Date'.enter('1/1/2019')
      'OK'.click()
      'stFormRejection'.shouldContain("Duplicate Lot Number: has already been specified on this document")
      'Lot Number'.enter('CLOT02')
      'OK'.click()
    'OK'.click()
  'searcher'.enter('tag')
  'mainTable./Tag (TA01)/.Adjust Qty'.click()
    'Quantity'.enter('1000')
    'Unit Price (Inc Tax)'.enter('0.05')
    'OK'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Enable Unbundling when Receiving POs'.shouldntExist()
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO1')
    'Add Line'.click()
      'Product'.enter('Brag Set (BS01)')
      'Quantity'.enter('2')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'Lines./Brag Set (BS01)/.Unbundle'.shouldntExist()
    'Lines./Brag Set (BS01)/.Edit'.click()
      'Unbundle'.shouldntExist()
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Enable Unbundling When Receiving POs'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'Bundles'.click()
    'mainTable./Brag Set (BS01)/.Edit'.click()
      'Unbundle When Receiving on PO'.enter('Yes')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable./PO1/.Enter Receipt'.click()
    'Lines./Brag Set (BS01)/.Unbundle'.shouldEqual('Yes')
    'Lines./Brag Set (BS01)/.Edit'.click()
      'Unbundle'.shouldEqual('Yes')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1') // no change
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('12')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('36')
  'Back'.click()
'Receive Purchases'.click()
  'View All Receipts'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('10')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'Back'.click()
'stocktend_settings'.click()
  'Enable Unbundling When Receiving POs'.enter('No')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity Change'.enter('-1')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('29')
  'Back'.click()
'stocktend_settings'.click()
  'Prevent Negative Stock When Entering Orders In Profitori'.enter('Yes')
  'OK'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('10')
    'Generate Lines'.click()
      'messageDialogText'.shouldEqual('Not enough quantity on hand of Little Bag (LB01)', 'doc')
      'messageDialogOK'.click('doc')
    'Finished Goods Quantity'.enter('9')
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(3)
    'OK'.click()
  'mainTable.0.Trash'.click()
  'mainTable.0.Really Trash?'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Prevent Negative Stock When Entering Orders In Profitori'.enter('No')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity Change'.enter('1')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('10')
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(3)
    'Lines./Little Bag (LB01)/.Edit'.click()
      'Edit Work Order Line'.shouldBeCurrentPage()
      'Product'.shouldEqual('Little Bag (LB01)')
      'Quantity'.shouldEqual('30')
      'Lots.0.Number'.shouldEqual('CLOT02')
      'Lots.0.Quantity'.shouldEqual('20')
      'Lots.1.Number'.shouldEqual('CLOT01')
      'Lots.1.Quantity'.shouldEqual('10')
      //'Add Lot'.click(); 'Lot Number'.enter('CLOT01'); 'Quantity'.enter('10'); 'OK'.click(); 'Add Lot'.click(); 'Lot Number'.enter('CLOT02'); 'Quantity'.enter('20'); 'OK'.click();
      'Lots'.shouldHaveCount(2)
      'Lots./CLOT01/.Quantity'.shouldEqual('10')
      'OK'.click()
    'stocktend_inventory'.click()
      'mainTable./Little Bag (LB01)/.View Serial/Lots'.click()
        'mainTable./CLOT01/.Quantity On WO Lines'.shouldEqual('-10')
        'mainTable./CLOT02/.Quantity On WO Lines'.shouldEqual('-20')
        'Back'.click()
      'Back'.click()
    'OK'.click()
  'mainTable./WO00001/.Edit'.click()
    'Lines'.shouldHaveCount(3)
    'Lines./Little Bag (LB01)/.Line Qty'.shouldEqual('30')
    'Lines./Little Bag (LB01)/.Edit'.click()
      'Edit Work Order Line'.shouldBeCurrentPage()
      'Work Order'.shouldEqual('WO00001')
      'Product'.shouldEqual('Little Bag (LB01)')
      'Quantity'.shouldEqual('30')
      'Lots'.shouldHaveCount(2)
      'Lots./CLOT01/.Quantity'.shouldEqual('10')
      'Lots./CLOT02/.Quantity'.shouldEqual('20')
      'Add Lot'.click()
        'Lot Number'.enter('CLOT03')
        'Quantity'.enter('1')
        'OK'.click()
      'Lots./CLOT03/.Quantity'.shouldEqual('1')
      'Lots./CLOT02/.Edit'.click()
        'Quantity'.enter('19')
        'OK'.click()
      'Lots./CLOT03/.Quantity'.shouldEqual('1')
      'OK'.click()
    'Lines./Little Bag (LB01)/.Edit'.click()
      'Lots./CLOT03/.Quantity'.shouldEqual('1')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'mainTable./Little Bag (LB01)/.View Serial/Lots'.click()
    'mainTable./CLOT03/.Quantity On WO Lines'.shouldEqual('-1')
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO00001/.Enter Receipt'.click()
      'Received Quantity'.enter('4')
      'Cancelled Quantity'.shouldEqual('6')
      'Cancelled Quantity'.enter('1')
      'Received Quantity'.shouldEqual('9')
      'Received Quantity'.enter('10')
      'OK'.click()
    'Back'.click()
  'mainTable./WO00001/.Status'.shouldEqual('Completed')
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('11')
  'mainTable./Brag Set (BS01)/.Last Cost'.shouldEqual('0.50')
  'searcher'.enter('LB01')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Little Bag (LB01)/.View Serial/Lots'.click()
    'mainTable./CLOT01/'.shouldntExist() // now zero
    'mainTable./CLOT02/.Quantity On WO Lines'.shouldEqual('0')
    'mainTable./CLOT02/.Quantity On Hand'.shouldEqual('1')
    'mainTable./CLOT03/.Quantity On WO Lines'.shouldEqual('0')
    'mainTable./CLOT03/.Quantity On Hand'.shouldEqual('-1')
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('0.01')
    'OK'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Use Markup Pricing'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Use Markup Pricing'.enter('Yes')
    'Base Markup On'.enter('Last Cost')
    'Markup %'.enter('150')
    'OK'.click()
  'Back'.click()
'helper'.addWCOrder({customer: 'Fester Inc (kevin.costly)', product: 'Brag Set (BS01)', quantity: 100, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Brag Set/.Edit'.click()
        'Unit Price (Excl Tax)'.shouldEqual('1.25')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable.0.Trash'.click()
      'mainTable.0.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'mainTable./Little Bag (LB01)/.View Serial/Lots'.click()
    'mainTable./CLOT01/.Quantity On WO Lines'.shouldEqual('-10')
    'mainTable./CLOT01/.Quantity On Hand'.shouldEqual('10')
    'mainTable./CLOT02/.Quantity On WO Lines'.shouldEqual('-19')
    'mainTable./CLOT02/.Quantity On Hand'.shouldEqual('20')
    'mainTable./CLOT03/.Quantity On WO Lines'.shouldEqual('-1')
    'mainTable./CLOT03/.Quantity On Hand'.shouldEqual('0')
    'Back'.click()
  'Back'.click()
'MFG2'.chapter()
'helper'.trashAll('*')
'helper'.clearWCOrders()
'helper'.clearWCStockLevels()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Default Tax %'.enter('10')
  'OK'.click()
'stocktend_locations'.click()
  'Add'.click()
    'Location Name'.enter('FG01')
    'OK'.click()
  'Add'.click()
    'Location Name'.enter('Raw Materials')
    'OK'.click()
  'Add'.click()
    'Location Name'.enter('Subassemblies')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'Customize'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityBeingManufactured')
      'Caption'.enter('Quantity Being Manufactured')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Add Field'.click()
      'Get Value From'.enter('Inventory.quantityOnWOLines')
      'Caption'.enter('Quantity On WO Lines')
      'Minimum Decimals'.enter('0')
      'OK'.click()
    'Back'.click()
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('0')
  'mainTable./Big Bag (BB01)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Default Location'.shouldEqual('General')
    'Default Location'.enter('FG01')
    'OK'.click()
  'mainTable./Brag Set (BS01)/.Adjust Qty'.click()
    'Quantity'.enter('1')
    'Unit Price (Inc Tax)'.enter('200.00')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Adjust Qty'.click()
    'Quantity'.enter('10')
    'Unit Price (Inc Tax)'.enter('50.00')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Adjust Qty'.click()
    'Quantity'.enter('30')
    'Unit Price (Inc Tax)'.enter('30.00')
    'OK'.click()
  'searcher'.enter('tag')
  'mainTable./Tag (TA01)/.Adjust Qty'.click()
    'Quantity'.enter('1000')
    'Unit Price (Inc Tax)'.enter('0.20')
    'OK'.click()
  'mainTable./Tag (TA01)/.Edit Product'.click()
    'Default Location'.enter('Subassemblies')
    'OK'.click()
  'Bundles'.click()
    'Bundles'.shouldBeCurrentPage()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Overhead Cost'.enter('10.00')
      'Expected Days To Manufacture'.shouldntExist()
      'Manage Manufacturing With Work Orders'.shouldEqual('No')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Expected Days To Manufacture'.shouldEqual('1')
      'Expected Days To Manufacture'.enter('2')
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('3')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable.0.Product'.shouldEqual('Brag Set (BS01)')
    'mainTable.0.Sellable Quantity'.shouldEqual('1')
    'Add'.click()
      'Bundle Product'.enter('Tag (TA01)')
      'Overhead Cost'.enter('1.00')
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Tag Outer (TO01)')
        'OK'.click()
      'Add Component'.click()
        'Add Component'.shouldBeCurrentPage()
        'Component Product'.enter('Tag Label (TL01)')
        'Quantity'.enter(2)
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_workOrders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO00001')
    'FG Lots'.shouldntExist()
    'Save'.click()
    'Inventory'.click()
      'mainTable./Brag Set (BS01)/.Edit Product'.click()
        'Serial/Lot Tracking'.enter('Lot')
        'OK'.click()
      'Back'.click()
    'Order Date'.shouldEqualExpression('global.todayLocal()')
    'Expected Completion Date'.shouldEqualExpression('global.todayLocal()')
    'Product'.enter('Brag Set (BS01)')
    'Expected Completion Date'.shouldEqualExpression('global.todayLocal().incDays(2)')
    'Order Date'.enterExpression('global.todayLocal().incDays(1)')
    'Expected Completion Date'.shouldEqualExpression('global.todayLocal().incDays(3)')
    'Expected Completion Date'.enterExpression('global.todayLocal().incDays(4)')
    'Finished Goods Location'.shouldEqual('FG01')
    'Generate Lines'.click()
      'messageDialogText'.shouldEqual("Please enter a quantity before generating lines", 'doc')
      'messageDialogOK'.click('doc')
    'Finished Goods Quantity'.enter('10')
    'FG Lots'.click()
      'Work Order Finished Goods Lots'.shouldBeCurrentPage()
      'Work Order Number'.shouldEqual('WO00001')
      'lots./Unspecified/.Quantity'.shouldEqual('10')
      'Add Lot'.click()
        'Lot Number'.enter('LOT01')
        'Quantity'.enter('6')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('LOT02')
        'Quantity'.enter('4')
        'OK'.click()
      'lots./LOT01/.Quantity'.shouldEqual('6')
      'lots./LOT02/.Quantity'.shouldEqual('4')
      'OK'.click()
    'Total Unit Cost (Excl Tax)'.shouldntExist()
    'Labels'.click()
      'Label Type'.shouldEqual('Inventory')
      'Source Type'.shouldEqual('Work Order')
      'Source Reference'.shouldEqual('WO00001')
      'Layout'.click()
        'Add Field'.click()
          'Get Value From'.chooseOption('WO.workOrderNumber')
          'Caption'.enter('WO Number')
          'Distance from Left of Label (mm)'.enter('20')
          'Distance from Top of Label (mm)'.enter('1')
          'OK'.click()
        'Add Field'.click()
          'Get Value From'.chooseOption('Allotment.lot')
          'Caption'.enter('Lot Number')
          'Distance from Left of Label (mm)'.enter('20')
          'Distance from Top of Label (mm)'.enter('17')
          'Maximum Width (mm)'.enter('20')
          'Font Size'.enter('8')
          'OK'.click()
        'Back'.click()
      'Download Labels PDF'.click()
      'Back'.click()
    'Save'.click()
    'stocktend_inventory'.click()
      'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('0')
      'Back'.click()
    'Generate Lines'.click()
    'Lines'.shouldHaveCount(3)
    'Lines./Little Bag (LB01)/.Edit'.click()
      'Edit Work Order Line'.shouldBeCurrentPage()
      'Product'.shouldEqual('Little Bag (LB01)')
      'Quantity'.shouldEqual('30')
      'OK'.click()
    'stocktend_inventory'.click()
      'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('10')
      'mainTable./Brag Set (BS01)/.Inventory by Location'.click()
        'mainTable./FG01/.Being Manufactured'.shouldEqual('10')
        'Back'.click()
      'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
        'mainTable./LOT01/.Quantity being Manufactured'.shouldEqual('6')
        'mainTable./LOT02/.Quantity being Manufactured'.shouldEqual('4')
        'Back'.click()
      'mainTable./Big Bag (BB01)/.Quantity On WO Lines'.shouldEqual('10')
      'mainTable./Little Bag (LB01)/.Quantity On WO Lines'.shouldEqual('30')
      'Back'.click()
    'Lines./Big Bag (BB01)/.Line Qty'.shouldEqual('10')
    'Lines./Big Bag (BB01)/.Line Qty'.shouldBeReadOnly()
    'Lines./Big Bag (BB01)/.Cost per FG Unit (Excl Tax)'.shouldEqual('45.454545')
    'Lines./Big Bag (BB01)/.From Location'.shouldEqual('General')
    'Lines./Big Bag (BB01)/.On Hand'.shouldEqual('10')
    'Lines./Big Bag (BB01)/.From Location'.enter('Raw Materials')
    'Lines./Big Bag (BB01)/.On Hand'.shouldEqual('0')
    'Lines./Little Bag (LB01)/.Line Qty'.shouldEqual('30')
    'Lines./Little Bag (LB01)/.Cost per FG Unit (Excl Tax)'.shouldEqual('81.818181')
    'Lines./Tag (TA01)/.Line Qty'.shouldEqual('100')
    'Lines./Tag (TA01)/.From Location'.shouldEqual('Subassemblies')
    'Lines./Tag (TA01)/.Cost per FG Unit (Excl Tax)'.shouldEqual('1.81818')
    'Cost of Components per FG Unit (Excl Tax)'.shouldEqual('129.09')
    'Overhead per FG Unit (Excl Tax)'.shouldEqual('9.09')
    'Total Cost Per FG Unit (Excl Tax)'.shouldEqual('138.18')
    'Lines./Big Bag (BB01)/.Description'.click()
      'Adjust Quantity On Hand'.click()
        'Product'.shouldEqual('Big Bag (BB01)')
        'Back'.click()
      'Back'.click()
    'Download PDF'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO00001/.Enter Receipt'.click()
      'Location'.shouldEqual('FG01')
      'Product'.shouldEqual('Brag Set (BS01)')
      'Ordered Quantity'.shouldEqual('10')
      'Received Quantity'.shouldEqual('10')
      'FG Lots'.click()
        'lots./LOT01/.quantity'.shouldEqual('6')
        'lots./LOT02/.quantity'.shouldEqual('4')
        'OK'.click()
      'Received Quantity'.enter('4')
      'FG Lots'.click()
        'lots./LOT01/.quantity'.shouldEqual('6')
        'lots./LOT02/.quantity'.shouldEqual('4')
        'lots./Unspecified/.quantity'.shouldEqual('-6')
        'lots./LOT01/.Trash'.click()
        'lots./LOT01/.Really Trash?'.click()
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable./WO00001/.Status'.shouldEqual('Partially Completed')
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('5')
  'mainTable./Brag Set (BS01)/.Inventory by Location'.click()
    'mainTable./FG01/.Being Manufactured'.shouldEqual('6')
    'Back'.click()
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable./LOT01/.Quantity Being Manufactured'.shouldEqual('6')
    'mainTable./LOT01/.Quantity On Hand'.shouldEqual('0')
    'mainTable./LOT02/.Quantity Being Manufactured'.shouldEqual('0')
    'mainTable./LOT02/.Quantity On Hand'.shouldEqual('4')
    'Back'.click()
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('6')
  'mainTable./Big Bag (BB01)/.Quantity On WO Lines'.shouldEqual('6')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO00001/.Enter Receipt'.click()
      'Product'.shouldEqual('Brag Set (BS01)')
      'Ordered Quantity'.shouldEqual('10')
      'Received Quantity'.shouldEqual('6')
      'OK'.click()
    'Back'.click()
  'mainTable./WO00001/.Status'.shouldEqual('Completed')
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('11')
  'mainTable./Brag Set (BS01)/.Avg Unit Cost'.shouldEqual('156.363636')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Big Bag (BB01)/.Quantity On WO Lines'.shouldEqual('0')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable.0.Edit'.click()
        'Received Quantity'.enter('0')
        'FG Lots'.click()
          'lots.0.Trash'.click()
          'lots.0.Really Trash?'.click()
          'OK'.click()
        'OK'.click()
      'mainTable.1.Edit'.click()
        'Received Quantity'.enter('0')
        'FG Lots'.click()
          'lots.0.Trash'.click()
          'lots.0.Really Trash?'.click()
          'OK'.click()
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('10')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO00001/.Enter Receipt'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Avg Unit Cost'.shouldEqual('156.363636')
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('11')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable.0.Trash'.click()
      'mainTable.0.Really Trash?'.click()
      'mainTable.0.Trash'.click()
      'mainTable.0.Really Trash?'.click()
      'mainTable.0.Trash'.click()
      'mainTable.0.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('10')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('10')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('30')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO00001/.Enter Receipt'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Avg Unit Cost'.shouldEqual('156.363636')
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('11')
  'mainTable./Big Bag (BB01)/.Quantity On Hand'.shouldEqual('0')
  'mainTable./Little Bag (LB01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'stocktend_workOrders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable.0.Trash'.click()
      'mainTable.0.Really Trash?'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('1')
  'mainTable./Brag Set (BS01)/.Quantity Being Manufactured'.shouldEqual('10')
  'mainTable./Brag Set (BS01)/.View Serial/Lots'.click()
    'mainTable./LOT01/.Quantity Being Manufactured'.shouldEqual('6')
    'mainTable./LOT01/.Quantity On Hand'.shouldEqual('0')
    'mainTable./LOT02/.Quantity Being Manufactured'.shouldEqual('4')
    'mainTable./LOT02/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'Cull'.chapter()
'helper'.trashAll('*')
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Number'.enter('BU01')
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('2')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO1')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('2')
    'Generate Lines'.click()
    'OK'.click()
  'Back'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO1/.Enter Receipt'.click()
      'Cull'.click()
        'Work Order Cull Products'.shouldBeCurrentPage()
        'Receipt Number'.shouldEqual('WO1-01')
        'Add Cull Product'.click()
          'Add Cull Product'.shouldBeCurrentPage()
          'Product'.shouldEqual('Brag Set (BS01)')
          'Product'.clickDropdown()
          'Product'.shouldHaveNOptions(2)
          'Product'.shouldHaveOption('Brag Set (BS01)')
          'Product'.shouldHaveOption('Big Bag (BB01)')
          'Cull Quantity'.enter('3')
          'OK'.click()
        'Cull Products'.shouldHaveCount(1)
        'Add Cull Product'.click()
          'Product'.enter('Big Bag (BB01)')
          'Cull Quantity'.enter('2')
          'OK'.click()
        'Cull Products'.shouldHaveCount(2)
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable./WO1-01/.Edit'.click()
        'Cull'.click()
          'Cull Products'.shouldHaveCount(2)
          'OK'.click()
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO2')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('2')
    'Generate Lines'.click()
    'OK'.click()
  'Back'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO2/.Enter Receipt'.click()
      'Completion Date'.enterExpression('global.todayLocal().incDays(1)')
      'Cull'.click()
        'Add Cull Product'.click()
          'Cull Quantity'.enter('5')
          'OK'.click()
        'Add Cull Product'.click()
          'Product'.enter('Big Bag (BB01)')
          'Cull Quantity'.enter('4')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Cull Report'.click()
    'Cull Report'.shouldBeCurrentPage()
    'Product'.enter('Brag Set (BS01)')
    'From Date'.enterExpression('global.todayLocal()')
    'To Date'.enterExpression('global.todayLocal()')
    'Go'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable./Brag Set (BS01)/.WO Receipt'.shouldEqual('WO1-01')
    'mainTable./Brag Set (BS01)/.Cull Quantity'.shouldEqual('3')
    'mainTable./Brag Set (BS01)/.Bundle'.shouldEqual('BU01')
    'mainTable./Brag Set (BS01)/.Date'.shouldEqualExpression('global.todayLocal().toLocalMMMDY()')
    'Product'.enter('')
    'From Date'.enterExpression('global.todayLocal()')
    'To Date'.enterExpression('global.todayLocal().incDays(1)')
    'Go'.click()
    'mainTable'.shouldHaveCount(4)
    'Back'.click()
  'Back'.click()
'RecallsAndSubstitutes'.chapter()
'helper'.trashAll('*')
'helper'.allowExclusives()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Enter Incremental Shipment Quantity'.enter('Yes')
  'Split WC Orders to Match Shipments'.enter('Yes') 
  'Status to set WC Order to when Shipment Created'.enter('Completed')
  'Include Exclusive Customizations'.enter('Yes')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter('Bombast Corporation')
    'OK'.click()
  'Add'.click()
    'Name'.enter('Castaways')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Default Expiry Days'.shouldntExist()
    'Track Expiry Dates'.enter('Yes')
    'Default Expiry Days'.shouldEqual('0')
    'Default Expiry Days'.enter('30')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Little Bag (LB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'searcher'.enter('ta')
  'mainTable./Tag (TA01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Tag Outer (TO01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'mainTable./Tag Label (TL01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'Track Expiry Dates'.enter('Yes')
    'OK'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('2')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag (TA01)')
        'Quantity'.enter('3')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Bundle Product'.enter('Tag (TA01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Tag Outer (TO01)')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Component'.click()
        'Component Product'.enter('Tag Label (TL01)')
        'Quantity'.enter('2')
        'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO1')
    'Supplier'.enter('Bombast Corporation')
    'Add Line'.click()
      'Product'.enter('Big Bag (BB01)')
      'Quantity'.enter('10')
      'Add Lot'.click()
        'Lot Number'.enter('B-B-1')
        'Supplier Lot Number'.enter('S+B+B+1')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('B-B-2')
        'Supplier Lot Number'.enter('S+B+B+2')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Little Bag (LB01)')
      'Quantity'.enter('10')
      'Add Lot'.click()
        'Lot Number'.enter('L-B-1')
        'Supplier Lot Number'.enter('S+L+B+1')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('L-B-2')
        'Supplier Lot Number'.enter('S+L+B+1')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'stocktend_inventory'.click()
    'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
      'mainTable./B-B-1/.Lot Number'.click()
        'Supplier Lot Number'.shouldEqual('S+B+B+1')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Add'.click()
    'Purchase Order Number'.enter('PO2')
    'Supplier'.enter('Castaways')
    'Add Line'.click()
      'Product'.enter('Tag Outer (TO01)')
      'Quantity'.enter('10')
      'Add Lot'.click()
        'Lot Number'.enter('T-O-1')
        'Supplier Lot Number'.enter('S+T+O+1')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-O-2')
        'Supplier Lot Number'.enter('S+T+O+2')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'OK'.click()
    'Add Line'.click()
      'Product'.enter('Tag Label (TL01)')
      'Quantity'.enter('10')
      'Add Lot'.click()
        'Lot Number'.enter('T-L-1')
        'Supplier Lot Number'.enter('S+T+L+1')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-L-2')
        'Supplier Lot Number'.enter('S+T+L+2')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable./PO1/.Enter Receipt'.click()
    'OK'.click()
  'mainTable./PO2/.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'stocktend_locations'.click()
  'Add'.click()
    'Location Name'.enter('Melb')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'searcher'.enter('TL01')
  'mainTable./Tag Label (TL01)/.Adjust Qty'.click()
    'Location'.enter('Melb')
    'Quantity Change'.enter('50')
    'Unit Price (Inc Tax)'.enter('100.00')
    'Add Lot'.click()
      'Lot Number'.enter('T-L-MEL')
      'Quantity'.enter('50')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'searcher'.enter('TL01')
  'mainTable./Tag Label (TL01)/.Quantity on Hand'.shouldEqual('60')
  'mainTable./Tag Label (TL01)/.Avg Unit Cost'.shouldEqual('83.333333')
  'mainTable./Tag Label (TL01)/.View Serial/Lots'.click()
    'mainTable./T-L-1/.Quantity on Hand'.shouldEqual('5')
    'mainTable./T-L-2/.Quantity on Hand'.shouldEqual('5')
    'mainTable./T-L-MEL/.Quantity on Hand'.shouldEqual('50')
    'Back'.click()
  'mainTable./Tag Label (TL01)/.Quantity on Hand'.shouldEqual('60')
  'mainTable./Tag Label (TL01)/.Edit Product'.click()
    'Supercede'.click()
      'Supercede Product'.shouldBeCurrentPage()
      'Old Product'.shouldEqual('Tag Label (TL01)')
      'New Product'.enter('Corn Flakes (CF01)')
      'Process Now'.click()
        'messageDialogText'.shouldContain("Supercede complete", 'doc')
        'OK'.click('doc')
      'Back'.click()
    'OK'.click()
  'searcher'.enter('CF01')
  'mainTable./Corn Flakes (CF01)/.Quantity On Hand'.shouldEqual('60')
  'Bundles'.click()
    'mainTable./Tag (TA01)/.Edit'.click()
      'Components./Corn Flakes (CF01)/.Internal Quantity'.shouldEqual('2')
      'Components./Tag Label (TL01)/.Internal Quantity'.shouldntExist()
      'OK'.click()
    'Back'.click()
  'searcher'.enter('TL01')
  'mainTable./Tag Label (TL01)/.Avg Unit Cost'.shouldEqual('83.333333')
  'searcher'.enter('CF01')
  'mainTable./Corn Flakes (CF01)/.View Serial/Lots'.click()
    'mainTable./T-L-1/.Quantity on Hand'.shouldEqual('5')
    'mainTable./T-L-2/.Quantity on Hand'.shouldEqual('5')
    'mainTable./T-L-MEL/.Quantity on Hand'.shouldEqual('50')
    'Back'.click()
  'mainTable./Corn Flakes (CF01)/.Supercede'.click()
    'Supercede Product'.shouldBeCurrentPage()
    'Old Product'.shouldEqual('Corn Flakes (CF01)')
    'New Product'.enter('Tag Label (TL01)')
    'Process Now'.click()
      'messageDialogText'.shouldContain("Supercede complete", 'doc')
      'OK'.click('doc')
    'Back'.click()
  'Bundles'.click()
    'mainTable./Tag (TA01)/.Edit'.click()
      'Components./Tag Label (TL01)/.Internal Quantity'.shouldEqual('2')
      'Components./Corn Flakes (CF01)/.Internal Quantity'.shouldntExist()
      'OK'.click()
    'Back'.click()
  'searcher'.enter('')
  'mainTable./Brag Set (BS01)/.Supercede'.click()
    'Supercede Product'.shouldBeCurrentPage()
    'Old Product'.shouldEqual('Brag Set (BS01)')
    'New Product'.enter('Corn Flakes (CF01)')
    'Process Now'.click()
      'messageDialogText'.shouldContain("Supercede complete", 'doc')
      'OK'.click('doc')
    'Back'.click()
  'Bundles'.click()
    'mainTable./Corn Flakes (CF01)/.Edit'.click()
      'Components./Big Bag (BB01)/.Internal Quantity'.shouldEqual('1')
      'OK'.click()
    'Back'.click()
  'mainTable./Corn Flakes (CF01)/.Supercede'.click()
    'Supercede Product'.shouldBeCurrentPage()
    'Old Product'.shouldEqual('Corn Flakes (CF01)')
    'New Product'.enter('Brag Set (BS01)')
    'Process Now'.click()
      'messageDialogText'.shouldContain("Supercede complete", 'doc')
      'OK'.click('doc')
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'Bundles'.click()
    'mainTable./Brag Set (BS01)/.Edit'.click()
      'Components./Tag (TA01)/.Edit'.click()
        'Add Alternative'.click()
          'Alternative Product'.enter('Cap (C01)')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO1')
    'Product'.enter('Tag (TA01)')
    'Finished Goods Quantity'.enter('20')
    'FG Lots'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-A-1')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('5')
        'Output Product (if different to WO product)'.shouldntExist()
        'Product'.shouldEqual('Tag (TA01)')
        'Product'.shouldBeReadOnly()
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-A-2')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('5')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-A-OTHER')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Generate Lines'.click()
    'Lines./Tag Outer (TO01)/.Edit'.click()
      'Lots./T-O-1/.Quantity'.shouldEqual('5') // 'Add Lot'.click(); 'Lot Number'.enter('T-O-1'); 'Quantity'.enter('5'); 'OK'.click();
      'Lots./T-O-2/.Quantity'.shouldEqual('5') // 'Add Lot'.click(); 'Lot Number'.enter('T-O-2'); 'Quantity'.enter('5'); 'OK'.click();
      'OK'.click()
    'Lines./Tag Label (TL01)/.Edit'.click()
      'Lots./T-L-1/.Edit'.click() //'Add Lot'.click(); 'Lot Number'.enter('T-L-1')
        'Quantity'.enter('10')
        'OK'.click()
      'Lots./T-L-2/.Edit'.click() // 'Add Lot'.click(); 'Lot Number'.enter('T-L-2')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'Add'.click()
    'Work Order Number'.enter('WO2')
    'Product'.enter('Brag Set (BS01)')
    'Order Date'.enter('31/12/2022')
    'Expected Completion Date'.shouldEqual('01/01/2023')
    'Expiry Date'.shouldEqual('31/01/2023')
    'Finished Goods Quantity'.enter('2')
    'FG Lots'.click()
      'Add Lot'.click()
        'Lot Number'.enter('BR-S-1')
        'Expiry Date'.shouldEqual('31/01/2023')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('BR-S-2')
        'Expiry Date'.shouldEqual('31/01/2023')
        'Expiry Date'.enter('1/2/2030')
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'Expiry Date'.enter('31/1/2024')
    'FG Lots'.click()
      'Lots.0.Edit'.click()
        'Expiry Date'.shouldEqual('31/01/2024')
        'Expiry Date'.enter('1/1/2030')
        'OK'.click()
      'Lots.1.Edit'.click()
        'Expiry Date'.shouldEqual('31/01/2024')
        'Expiry Date'.enter('1/2/2030')
        'OK'.click()
      'OK'.click()
    'Generate Lines'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'Lots./B-B-1/.Edit'.click() // 'Add Lot'.click(); 'Lot Number'.enter('B-B-1')
        'Quantity'.enter('1')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('B-B-2')
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'Lines./Little Bag (LB01)/.Edit'.click()
      'Lots./L-B-1/.Edit'.click() // 'Add Lot'.click(); 'Lot Number'.enter('L-B-1')
        'Quantity'.enter('2')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('L-B-2')
        'Quantity'.enter('2')
        'OK'.click()
      'OK'.click()
    'Lines./Tag (TA01)/.Edit'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-A-1')
        'Quantity'.enter('3')
        'OK'.click()
      'Add Lot'.click()
        'Lot Number'.enter('T-A-2')
        'Quantity'.enter('3')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'stocktend_inventory'.click()
    'mainTable./Big Bag (BB01)/.View Serial/Lots'.click()
      'mainTable./B-B-1/.Lot Number'.click()
        'Supplier Lot Number'.shouldEqual('S+B+B+1')
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO1/.Enter Receipt'.click()
      'FG Lots'.click()
        'Lots./T-A-OTHER/.Edit'.click()
          'Product'.shouldEqual('Tag (TA01)')
          'Output Product (if different to WO product)'.shouldEqual('')
          'Output Product (if different to WO product)'.enter('Cap (C01)')
          'Product'.shouldntExist()
          'OK'.click()
        'Lots./T-A-OTHER/.Product'.shouldEqual('Cap (C01)')
        'Lots./T-A-1/.Product'.shouldEqual('Tag (TA01)')
        'OK'.click()
      'OK'.click()
    'mainTable./WO2/.Enter Receipt'.click()
      'Expiry Date'.shouldEqual('31/01/2024')
      'FG Lots'.click()
        'Lots./BR-S-1/.Edit'.click()
          'Expiry Date'.shouldEqual('01/01/2030')
          'OK'.click()
        'Lots./BR-S-2/.Edit'.click()
          'Expiry Date'.shouldEqual('01/02/2030')
          'OK'.click()
        'OK'.click()
      'Expiry Date'.enter('31/1/2025')
      'FG Lots'.click()
        'Lots./BR-S-1/.Edit'.click()
          'Expiry Date'.shouldEqual('31/01/2025')
          'OK'.click()
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable./WO1-01/.Edit'.click()
        'FG Lots'.click()
          'Lots./T-A-OTHER/.Product'.shouldEqual('Cap (C01)')
          'Lots./T-A-OTHER/.Edit'.click()
            'Product'.shouldntExist()
            'Output Product (if different to WO product)'.shouldEqual('Cap (C01)')
            'Output Product (if different to WO product)'.enter('Hoodie (H01)')
            'OK'.click()
            'stFormRejection'.shouldContain('Output Product cannot be changed. Please Trash this lot line and add a new one')
            'Output Product (if different to WO product)'.enter('Cap (C01)')
            'OK'.click()
          'OK'.click()
        'Back'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('10')
  'searcher'.enter('TA')
  'mainTable./Tag (TA01)/.Quantity On Hand'.shouldEqual('4')
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Status'.enter('Processing')
      'Add Line'.click()
        'Product'.enter('Brag Set (BS01)')
        'Quantity'.enter('2')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('8')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (kevin.costly)')
      'Status'.enter('Processing')
      'Add Line'.click()
        'Product'.enter('Little Bag (LB01)')
        'Quantity'.enter('6')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Tag (TA01)')
        'Quantity'.enter('14')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (paul.andrews)')
      'Status'.enter('Processing')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('10')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable./Johnny Appleseed, Fester Inc/.Edit'.click()
    'Lines./Brag Set (BS01)/.Edit'.click()
      'This Shipment Qty'.enter('1')
      'Lots./BR-S-2/.Trash'.click()
      'Lots./BR-S-2/.Really Trash?'.click()
      'OK'.click()
    'Lines./Big Bag (BB01)/.Edit'.click()
      'This Shipment Qty'.enter('5')
      'Lots./B-B-2/.Edit'.click()
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'View Shipments'.click()
    'mainTable.0.Edit'.click()
      'Invoiced'.enter('Yes')
      'OK'.click()
    'Back'.click()
  'mainTable./Johnny Appleseed, Fester Inc/.Edit'.click()
    'Lines./Brag Set (BS01)/.This Shipment Qty'.enter('1')
    'Lines./Big Bag (BB01)/.This Shipment Qty'.enter('3')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Recalls'.click()
    'Customer'.enter('Fester Inc (johnny.appleseed)')
    'Go'.click()
    'mainTable'.shouldHaveCount(5)
    'mainTable./BR-S-1/.Lot'.click()
      'Component Lots By FG Lot'.shouldBeCurrentPage()
      'FG Lot'.shouldEqual('BR-S-1')
      'mainTable./B-B-1/.Component Lot'.shouldEqual('B-B-1')
      'mainTable./B-B-1/.Parent Lot'.shouldEqual('BR-S-1')
      'mainTable./B-B-1/.WO Receipt'.shouldEqual('WO2-01')
      'searcher'.enter('PO1-01')
      'mainTable./B-B-1/.PO Receipt'.shouldEqual('PO1-01')
      'searcher'.enter('WO')
      'mainTable./T-L-1/.Component Lot'.shouldEqual('T-L-1')
      'mainTable./T-L-1/.Parent Lot'.shouldEqual('T-A-1')
      'mainTable./T-L-1/.Component Lot'.click()
        'Sales Orders By Component Lot'.shouldBeCurrentPage()
        'Component Lot'.shouldEqual('T-L-1')
        'searcher'.enter('T-A-1')
        'mainTable.0.Product'.shouldEqual('Tag (TA01)')
        'mainTable.0.Lot'.shouldEqual('T-A-1')
        'mainTable.0.Customer'.shouldEqual('Fester Inc (kevin.costly)')
        'searcher'.enter('BR-S-1')
        'mainTable.0.Product'.shouldEqual('Brag Set (BS01)')
        'mainTable.0.Lot'.shouldEqual('BR-S-1')
        'mainTable.0.Customer'.shouldEqual('Fester Inc (johnny.appleseed)')
        'Back'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable./Paul Andrews, Fester Inc/.Edit'.click()
    'Lines./Cap (C01)/.Edit'.click()
      'This Shipment Qty'.enter('10')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Recalls'.click()
    'Customer'.enter('Fester Inc (paul.andrews)')
    'Go'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable./T-A-OTHER/.Lot'.click()
      'FG Lot'.shouldEqual('T-A-OTHER')
      'searcher'.enter('WO')
      'mainTable./T-L-1/.Component Lot'.shouldEqual('T-L-1')
      'mainTable./T-L-1/.Parent Lot'.shouldEqual('T-A-OTHER')
      'mainTable./T-L-1/.Parent Product'.shouldEqual('Cap (C01)')
      'mainTable./T-L-1/.Component Lot'.click()
        'Sales Orders By Component Lot'.shouldBeCurrentPage()
        'Component Lot'.shouldEqual('T-L-1')
        'mainTable./Cap (C01)/.Lot'.shouldEqual('T-A-OTHER')
        'Back'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO4')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('1')
    'FG Lots'.click()
      'Add Lot'.click()
        'Lot Number'.enter('BR-S-3')
        'Expiry Date'.enter('1/1/2030')
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'Generate Lines'.click()
    'Lines./Tag (TA01)/.Edit'.click()
      'Product'.enter('Cap (C01)') 
      'Add Lot'.click()
        'Lot Number'.enter('T-A-OTHER')
        'Quantity'.enter('3')
        'OK'.click()
      'OK'.click()
    'OK'.click()
  'Receive Work Orders'.click()
    'mainTable./WO4/.Enter Receipt'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Show Completed Orders'.click()
    'searcher'.enter('paul')
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (paul.andrews)')
      'Status'.enter('Processing')
      'Add Line'.click()
        'Product'.enter('Brag Set (BS01)')
        'Quantity'.enter('1')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Fulfillment'.click()
  'mainTable./Paul Andrews, Fester Inc/.Edit'.click()
    'Lines./Brag Set (BS01)/.Edit'.click()
      'This Shipment Qty'.enter('1')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Recalls'.click()
    'Customer'.enter('Fester Inc (paul.andrews)')
    'Go'.click()
    'mainTable'.shouldHaveCount(1)
    'mainTable./BR-S-3/.Lot'.click()
      'searcher'.enter('WO')
      'mainTable./T-L-1/.Component Lot'.shouldEqual('T-L-1')
      'mainTable./T-L-1/.Parent Lot'.shouldEqual('T-A-OTHER')
      'mainTable./T-L-1/.Parent Product'.shouldEqual('Cap (C01)')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'Coproducts'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Include Exclusive Customizations'.enter('No')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Big Bag (BB01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'mainTable./Bonnet (BONNET01)/.Edit Product'.click()
    'Serial/Lot Tracking'.enter('Lot')
    'OK'.click()
  'Bundles'.click()
    'Add'.click()
      'Bundle Number'.enter('BU01')
      'Bundle Product'.enter('Brag Set (BS01)')
      'Manage Manufacturing With Work Orders'.enter('Yes')
      'Add Component'.click()
        'Component Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('2')
        'OK'.click()
        'Co-products'.click()
          'Add Co-product'.click()
            'Product'.enter('Corn Flakes (CF01)')
            'OK'.click()
          'Co-products'.shouldHaveCount(1)
          'Add Co-product'.click()
            'Product'.enter('Bonnet (BONNET01)')
            'OK'.click()
          'Co-products'.shouldHaveCount(2)
        'Back'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Work Orders'.click()
  'Add'.click()
    'Work Order Number'.enter('WO1')
    'Product'.enter('Brag Set (BS01)')
    'Finished Goods Quantity'.enter('2')
    'Generate Lines'.click()
    'OK'.click()
  'Back'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO1/.Enter Receipt'.click()
      'Co-products'.shouldntExist()
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Allow WO Receipt Co-products'.enter('Yes')
  'OK'.click()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'mainTable./WO1/.Enter Receipt'.click()
      'Co-products'.click()
        'Work Order Receipt Co-products'.shouldBeCurrentPage()
        'Receipt Number'.shouldEqual('WO1-01')
        'Add Co-product'.click()
          'Add Co-product'.shouldBeCurrentPage()
          'Product'.clickDropdown()
          'Product'.shouldHaveNOptions(2)
          'Product'.enter('Corn Flakes (CF01)')
          'Quantity'.enter('3')
          'Lots./Unspecified/.Quantity'.shouldEqual('3')
          'Add Lot'.click()
            'Lot Number'.enter('CFLOT01')
            'Quantity'.enter('2')
            'OK'.click()
          'Add Lot'.click()
            'Lot Number'.enter('CFLOT02')
            'Quantity'.enter('1')
            'OK'.click()
          'Lots./CFLOT01/.Quantity'.shouldEqual('2')
          'Lots./CFLOT02/.Quantity'.shouldEqual('1')
          'OK'.click()
        'Co-products'.shouldHaveCount(1)
        'Add Co-product'.click()
          'Product'.enter('Bonnet (BONNET01)')
          'Quantity'.enter('2')
          'Lots./Unspecified/.Quantity'.shouldEqual('2')
          'Add Lot'.click()
            'Lot Number'.enter('BLOT01')
            'Quantity'.shouldEqual('2')
            'OK'.click()
          'Lots./BLOT01/.Quantity'.shouldEqual('2')
          'OK'.click()
        'Co-products'.shouldHaveCount(2)
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Brag Set (BS01)/.Quantity On Hand'.shouldEqual('2')
  'mainTable./Corn Flakes (CF01)/.Quantity On Hand'.shouldEqual('3')
  'mainTable./Corn Flakes (CF01)/.View Serial/Lots'.click()
    'mainTable./CFLOT01/.Quantity On Hand'.shouldEqual('2')
    'mainTable./CFLOT02/.Quantity On Hand'.shouldEqual('1')
    'Back'.click()
  'mainTable./Bonnet (BONNET01)/.Quantity On Hand'.shouldEqual('2')
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Work Orders'.click()
  'Receive Work Orders'.click()
    'View All Receipts'.click()
      'mainTable./WO1-01/.Edit'.click()
        'Co-products'.click()
          'Co-products'.shouldHaveCount(2)
          'OK'.click()
        'OK'.click()
      'Back'.click()
    'Back'.click()
  'Back'.click()
