'Embryo'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Support Unlisted Product Ordering'.enter('Yes')
  'OK'.click()
'stocktend_suppliers'.click()
  'Add'.click()
    'Name'.enter('Acme')
    'Generic Product for Sales of Unlisted Products'.enter('Corn Flakes (CF01)')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (kevin.costly)')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('1')
        'Unit Price (Excl Tax)'.enter('10.00')
        'Notes'.enter('Embryo 1')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('1')
        'Unit Price (Excl Tax)'.enter('10.00')
        'Notes'.enter('Embryo 1')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('1')
        'Unit Price (Excl Tax)'.enter('10.00')
        'Notes'.enter('Embryo 2')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Supplier'.enter('Acme')
    'Add Line'.click()
      'Product'.enter('Cap (C01)')
      'Quantity'.enter('1')
      'OK'.click()
    'Lines.0.Unlisted Product Notes'.shouldntExist()
    'Bulk Add'.click()
      'Bulk Add PO Lines'.shouldBeCurrentPage()
      'mainTable'.shouldHaveCount(3) // including Cap
      'mainTable./Embryo 1/.Unlisted Qty on Sales Orders'.shouldEqual('2')
      'mainTable./Embryo 1/.Product'.shouldEqual('Corn Flakes (CF01)')
      'mainTable./Embryo 1/.Order Quantity'.enter('2')
      'mainTable./Embryo 2/.Unlisted Qty on Sales Orders'.shouldEqual('1')
      'mainTable./Embryo 2/.Product'.shouldEqual('Corn Flakes (CF01)')
      'mainTable./Embryo 2/.Order Quantity'.enter('1')
      'OK'.click()
    'Lines'.shouldHaveCount(3)
    'Lines.0.Unlisted Product Notes'.shouldEqual('')
    'Lines.1.Unlisted Product Notes'.shouldEqual('Embryo 1')
    'Lines.2.Unlisted Product Notes'.shouldEqual('Embryo 2')
    'Lines./Embryo 1/.Quantity'.shouldEqual('2')
    'Lines./Embryo 1/.Description'.shouldEqual('Corn Flakes (CF01)')
    'Lines./Embryo 2/.Quantity'.shouldEqual('1')
    'Lines./Embryo 2/.Description'.shouldEqual('Corn Flakes (CF01)')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'List Unlisted Products'.click()
    'mainTable'.shouldHaveCount(2)
    'mainTable./Embryo 1/.List this Product'.click()
      'List Unlisted Product'.shouldBeCurrentPage()
      'Supplier'.shouldEqual('Acme')
      'Supplier'.shouldBeReadOnly()
      'Notes'.shouldEqual('Embryo 1')
      'Notes'.shouldBeReadOnly()
      'Product Name'.shouldEqual('Embryo 1')
      'Product Name'.enter('')
      'OK'.click()
      'stFormRejection'.shouldContain('Product Name is required')
      'Product Name'.enter('Acme Embryo 1')
      'OK'.click()
      'messageDialogText'.shouldContain("SKU is required", 'doc')
      'messageDialogOK'.click('doc')
      'SKU'.enter('CF01')
      'OK'.click()
      'messageDialogText'.shouldContain("SKU CF01 is already in use", 'doc')
      'messageDialogOK'.click('doc')
      'SKU'.enter('prfi_EM01')
      'Brand'.enter('Acme')
      'OK'.click()
      'messageDialogText'.shouldEqual("New product was created, and customer and supplier order lines converted", 'doc')
      'OK'.click('doc')
    'mainTable'.shouldHaveCount(1)
    'stocktend_purchaseOrders'.click()
      'mainTable.0.Edit'.click()
        'Lines./Acme Embryo 1 (prfi_EM01)/.Description'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
        'OK'.click()
      'Back'.click()
    'stocktend_inventory'.click()
      'mainTable./Acme Embryo 1 (prfi_EM01)/.On Purchase Orders'.shouldEqual('2')
      'Back'.click()
    'Sales and Invoices'.click()
      'mainTable.0.Product'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
      'mainTable.0.Quantity'.shouldEqual('1')
      'mainTable.0.Amount Ex Tax'.shouldEqual('10.00')
      'mainTable.0.Tax'.shouldEqual('1.00')
      'mainTable.1.Product'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
      'mainTable.1.Quantity'.shouldEqual('1')
      'mainTable.1.Amount Ex Tax'.shouldEqual('10.00')
      'mainTable.1.Tax'.shouldEqual('1.00')
      'Back'.click()
    'List Unlisted Products'.shouldBeCurrentPage()
    'mainTable.0.Use Existing Product'.click()
      'Link Unlisted Product to Existing Product'.shouldBeCurrentPage()
      'Supplier'.shouldEqual('Acme')
      'Supplier'.shouldBeReadOnly()
      'Notes'.shouldEqual('Embryo 2')
      'Notes'.shouldBeReadOnly()
      'OK'.click()
      'messageDialogText'.shouldContain("Link to Product is required", 'doc')
      'messageDialogOK'.click('doc')
      'Link to Product'.enter('Hoodie (H01)')
      'OK'.click()
      'messageDialogText'.shouldEqual("Customer and supplier order lines have been converted to the specified product", 'doc')
      'OK'.click('doc')
    'mainTable'.shouldHaveCount(0)
    'stocktend_purchaseOrders'.click()
      'mainTable.0.Edit'.click()
        'Lines.1.Description'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
        'Lines.2.Description'.shouldEqual('Hoodie (H01)')
        'OK'.click()
      'Back'.click()
    'stocktend_inventory'.click()
      'mainTable./Acme Embryo 1 (prfi_EM01)/.On Purchase Orders'.shouldEqual('2')
      'mainTable./Hoodie (H01)/.On Purchase Orders'.shouldEqual('1')
      'Back'.click()
    'Sales and Invoices'.click()
      'mainTable.1.Product'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
      'mainTable.1.Quantity'.shouldEqual('1')
      'mainTable.1.Amount Ex Tax'.shouldEqual('10.00')
      'mainTable.1.Tax'.shouldEqual('1.00')
      'mainTable.2.Product'.shouldEqual('Acme Embryo 1 (prfi_EM01)')
      'mainTable.2.Quantity'.shouldEqual('1')
      'mainTable.2.Amount Ex Tax'.shouldEqual('10.00')
      'mainTable.2.Tax'.shouldEqual('1.00')
      'mainTable./Hoodie (H01)/.Quantity'.shouldEqual('1')
      'mainTable./Hoodie (H01)/.Amount Ex Tax'.shouldEqual('10.00')
      'Back'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Acme Embryo 1 (prfi_EM01)/.Quantity On Hand'.shouldEqual('-2')
  'searcher'.enter('hoo')
  'mainTable./Hoodie (H01)/.Quantity On Hand'.shouldEqual('-1')
  'Back'.click()
'stocktend_receivePurchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Acme Embryo 1 (prfi_EM01)/.Quantity On Hand'.shouldEqual('0')
  'searcher'.enter('hoo')
  'mainTable./Hoodie (H01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'PreventNegativeMargin'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'OK'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Prevent Negative Margin When Entering Orders In Profitori'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity Change'.enter('1')
    'Unit Price (Inc Tax)'.enter('100')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Unit Price (Excl Tax)'.enter('80')
        'OK'.click()
        'stFormRejection'.shouldContain('Price is below cost')
        'Unit Price (Excl Tax)'.enter('120')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'PreventNegativeStock'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'OK'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Prevent Negative Stock When Entering Orders In Profitori'.enter('Yes')
  'OK'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
      'stFormRejection'.shouldContain('Not enough quantity on hand of Cap (C01)')
      'Back'.click()
      'Yes - Cancel my changes'.click('doc')
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity Change'.enter('1')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Quantity On Hand'.shouldEqual('0')
  'Back'.click()
'Stock'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Save Total Order Inventory Value as a WC Order Attribute'.enter('Yes')
  'OK'.click()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Adjust Qty'.click()
    'Quantity Change'.enter('1')
    'Unit Price (Inc Tax)'.enter('10.00')
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Adjust Qty'.click()
    'Quantity Change'.enter('1')
    'Unit Price (Inc Tax)'.enter('20.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('2')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.View History'.click()
    'mainTable.0.Source'.shouldEqual('Sale')
    'Back'.click()
  'Back'.click()
'Markups'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Default Tax %'.enter('10')
  'Use Markup Pricing'.enter('Yes')
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('15.00')
    'WooCommerce Regular Price Inc Tax'.shouldEqual('18.00')
    'Use Markup Pricing'.shouldEqual('No')
    'Base Markup On'.shouldntExist()
    'Markup %'.shouldntExist()
    'Current Marked Up Price Inc Tax'.shouldntExist()
    'Current Marked Up Price Excl Tax'.shouldntExist()
    'Use Markup Pricing'.enter('Yes')
    'Base Markup On'.clickDropdown()
    'Base Markup On'.shouldHaveOption('Average Cost')
    'Base Markup On'.shouldHaveOption('Last Cost')
    'Base Markup On'.enter('Last Cost')
    'Markup %'.shouldEqual('0.00')
    'Last Purchase Unit Cost (Inc Tax)'.enter('10.00')
    'Current Marked Up Price Inc Tax'.shouldEqual('18.00') // because marked up price is lower than regular price
    'Markup %'.enter('150.1')
    'Current Marked Up Price Inc Tax'.shouldEqual('27.28')
    'Current Marked Up Price Inc Tax'.shouldBeReadOnly()
    'Current Marked Up Price Excl Tax'.shouldEqual('22.75')
    'Current Marked Up Price Excl Tax'.shouldBeReadOnly()
    'Last Purchase Unit Cost (Inc Tax)'.enter('1.00')
    'Current Marked Up Price Inc Tax'.shouldEqual('18.00') // because marked up price is lower than regular price
    'Current Marked Up Price Excl Tax'.shouldEqual('15.00')
    'Last Purchase Unit Cost (Inc Tax)'.enter('10.00')
    'Current Marked Up Price Inc Tax'.shouldEqual('27.28')
    'Current Marked Up Price Excl Tax'.shouldEqual('22.75')
    'OK'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('1.00')
    'Use Markup Pricing'.enter('Yes')
    'Base Markup On'.enter('Average Cost')
    'Adjust Quantity On Hand'.click()
      'Quantity Change'.enter('1')
      'Unit Price (Inc Tax)'.enter('10.00')
      'OK'.click()
    'Markup %'.enter('150.1')
    'Current Marked Up Price Inc Tax'.shouldEqual('27.28')
    'Current Marked Up Price Excl Tax'.shouldEqual('22.75')
    'OK'.click()
  'mainTable./Coat (COAT01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('0.45')
    'OK'.click()
  'Back'.click()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('10')
        'Unit Price (Excl Tax)'.shouldEqual('22.75')
        'Line Total (Excl Tax)'.shouldEqual('227.50')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Coat (COAT01)')
        'Quantity'.enter('10')
        'Unit Price (Excl Tax)'.shouldEqual('0.45')
      'OK'.click()
    'Back'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
  'Back'.click()
'helper'.addWCOrder({customer: 'Fester Inc (kevin.costly)', product: 'Cap (C01)', quantity: 1, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'helper'.addWCOrderItem({product: 'Coat (COAT01)', quantity: 1, useProductPrice: true})
'helper'.addWCOrderItem({product: 'Corn Flakes (CF01)', quantity: 1, useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Cap/.Edit'.click()
        'Unit Price (Excl Tax)'.shouldEqual('22.75')
        'Line Total (Excl Tax)'.shouldEqual('22.75')
        'OK'.click()
      'Lines./Coat/.Edit'.click()
        'Unit Price (Excl Tax)'.shouldEqual('0.45')
        'Line Total (Excl Tax)'.shouldEqual('0.45')
        'OK'.click()
      'Lines./Corn Flakes/.Edit'.click()
        'Unit Price (Excl Tax)'.shouldEqual('22.75')
        'Line Total (Excl Tax)'.shouldEqual('22.75')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_purchaseOrders'.click()
  'Add'.click()
    'Add Line'.click()
      'Product'.enter('Corn Flakes (CF01)')
      'Quantity'.enter('1')
      'Unit Price (Inc Tax)'.enter('20.00')
      'OK'.click()
    'OK'.click()
  'Back'.click()
'Receive Purchases'.click()
  'mainTable.1.Enter Receipt'.click()
    'OK'.click()
  'Back'.click()
'helper'.addWCOrder({customer: 'Fester Inc (kevin.costly)', product: 'Corn Flakes (CF01)', quantity: 1, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Corn Flakes/.Edit'.click()
        'Unit Price (Excl Tax)'.shouldEqual('34.10')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Discounts'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_mcg')
    'Name'.enter('Melbourne Cricket Ground')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Password'.enter('secret')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Melbourne Cricket Ground (prfi_mcg)')
      'Add Line'.click()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('No')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('10.00')
        'Discount Type'.shouldEqual('Percentage')
        'Discount %'.enter('10')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('9.00')
        'Line Total (Excl Tax)'.shouldEqual('90.00')
        'Apply Discount'.enter('No')
        'Unit Price (Excl Tax)'.shouldEqual('10.00')
        'Line Total (Excl Tax)'.shouldEqual('100.00')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('9.00')
        'Line Total (Excl Tax)'.shouldEqual('90.00')
        'Discount Type'.enter('Amount')
        'Discount Amount Per Unit'.shouldEqual('0.00')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('10.00')
        'Line Total (Excl Tax)'.shouldEqual('100.00')
        'Discount Amount Per Unit'.enter('2.50')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('7.50')
        'Line Total (Excl Tax)'.shouldEqual('75.00')
        'Apply Discount'.enter('No')
        'Unit Price (Excl Tax)'.shouldEqual('10.00')
        'Line Total (Excl Tax)'.shouldEqual('100.00')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.shouldEqual('7.50')
        'Line Total (Excl Tax)'.shouldEqual('75.00')
        'Unit Price Before Discount (Excl Tax)'.enter('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('17.50')
        'Line Total (Excl Tax)'.shouldEqual('175.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_cub')
    'Name'.enter('Carlton and United Breweries')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_oph')
    'Name'.enter('Sydney Opera House')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_ccb')
    'Name'.enter('Cascade Brewery')
    'Password'.enter('secret')
    'OK'.click()
  'Discounts'.click()
    'Discount Rules'.shouldBeCurrentPage()
    'Add'.click()
      'Description'.enter('Corn Flakes and Hoodies')
      'Discount Type'.enter('Percentage')
      'Percentage'.enter('20')
      'Add Products'.click()
        'Add Products to Discount Rule'.shouldBeCurrentPage()
        'searcher'.enter('Corn Flakes')
        'Select All'.click()
        'OK'.click()
      'Product Categories (comma separated, leave blank for all)'.enter('Hoodies')
      'Products'.shouldHaveCount(1)
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('10')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Automatically Show Discounts In Store'.enter('Yes')
  'OK'.click()
'helper'.addWCOrder({customer: 'Sydney Cricket Ground', product: 'Corn Flakes (CF01)', quantity: 10, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Discount Rules'.click()
    'Customer Groups'.click()
      'Customer Groups'.shouldBeCurrentPage()
      'Add'.click()
        'Add Customer Group'.shouldBeCurrentPage()
        'Group Name'.enter('VIC')
        'Description'.enter('Victoria')
        'Add Customers'.click()
          'Add Customers to Group'.shouldBeCurrentPage()
          'Select All'.click()
          'Select None'.click()
          'searcher'.enter('melb')
          'mainTable./Melbourne Cricket Ground/.Include'.toggleTick()
          'searcher'.enter('carl')
          'mainTable./Carlton and United Breweries/.Include'.toggleTick()
          'searcher'.enter('cascade')
          'mainTable./Cascade Brewery/.Include'.toggleTick()
          'OK'.click()
        'Customers'.shouldHaveCount(3)
        'Customers./Cascade Brewery (prfi_ccb)/.Remove'.click()
        'Customers./Cascade Brewery (prfi_ccb)/.Really Remove?'.click()
        'Customers'.shouldHaveCount(2)
        'Add another'.click()
        'Group Name'.enter('NSW')
        'Description'.enter('New South Wales')
        'Add Customers'.click()
          'searcher'.enter('Sydney')
          'Select All'.click()
          'OK'.click()
        'Customers'.shouldHaveCount(2)
        'Add another'.click()
        'Group Name'.enter('TAS')
        'Description'.enter('Tasmania')
        'Add another'.click()
        'Group Name'.enter('SA')
        'Description'.enter('South Australia')
        'OK'.click()
      'mainTable'.shouldHaveCount(4)
      'mainTable./VIC/.Description'.shouldEqual('Victoria')
      'mainTable./VIC/.Edit'.click()
        'Edit Customer Group'.shouldBeCurrentPage()
        'OK'.click()
      'mainTable./TAS/.Trash'.click()
      'mainTable./TAS/.Really Trash?'.click()
      'mainTable'.shouldHaveCount(3)
      'Back'.click()
    'Add'.click()
      'Add Discount Rule'.shouldBeCurrentPage()
      'Description'.enter('NSW Hoodies 20%')
      'Customer Groups (comma separated, leave blank for all)'.enter('NSW,TAS')
      'Product Categories (comma separated, leave blank for all)'.enter('Hoodies')
      'Discount Type'.shouldEqual('Percentage')
      'Percentage'.enter('20')
      'Fixed Price'.shouldntExist()
      'Add another'.click()
      'stFormRejection'.shouldContain('Customer Group TAS does not exist')
      'Customer Groups (comma separated, leave blank for all)'.enter('NSW')
      'Add another'.click()
      'Description'.enter('VIC and SA Tshirts 2.50')
      'Customer Groups (comma separated, leave blank for all)'.enter('VIC,SA')
      'Product Categories (comma separated, leave blank for all)'.enter('Tshirts,Elephants')
      'Discount Type'.enter('Amount')
      'Fixed Price'.enter('7.50')
      'Percentage'.shouldntExist()
      'Add another'.click()
      'stFormRejection'.shouldContain('Product Category Elephants does not exist')
      'Product Categories (comma separated, leave blank for all)'.enter('Tshirts')
      'Add another'.click()
      'Description'.enter('Test only')
      'OK'.click()
    'mainTable'.shouldHaveCount(4)
    'mainTable./NSW Hoodies 20%/.Edit'.click()
      'Edit Discount Rule'.shouldBeCurrentPage()
      'OK'.click()
    'mainTable./Test only/.Trash'.click()
    'mainTable./Test only/.Really Trash?'.click()
    'mainTable'.shouldHaveCount(3)
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'searcher'.enter('vn')
  'mainTable./Vneck Tshirt (V01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Automatically Show Discounts In Store'.enter('Yes')
  'OK'.click()
'helper'.addWCOrder({customer: 'Sydney Cricket Ground', product: 'Hoodie with Pocket (HP01)', quantity: 10, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'helper'.addWCOrder({customer: 'Melbourne Cricket Ground', product: 'Vneck Tshirt (V01)', quantity: 10, orderDate: global.todayLocal(), status: 'wc-processing', useProductPrice: true})
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Amount')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount Amount Per Unit'.shouldEqual('2.50')
        'Unit Price (Excl Tax)'.shouldEqual('7.50')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('75.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Discount Rules'.click()
    'mainTable'.shouldHaveCount(3)
    'mainTable./NSW Hoodies 20%/.Percentage'.shouldEqual('20.00')
    'mainTable./Corn Flakes and Hoodies/.Trash'.click()
    'mainTable./Corn Flakes and Hoodies/.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('Yes')
        'Product'.enter('Brag Set (BS01)')
        'Apply Discount'.shouldEqual('No')
        'Discount Type'.shouldntExist()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00') // New field.    'Line Total Before Discount (Excl Tax)'.shouldEqual('100.00') // _line_subtotal
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00') // note: use existing field
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('No')
        'Discount Type'.shouldntExist()
        'Unit Price Before Discount (Excl Tax)'.shouldntExist()
        'Discount %'.shouldntExist()
        'Unit Price (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Excl Tax)'.enter('20.00')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Customer'.enter('Melbourne Cricket Ground (prfi_mcg)')
      'Add Line'.click()
        'Product'.enter('Vneck Tshirt (V01)')
        'Apply Discount'.shouldEqual('Yes')
        'Quantity'.enter('10')
        'Discount Type'.shouldEqual('Amount')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00')
        'Discount Amount Per Unit'.shouldEqual('2.50')
        'Unit Price (Excl Tax)'.shouldEqual('7.50')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('75.00')
        'Line Total (Inc Tax)'.shouldEqual('82.50')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(3)
  'Back'.click()
'1'.chapter()
'helper'.clearWCOrders()
'helper'.trashAll('*')
'helper'.clearWCStockLevels()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (kevin.costly)')
      'billingCountry'.enter('Australia')
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Apply Discount'.shouldEqual('No')
        'Quantity'.enter('100')
        'Unit Price (Excl Tax)'.enter('181.82')
        'OK'.click()
      'Add another'.click()
      'Customer'.shouldEqual('')
      'Lines'.shouldBeEmpty()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('100')
        'Unit Price (Excl Tax)'.enter('181.82')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable'.shouldHaveCount(2)
  'Manage Orders'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'mainTable.0.Edit'.click()
    'Edit Sales Order'.shouldBeCurrentPage()
    'Lines./Big Bag/.Quantity'.shouldEqual('100')
    'OK'.click()
  'Manage Orders'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'mainTable'.shouldHaveCount(0)
  'Manage Orders'.click()
    'Sales Orders'.shouldBeCurrentPage()
    'mainTable'.shouldHaveCount(0)
    'Add'.click()
      'Add Sales Order'.shouldBeCurrentPage()
      'Order Date'.shouldEqualExpression('global.todayLocal()')
      'Customer'.clickDropdown()
      'Customer'.shouldHaveOption('Fester Inc (johnny.appleseed)')
      'Customer'.chooseOption('Fester Inc (johnny.appleseed)')
      'Customer Reference'.enter('JA01')
      'Requested ETA Date'.shouldEqual('')
      'Requested ETA Date'.enterExpression('global.todayLocal().incDays(30)')
      'billingCountry'.enter('Australia')
      'Total'.shouldEqual('0.00')
      'Tax'.shouldEqual('0.00')
      'Lines'.shouldHaveCount(0)
      'Add Line'.click()
        'Add Sales Order Line'.shouldBeCurrentPage()
        'Line Type'.shouldEqual('Product')
        'Line Type'.clickDropdown()
        'Line Type'.shouldHaveOption('Product')
        'Line Type'.shouldHaveOption('Fee')
        'Line Type'.shouldHaveOption('Shipping')
        'Shipping Method'.shouldntExist()
        'Product'.enter('Big Bag (BB01)')
        'Description'.shouldEqual('Big Bag')
        'Description'.enter('Big Bag Test')
        'Quantity'.shouldEqual('1')
        'Quantity'.enter('100')
        'Unit Price (Excl Tax)'.enter('181.82')
        'Tax %'.shouldBeReadOnly()
        'Tax %'.shouldEqual('10.00')
        'Line Total (Inc Tax)'.shouldEqual('20,000.20')
        'Line Total (Inc Tax)'.shouldBeReadOnly()
        'Tax'.shouldEqual('1,818.20')
        'Tax'.shouldBeReadOnly()
        'Add another line'.click()
        'Line Type'.enter('Shipping')
        'Shipping Method'.shouldExist()
        'Description'.enter('Shipping Test')
        'OK'.click()
        'stFormRejection'.shouldContain('Shipping Method is required')
        'Unit Price (Excl Tax)'.shouldEqual('0.00')
        'Shipping Method'.clickDropdown()
        'Shipping Method'.shouldHaveNOptions(4) // including blank
        'Shipping Method'.shouldHaveOption('Australia et al: Local pickup')
        'Shipping Method'.chooseOption('Australia et al: Local pickup')
        'Unit Price (Excl Tax)'.shouldEqual('30.00')
        'Unit Price (Excl Tax)'.enter('1.00')
        'Tax %'.enter('10')
        'Add another line'.click()
        'Line Type'.enter('Fee')
        'Description'.enter('Fee Test')
        'Unit Price (Excl Tax)'.enter('3.00')
        'Tax %'.enter('10')
        'OK'.click()
      'Lines'.shouldHaveCount(3)
      'OK'.click()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'mainTable.0.View Order'.click()
    'Shipping'.shouldEqual('1.00')
    'Lines'.shouldHaveCount(3)
    'Lines./Shipping Test/.Amount Inc Tax'.shouldEqual('1.10')
    'Lines./Fee Test/.Amount Inc Tax'.shouldEqual('3.30')
    'Edit Order'.click() 
      'Edit Sales Order'.shouldBeCurrentPage()
      'Lines'.shouldHaveCount(3)
      'Lines./Shipping Test/.Edit'.click()
        'Shipping Method'.shouldEqual('Australia et al: Local pickup')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Shipping Test/.Edit'.click()
        'Description'.enter('Shipping Test 2')
        'Unit Price (Excl Tax)'.enter('2.00')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'mainTable.0.View Order'.click()
    'Shipping'.shouldEqual('2.00')
    'Lines./Shipping Test 2/.Amount Inc Tax'.shouldEqual('2.20')
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Fee Test/.Unit Price (Excl Tax)'.enter('4')
      'OK'.click()
    'Back'.click()
  'mainTable.0.View Order'.click()
    'Lines./Fee Test/.Amount Inc Tax'.shouldEqual('4.40')
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines./Fee Test/.Trash'.click()
      'Lines./Fee Test/.Really Trash?'.click()
      'OK'.click()
    'Back'.click()
  'mainTable.0.View Order'.click()
    'Lines'.shouldHaveCount(2)
    'Back'.click()
  'Back'.click()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.enter('No')
  'OK'.click()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.shouldEqual('No')
  'OK'.click()
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Use Database Subselects Instead of Joins'.shouldEqual('No')
  'OK'.click()
'Sales and Invoices'.click()
  'mainTable.0.View Order'.click()
    'Lines'.shouldHaveCount(2)
    'Shipping'.shouldEqual('2.00')
    'Lines./Shipping Test 2/.Amount Inc Tax'.shouldEqual('2.20')
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines'.shouldHaveCount(2)
      'Lines./Shipping Test 2/.Trash'.click()
      'Lines./Shipping Test 2/.Really Trash?'.click()
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('99')
        'Unit Price (Excl Tax)'.enter('180.91')
        'Tax %'.shouldEqual('10.00')
        'Add another line'.click()
        'Product'.enter('Hoodie (H01)')
        'Quantity'.enter('99')
        'Unit Price (Excl Tax)'.enter('180.91')
        'Tax %'.shouldEqual('0.00')
        'Add another line'.click()
        'Line Type'.enter('Shipping')
        'Shipping Method'.enter('Australia et al: Flat rate')
        'Product'.shouldntExist()
        'Quantity'.shouldEqual('1')
        'Unit Price (Excl Tax)'.enter('1.82')
        'Tax %'.enter('10')
        'Add another line'.click()
        'Line Type'.enter('Fee')
        'Product'.shouldntExist()
        'Unit Price (Excl Tax)'.enter('2.73')
        'Tax %'.enter('10')
        'OK'.click()
      'Lines'.shouldHaveCount(5)
      'Products'.shouldEqual('54,002.18')
      'Shipping'.shouldEqual('1.82')
      'Fees'.shouldEqual('2.73')
      'totalTax'.shouldEqual('3,609.66')
      'Total'.shouldEqual('57,616.39')
      'OK'.click()
    'Back'.click()
  'mainTable.0.View Order'.click()
    'Lines'.shouldHaveCount(5)
    'Products'.shouldEqual('54,002.18')
    'Shipping'.shouldEqual('1.82')
    'Fees'.shouldEqual('2.73')
    'totalTax'.shouldEqual('3,609.66')
    'Total'.shouldEqual('AUD 57,616.39')
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines'.shouldHaveCount(5)
      'Lines./Big Bag Test/.SKU'.shouldEqual('BB01')
      'Lines./Big Bag Test/.Quantity'.shouldEqual('100')
      'Lines./Big Bag Test/.Unit Price (Excl Tax)'.shouldEqual('181.82')
      'Lines./Big Bag Test/.Line Total (Inc Tax)'.shouldEqual('20,000.20')
      'Lines./Cap/.Quantity'.enter('101')
      'Lines./Cap/.Unit Price (Excl Tax)'.enter('181.82')
      'Lines./Hoodie/.Trash'.click()
      'Lines./Hoodie/.Really Trash?'.click()
      'Lines'.shouldHaveCount(4)
      'Lines./Cap/.Edit'.click()
        'Edit Sales Order Line'.shouldBeCurrentPage()
        'Quantity'.shouldEqual('101')
        'Quantity'.enter('100')
        'OK'.click()
      'Lines./Cap/.Quantity'.shouldEqual('100')
      'Status'.enter('Processing')
      'OK'.click()
    'helper'.checkWCStockLevel('Big Bag (BB01)', -100, "frontend")
    'Add'.click()
      'Customer'.enter('Fester Inc (kevin.costly)')
      'billingCountry'.enter('Australia')
      'Add Line'.click()
        'Product'.enter('Big Bag (BB01)')
        'Quantity'.enter('100')
        'Unit Price (Excl Tax)'.enter('181.82')
        'Tax %'.shouldEqual('10.00')
        'Add another line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('100')
        'Unit Price (Excl Tax)'.enter('181.82')
        'Tax %'.shouldEqual('10.00')
        'OK'.click()
      'Status'.enter('Processing')
      'OK'.click()
    'helper'.checkWCStockLevel('Big Bag (BB01)', -200, "frontend")
    'mainTable.<columnHeadings>.Order'.click()
    'mainTable.1.Edit'.click()
      'Lines'.shouldHaveCount(2)
      'Lines./001/.Description'.shouldEqual('Big Bag')
      'Lines./002/.Description'.shouldEqual('Cap')
      'Add Line'.click()
        'Line Type'.enter('Fee')
        'Description'.enter('Fee Test 1')
        'Unit Price (Excl Tax)'.enter('10.00')
        'Tax %'.enter('10')
        'OK'.click()
      'Add Line'.click()
        'Line Type'.enter('Fee')
        'Description'.enter('Fee Test 2')
        'Unit Price (Excl Tax)'.enter('20.00')
        'Tax %'.enter('10')
        'OK'.click()
      'Lines./003/.Description'.shouldEqual('Fee Test 1')
      'Lines./004/.Description'.shouldEqual('Fee Test 2')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(4) // product lines only - no fees
  'mainTable.<columnHeadings>.Order Number'.click()
  'mainTable.2.View Order'.click()
    'Fees'.shouldEqual('30.00')
    'Total'.shouldEqual('AUD 40,033.40')
    'Lines'.shouldHaveCount(4)
    'Lines.2.Description'.shouldEqual('Fee Test 1')
    'Lines.2.Amount'.shouldEqual('10.00')
    'Lines.2.Tax'.shouldEqual('1.00')
    'Lines.2.Amount Inc Tax'.shouldEqual('11.00')
    'Lines.3.Description'.shouldEqual('Fee Test 2')
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(4)
  'mainTable.<columnHeadings>.Order Number'.click()
  'mainTable.2.View Order'.click()
    'Fees'.shouldEqual('30.00')
    'Total'.shouldEqual('AUD 40,033.40')
    'Back'.click()
  'Back'.click()
'helper'.clearWCOrders()
'helper'.trashAll('SO')
'helper'.trashAll('SOLine')
'helper'.trashAll('Inventory')
'helper'.trashAll('Location')
'helper'.trashAll('Configuration')
'helper'.trashAll('Template')
'helper'.trashAll('Cluster')
'helper'.trashAll('Bundle')
'helper'.trashAll('Preempt')
'helper'.trashAll('POReceipt')
'helper'.trashAll('PO')
'helper'.trashAll('Lot')
'helper'.trashAll('Allotment')
'helper'.trashAll('Allocation')
'helper'.trashAll('AllocationLine')
'helper'.trashAll('SOShipment')
'helper'.trashAll('SOShipmentLine')
'helper'.trashAll('Credit')
'helper'.trashAll('Debtor')
'helper'.trashAll('Preorder')
'helper'.trashAll('NextNumber')
'helper'.trashAll('Impost')
'helper'.clearWCStockLevels()
'helper'.setWCStockLevel('Big Bag (BB01)', 500)
'helper'.setWCStockLevel('Cap (C01)', 500)
'helper'.simulateBrowserRefresh()
'stocktend_settings'.click()
  'Imposts'.click()
    'Add'.click()
      'Add Impost'.shouldBeCurrentPage()
      'Description'.enter('Chemtax')
      'Customer Meta Field Name'.enter('registered_chemtax')
      'Add Classifier'.click()
        'Classifier Description'.enter('Type')
        'Product Meta Field Name'.enter('kemikalieskatt_type')
        'Default Value'.enter('Whitegoods')
        'Add Classification'.click()
          'Classification Value'.enter('Whitegoods')
          'Add another'.click()
          'Classification Value'.enter('Other')
          'OK'.click()
        'Add another'.click()
        'Classifier Description'.enter('Discount')
        'Product Meta Field Name'.enter('kemikalieskatt_discount')
        'Default Value'.enter('50')
        'Add Classification'.click()
          'Classification Value'.enter('0')
          'Add another'.click()
          'Classification Value'.enter('50')
          'Add another'.click()
          'Classification Value'.enter('90')
          'OK'.click()
        'OK'.click()
      'Javascript Function To Calculate Impost'.removeInputLine(5)
      'Javascript Function To Calculate Impost'.removeInputLine(4)
      'Javascript Function To Calculate Impost'.addLine("  let rates = { ")
      'Javascript Function To Calculate Impost'.addLine("    'Whitegoods': {")
      'Javascript Function To Calculate Impost'.addLine("      maxWeight: 9999999,")
      'Javascript Function To Calculate Impost'.addLine("      maxCharge: 9999999,")
      'Javascript Function To Calculate Impost'.addLine("      rate: 11")
      'Javascript Function To Calculate Impost'.addLine("    },")
      'Javascript Function To Calculate Impost'.addLine("    'Other': {")
      'Javascript Function To Calculate Impost'.addLine("      maxWeight: 3,")
      'Javascript Function To Calculate Impost'.addLine("      maxCharge: 451,")
      'Javascript Function To Calculate Impost'.addLine("      rate: 164")
      'Javascript Function To Calculate Impost'.addLine("    }")
      'Javascript Function To Calculate Impost'.addLine("  }")
      'Javascript Function To Calculate Impost'.addLine("'product'.m(product)")
      'Javascript Function To Calculate Impost'.addLine("  let rateObj = rates[product.kemikalieskatt_type]; if ( ! rateObj ) return 0")
      'Javascript Function To Calculate Impost'.addLine("  let weight = product.weight * quantity")
      'Javascript Function To Calculate Impost'.addLine("  let baseCharge = ")
      'Javascript Function To Calculate Impost'.addLine("    (weight >= rateObj.maxWeight) ")
      'Javascript Function To Calculate Impost'.addLine("      ? rateObj.maxCharge ")
      'Javascript Function To Calculate Impost'.addLine("      : rateObj.rate * weight")
      'Javascript Function To Calculate Impost'.addLine("  let multiplier = parseFloat(product.kemikalieskatt_discount, 10) / 100")
      'Javascript Function To Calculate Impost'.addLine("  let charge = baseCharge * multiplier")
      'Javascript Function To Calculate Impost'.addLine("  charge = Math.round((charge + Number.EPSILON) * 100) / 100 // round to 2 decimals")
      'Javascript Function To Calculate Impost'.addLine("  return charge")
      'Javascript Function To Calculate Impost'.addLine("}")
      'OK'.click()
    'Back'.click()
  'OK'.click()
'stocktend_inventory'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'Chemtax Type'.enter('Other')
    'Chemtax Discount'.enter('90')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'billingCountry'.enter('Australia')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('2')
        'Unit Price (Excl Tax)'.enter('181.82')
        'Tax %'.shouldEqual('10.00')
        'Add another line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('10')
        'Unit Price (Excl Tax)'.enter('27.27')
        'Tax %'.shouldEqual('10.00')
        'OK'.click()
      'Lines'.shouldHaveCount(4)
      'Lines.0.Description'.shouldEqual('Corn Flakes')
      'Lines.1.Description'.shouldEqual('Corn Flakes (CF01) - Chemtax')
      'Lines.2.Description'.shouldEqual('Cap')
      'Lines.3.Description'.shouldEqual('Cap (C01) - Chemtax')
      'Lines.3.Line Total (Inc Tax)'.shouldEqual('275.00')
      'Lines.2.Edit'.click()
        'Quantity'.enter('20')
        'OK'.click()
      'Lines.3.Line Total (Inc Tax)'.shouldEqual('550.00')
      'Lines.2.Quantity'.enter('40')
      'Lines.3.Line Total (Inc Tax)'.shouldEqual('1,100.00')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'PreDisc'.chapter()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_mcg')
    'Name'.enter('Melbourne Cricket Ground')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Password'.enter('secret')
    'OK'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Hoodie with Pocket (HP01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Melbourne Cricket Ground (prfi_mcg)')
      'Add Line'.click()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('No')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('12.00')
        'Discount Type'.shouldEqual('Percentage')
        'Discount %'.enter('10')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('10.80')
        'Line Total (Inc Tax)'.shouldEqual('108.00')
        'Apply Discount'.enter('No')
        'Unit Price (Inc Tax)'.shouldEqual('12.00')
        'Line Total (Inc Tax)'.shouldEqual('120.00')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('10.80')
        'Line Total (Inc Tax)'.shouldEqual('108.00')
        'Discount Type'.enter('Amount')
        'Discount Amount Per Unit'.shouldEqual('0.00')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('12.00')
        'Line Total (Inc Tax)'.shouldEqual('120.00')
        'Discount Amount Per Unit'.enter('2.50')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('9.00')
        'Line Total (Inc Tax)'.shouldEqual('90.00')
        'Apply Discount'.enter('No')
        'Unit Price (Inc Tax)'.shouldEqual('12.00')
        'Line Total (Inc Tax)'.shouldEqual('120.00')
        'Apply Discount'.enter('Yes')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Unit Price (Inc Tax)'.shouldEqual('9.00')
        'Line Total (Inc Tax)'.shouldEqual('90.00')
        'Unit Price Before Discount (Excl Tax)'.enter('20.00')
        'Unit Price (Inc Tax)'.shouldEqual('21.00')
        'Line Total (Inc Tax)'.shouldEqual('210.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'stocktend_customers'.click()
  'Add'.click()
    'Login'.enter('prfi_cub')
    'Name'.enter('Carlton and United Breweries')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_scg')
    'Name'.enter('Sydney Cricket Ground')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_oph')
    'Name'.enter('Sydney Opera House')
    'Password'.enter('secret')
    'Billing'.usePanel()
    'Country'.enter('Australia')
    'Billing'.stopUsingPanel()
    'Shipping'.usePanel()
    'Country'.enter('Australia')
    'Shipping'.stopUsingPanel()
    'Add another'.click()
    'Login'.enter('prfi_ccb')
    'Name'.enter('Cascade Brewery')
    'Password'.enter('secret')
    'OK'.click()
  'Discounts'.click()
    'Add'.click()
      'Description'.enter('Corn Flakes and Hoodies')
      'Discount Type'.enter('Percentage')
      'Percentage'.enter('20')
      'Add Products'.click()
        'searcher'.enter('Corn Flakes')
        'Select All'.click()
        'OK'.click()
      'Product Categories (comma separated, leave blank for all)'.enter('Hoodies')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Corn Flakes (CF01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('10')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Inc Tax)'.shouldEqual('9.60')
        'Unit Price (Inc Tax)'.shouldBeReadOnly()
        'Line Total (Inc Tax)'.shouldEqual('96.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('10')
        'OK'.click()
      'Convert to WC Order'.click()
        'messageDialogText'.shouldEqual("Are you sure you want to convert this Preorder to a WC order?", 'doc')
        'Yes'.click('doc')
        'messageDialogText'.shouldEqual("New WC Order was created", 'doc')
        'OK'.click('doc')
    'Preorders'.shouldBeCurrentPage()
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Discount Rules'.click()
    'Customer Groups'.click()
      'Add'.click()
        'Group Name'.enter('VIC')
        'Description'.enter('Victoria')
        'Add Customers'.click()
          'Select All'.click()
          'Select None'.click()
          'searcher'.enter('mel')
          'mainTable./Melbourne Cricket Ground/.Include'.toggleTick()
          'searcher'.enter('carl')
          'mainTable./Carlton and United Breweries/.Include'.toggleTick()
          'searcher'.enter('cascade')
          'mainTable./Cascade Brewery/.Include'.toggleTick()
          'OK'.click()
        'Customers./Cascade Brewery (prfi_ccb)/.Remove'.click()
        'Customers./Cascade Brewery (prfi_ccb)/.Really Remove?'.click()
        'Add another'.click()
        'Group Name'.enter('NSW')
        'Description'.enter('New South Wales')
        'Add Customers'.click()
          'searcher'.enter('Sydney')
          'Select All'.click()
          'OK'.click()
        'Add another'.click()
        'Group Name'.enter('SA')
        'Description'.enter('South Australia')
        'OK'.click()
      'Back'.click()
    'Add'.click()
      'Description'.enter('NSW Hoodies 20%')
      'Customer Groups (comma separated, leave blank for all)'.enter('NSW,TAS')
      'Product Categories (comma separated, leave blank for all)'.enter('Hoodies')
      'Percentage'.enter('20')
      'Customer Groups (comma separated, leave blank for all)'.enter('NSW')
      'Add another'.click()
      'Description'.enter('VIC and SA Tshirts 2.50')
      'Customer Groups (comma separated, leave blank for all)'.enter('VIC,SA')
      'Product Categories (comma separated, leave blank for all)'.enter('Tshirts,Elephants')
      'Discount Type'.enter('Amount')
      'Fixed Price'.enter('7.50')
      'Product Categories (comma separated, leave blank for all)'.enter('Tshirts')
      'OK'.click()
    'Back'.click()
  'Back'.click()
'stocktend_inventory'.click()
  'mainTable./Cap (C01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'searcher'.enter('vn')
  'mainTable./Vneck Tshirt (V01)/.Edit Product'.click()
    'WooCommerce Regular Price'.enter('10.00')
    'OK'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Quantity'.enter('10')
        'OK'.click()
      'Convert to WC Order'.click()
        'messageDialogText'.shouldEqual("Are you sure you want to convert this Preorder to a WC order?", 'doc')
        'Yes'.click('doc')
        'messageDialogText'.shouldEqual("New WC Order was created", 'doc')
        'OK'.click('doc')
    'Preorders'.shouldBeCurrentPage()
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Excl Tax)'.shouldEqual('8.00')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('80.00')
        'Line Total (Inc Tax)'.shouldEqual('88.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Melbourne Cricket Ground (prfi_mcg)')
      'Add Line'.click()
        'Product'.enter('Vneck Tshirt (V01)')
        'Quantity'.enter('10')
        'OK'.click()
      'Convert to WC Order'.click()
        'messageDialogText'.shouldEqual("Are you sure you want to convert this Preorder to a WC order?", 'doc')
        'Yes'.click('doc')
        'messageDialogText'.shouldEqual("New WC Order was created", 'doc')
        'OK'.click('doc')
    'Preorders'.shouldBeCurrentPage()
    'Back'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Lines.0.Edit'.click()
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Amount')
        'Unit Price Before Discount (Excl Tax)'.shouldEqual('10.00')
        'Discount Amount Per Unit'.shouldEqual('2.50')
        'Unit Price (Excl Tax)'.shouldEqual('7.50')
        'Unit Price (Excl Tax)'.shouldBeReadOnly()
        'Line Total (Excl Tax)'.shouldEqual('75.00')
        'OK'.click()
      'OK'.click()
    'mainTable.0.Trash'.click()
    'mainTable.0.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Discount Rules'.click()
    'mainTable'.shouldHaveCount(3)
    'mainTable./NSW Hoodies 20%/.Percentage'.shouldEqual('20.00')
    'mainTable./Corn Flakes and Hoodies/.Trash'.click()
    'mainTable./Corn Flakes and Hoodies/.Really Trash?'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Preorders'.click()
    'Add'.click()
      'Customer'.enter('Sydney Cricket Ground (prfi_scg)')
      'Add Line'.click()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('Yes')
        'Product'.enter('Brag Set (BS01)')
        'Apply Discount'.shouldEqual('No')
        'Discount Type'.shouldntExist()
        'Product'.enter('Hoodie with Pocket (HP01)')
        'Apply Discount'.shouldEqual('Yes')
        'Discount Type'.shouldEqual('Percentage')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00')
        'Discount %'.shouldEqual('20.00')
        'Unit Price (Inc Tax)'.shouldEqual('9.60')
        'Unit Price (Inc Tax)'.shouldBeReadOnly()
        'Line Total (Inc Tax)'.shouldEqual('96.00')
        'OK'.click()
      'Add Line'.click()
        'Product'.enter('Cap (C01)')
        'Quantity'.enter('10')
        'Apply Discount'.shouldEqual('No')
        'Discount Type'.shouldntExist()
        'Unit Price Before Discount (Excl Tax)'.shouldntExist()
        'Discount %'.shouldntExist()
        'Unit Price (Inc Tax)'.shouldEqual('12.00')
        'Unit Price (Inc Tax)'.enter('24.00')
        'OK'.click()
      'OK'.click()
    'Add'.click()
      'Customer'.enter('Melbourne Cricket Ground (prfi_mcg)')
      'Add Line'.click()
        'Product'.enter('Vneck Tshirt (V01)')
        'Apply Discount'.shouldEqual('Yes')
        'Quantity'.enter('10')
        'Discount Type'.shouldEqual('Amount')
        'Unit Price Before Discount (Excl Tax)'.enter('10.00')
        'Discount Amount Per Unit'.shouldEqual('2.50')
        'Unit Price (Inc Tax)'.shouldEqual('9.00')
        'Unit Price (Inc Tax)'.shouldBeReadOnly()
        'Line Total (Inc Tax)'.shouldEqual('90.00')
        'OK'.click()
      'Convert to WC Order'.click()
        'messageDialogText'.shouldEqual("Are you sure you want to convert this Preorder to a WC order?", 'doc')
        'Yes'.click('doc')
        'messageDialogText'.shouldEqual("New WC Order was created", 'doc')
        'OK'.click('doc')
    'Preorders'.shouldBeCurrentPage()
    'Back'.click()
  'Back'.click()
'helper'.simulateBrowserRefresh()
'Sales and Invoices'.click()
  'mainTable'.shouldHaveCount(1)
  'Back'.click()
'DupSO'.chapter()
'helper'.allowExclusives()
'helper'.trashAll('*')
'helper'.simulateBrowserRefresh()
'helper'.allowExclusives()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'Add'.click()
      'Customer'.enter('Fester Inc (johnny.appleseed)')
      'billingCountry'.enter('Australia')
      'Add Line'.click()
        'Product'.enter('Hoodie with Logo (HL01)')
        'Quantity'.enter('2')
        'Unit Price (Excl Tax)'.enter('181.82')
        'Add another line'.click()
        'Product'.enter('Corn Flakes (CF01)')
        'Quantity'.enter('10')
        'Unit Price (Excl Tax)'.enter('27.27')
        'OK'.click()
      'Add Line'.click()
        'Line Type'.enter('Fee')
        'Description'.enter('Test Desc')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
'Sales and Invoices'.click()
  'Manage Orders'.click()
    'mainTable.0.Edit'.click()
      'Duplicate SO'.click()
        'messageDialogText'.shouldEqual("Sales Order Duplication Complete. You are now editing the new SO.")
        'messageDialogOK'.click()
      'billingCountry'.shouldEqual('Australia')
      'Lines'.shouldHaveCount(3)
      'OK'.click()
    'mainTable'.shouldHaveCount(2)
    'mainTable.1.Edit'.click() // the original, which is sorted last
      'Lines'.shouldHaveCount(3)
      'OK'.click()
    'mainTable.0.Edit'.click()
      'Lines./Hoodie with Logo/.Edit'.click()
        'Quantity'.shouldEqual('2')
        'Unit Price (Excl Tax)'.shouldEqual('181.82')
        'OK'.click()
      'Lines./Corn Flakes/.Edit'.click()
        'Quantity'.shouldEqual('10')
        'Unit Price (Excl Tax)'.shouldEqual('27.27')
        'OK'.click()
      'Lines./Test Desc/.Edit'.click()
        'Description'.shouldEqual('Test Desc')
        'Line Type'.shouldEqual('Fee')
        'OK'.click()
      'OK'.click()
    'Back'.click()
  'Back'.click()
